import type { StudioLeader, StudioTemplate } from "@/lib/studio/types";

/**
 * Ready-made HenryCo Studio websites. These sites are built and owned by
 * the studio — clients pick one, supply brand assets and copy, and the
 * studio launches a customised version inside the stated ready-in window.
 *
 * Pricing principles:
 *   • Numbers are real, expressed in NGN, and aligned with the package
 *     bands in `studioPackages` so proposals stay coherent.
 *   • Each template carries a `packageId` anchor so accepted briefs flow
 *     into the standard milestone-priced proposal pipeline.
 *   • Deposit rate matches the underlying package; the rest is paid on
 *     milestone approval.
 *   • The `preview` gradients are deliberate: they let us ship a
 *     tasteful, on-brand visual today without faking screenshots we
 *     don't yet have permission to publish.
 */
export const studioTemplates: StudioTemplate[] = [
  {
    id: "tpl-meridian-executive",
    slug: "meridian-executive",
    name: "Meridian — Executive Company Website",
    category: "business",
    serviceKind: "website",
    projectTypeLabel: "Executive company website",
    audience: "Founder-led firms, consultancies, and professional service businesses",
    tagline: "A premium six-page site that makes the company feel as serious as it is.",
    summary:
      "A calm, high-trust company website with a confident hero, plain-language services, and a contact path that captures qualified leads instead of generic enquiries.",
    price: 1950000,
    packageId: "pkg-executive-presence",
    depositRate: 0.45,
    timelineWeeks: 4,
    readyInDays: 14,
    pages: [
      "Home",
      "Services overview",
      "Service detail (3 pre-styled)",
      "About and team",
      "Insights or case studies",
      "Contact",
    ],
    features: [
      "Editable CMS-driven content",
      "Lead-capture form routed to inbox + WhatsApp",
      "On-page SEO and Open Graph cards",
      "Analytics + conversion event wiring",
      "Mobile-first layout with safe-area polish",
      "WCAG 2.1 AA contrast and focus pass",
    ],
    stack: ["Next.js", "Headless CMS", "Tailwind tokens", "Cloudflare or Vercel"],
    outcomes: [
      "Stronger first-impression credibility",
      "Higher-quality inbound leads",
      "A site you can extend without rebuilding",
    ],
    preview: { from: "#0e2a35", to: "#0a3b46", accent: "#97f4f3" },
    demoUrl: null,
  },
  {
    id: "tpl-helix-funnel",
    slug: "helix-funnel",
    name: "Helix — Offer & Revenue Funnel",
    category: "business",
    serviceKind: "website",
    projectTypeLabel: "Lead generation or campaign funnel",
    audience: "Coaches, agencies, and teams selling premium offers, programs, and cohorts",
    tagline: "Long-form offer page, trust layers, and a measurable conversion stack.",
    summary:
      "A campaign-grade funnel built around one premium offer: hero, proof, objections, FAQ, urgency, and a checkout-friendly CTA wired to your CRM.",
    price: 2450000,
    packageId: "pkg-revenue-funnel",
    depositRate: 0.4,
    timelineWeeks: 5,
    readyInDays: 18,
    pages: [
      "Long-form offer page",
      "Order or apply page",
      "Thank-you page with onboarding",
      "Light home (positioning page)",
      "Privacy and terms",
    ],
    features: [
      "A/B-ready hero variants",
      "Testimonial and case-proof modules",
      "Conversion analytics + pixel wiring",
      "Email capture + CRM hand-off",
      "Premium type & motion polish",
      "Performance budget (LCP < 2.5s on mobile)",
    ],
    stack: ["Next.js", "Tailwind tokens", "ConvertKit or Mailchimp ready", "Stripe-ready forms"],
    outcomes: [
      "Higher landing-page conversion",
      "Cleaner attribution to ad spend",
      "Sharper offer narrative",
    ],
    preview: { from: "#241433", to: "#3b1850", accent: "#f8b6e6" },
    demoUrl: null,
  },
  {
    id: "tpl-atelier-commerce",
    slug: "atelier-commerce",
    name: "Atelier — Premium Commerce Storefront",
    category: "commerce",
    serviceKind: "ecommerce",
    projectTypeLabel: "Premium e-commerce storefront",
    audience: "Beauty, fashion, lifestyle, and design brands ready for a premium catalog",
    tagline: "A commerce site that feels considered — not a templated checkout in a cheap suit.",
    summary:
      "A storefront with editorial product pages, a premium cart and checkout, and an admin layer the team actually wants to use day-to-day.",
    price: 3250000,
    packageId: "pkg-commerce-growth",
    depositRate: 0.4,
    timelineWeeks: 6,
    readyInDays: 28,
    pages: [
      "Home",
      "Collection / category",
      "Product detail",
      "Cart and checkout",
      "Account and order tracking",
      "Lookbook or campaign",
      "Policies and FAQs",
    ],
    features: [
      "Product variants and inventory rules",
      "Paystack or Flutterwave checkout",
      "Saved-items + wishlist",
      "Order email receipts (branded)",
      "Editorial CMS for collections",
      "Pickup vs delivery toggle",
    ],
    stack: ["Next.js", "Sanity CMS", "Paystack/Flutterwave", "Inventory webhooks"],
    outcomes: [
      "Higher AOV from clearer merchandising",
      "Lower abandoned-cart rate",
      "An admin layer that reduces manual work",
    ],
    preview: { from: "#1f1310", to: "#3a2018", accent: "#f6c483" },
    demoUrl: null,
  },
  {
    id: "tpl-foundry-marketplace",
    slug: "foundry-marketplace",
    name: "Foundry — Multi-Seller Marketplace",
    category: "commerce",
    serviceKind: "ecommerce",
    projectTypeLabel: "Premium e-commerce storefront",
    audience: "Operators launching curated multi-seller marketplaces or vertical commerce",
    tagline: "Sellers, listings, payouts, and trust signals — engineered to scale.",
    summary:
      "A marketplace surface with seller onboarding, listing moderation, escrow-style payouts, and the admin controls that keep an early marketplace from collapsing under its own weight.",
    price: 5650000,
    packageId: "pkg-commerce-growth",
    depositRate: 0.4,
    timelineWeeks: 10,
    readyInDays: 45,
    pages: [
      "Buyer storefront",
      "Listing search and filters",
      "Seller onboarding flow",
      "Seller dashboard",
      "Admin moderation surface",
      "Payouts and reporting",
    ],
    features: [
      "Seller KYC + listing approval",
      "Split payments / payouts",
      "Reviews and dispute trail",
      "Anti-fraud heuristics",
      "Audit log for admin actions",
      "Notifications across channels",
    ],
    stack: ["Next.js", "Supabase (RLS)", "Paystack split", "Resend"],
    outcomes: [
      "A marketplace launchable in weeks not quarters",
      "Operational visibility from day one",
      "Trust signals that reduce buyer friction",
    ],
    preview: { from: "#0f1f2a", to: "#15364a", accent: "#7adcff" },
    demoUrl: null,
  },
  {
    id: "tpl-cadence-bookings",
    slug: "cadence-bookings",
    name: "Cadence — Bookings & Appointments",
    category: "service",
    serviceKind: "custom_software",
    projectTypeLabel: "Marketplace or booking platform",
    audience: "Clinics, salons, tutors, trades, and consultants",
    tagline: "Take the schedule off your hands and put it on a confident booking page.",
    summary:
      "A booking site with availability windows, deposit-aware scheduling, reminder flows, and a clean staff calendar — designed to end the never-ending what-time-works thread.",
    price: 2150000,
    packageId: "pkg-executive-presence",
    depositRate: 0.4,
    timelineWeeks: 5,
    readyInDays: 21,
    pages: [
      "Service overview",
      "Booking flow (multi-step)",
      "Confirmation + reminders",
      "Customer account (history)",
      "Staff calendar",
      "Light home",
    ],
    features: [
      "Availability windows per service",
      "Deposit on booking (optional)",
      "Email + WhatsApp reminders",
      "Reschedule + cancel policies",
      "Staff role accounts",
      "Reports for repeat clients",
    ],
    stack: ["Next.js", "Supabase", "Resend", "WhatsApp Business"],
    outcomes: [
      "No more missed appointments",
      "Lower no-show rate from deposits",
      "Less time on admin coordination",
    ],
    preview: { from: "#0a2620", to: "#0e3b30", accent: "#6effc0" },
    demoUrl: null,
  },
  {
    id: "tpl-prospect-realestate",
    slug: "prospect-realestate",
    name: "Prospect — Property & Listings",
    category: "service",
    serviceKind: "website",
    projectTypeLabel: "Executive company website",
    audience: "Agents, developers, and property managers",
    tagline: "Show real listings, capture serious buyers, and keep weak leads out of the inbox.",
    summary:
      "A property site with map, search, listing detail, lead capture, and an agent-facing dashboard — built to surface inventory cleanly and qualify enquiries.",
    price: 2750000,
    packageId: "pkg-revenue-funnel",
    depositRate: 0.4,
    timelineWeeks: 6,
    readyInDays: 24,
    pages: [
      "Listings index (with filters)",
      "Listing detail",
      "Map view",
      "Agent profile",
      "Buyer enquiry flow",
      "Saved searches",
    ],
    features: [
      "Filter by price / size / location",
      "Photo galleries with zoom",
      "Mortgage / rent calculator",
      "Agent enquiry routing",
      "Saved searches with email alerts",
      "Map integration (Google or Mapbox)",
    ],
    stack: ["Next.js", "Supabase", "Mapbox", "Resend"],
    outcomes: [
      "Better lead qualification",
      "More confident buyer enquiries",
      "An inventory layer the team can manage",
    ],
    preview: { from: "#1a1530", to: "#2b1d56", accent: "#a89aff" },
    demoUrl: null,
  },
  {
    id: "tpl-orbit-portfolio",
    slug: "orbit-portfolio",
    name: "Orbit — Portfolio & Personal Brand",
    category: "creative",
    serviceKind: "website",
    projectTypeLabel: "Executive company website",
    audience: "Creatives, experts, and public-facing professionals",
    tagline: "Quiet confidence — your work, your story, and a clear way to hire you.",
    summary:
      "A typographically considered portfolio with case study modules, a calm bio, press mentions, and a sharp contact path. Designed for people whose work should speak first.",
    price: 1450000,
    packageId: "pkg-brand-interface",
    depositRate: 0.5,
    timelineWeeks: 3,
    readyInDays: 12,
    pages: [
      "Home (curated reel)",
      "Selected work",
      "Case study (3 pre-styled)",
      "About and bio",
      "Press / mentions",
      "Contact",
    ],
    features: [
      "Editorial type + tasteful motion",
      "Lazy-loaded gallery",
      "Inline video embed",
      "Press wall module",
      "RSS / Substack ready",
      "Mobile-first reading rhythm",
    ],
    stack: ["Next.js", "Tailwind", "Sanity CMS", "Vercel"],
    outcomes: [
      "Higher quality enquiries",
      "Stronger personal positioning",
      "A site that ages gracefully",
    ],
    preview: { from: "#1a181a", to: "#252127", accent: "#e8d8b0" },
    demoUrl: null,
  },
  {
    id: "tpl-academy-school",
    slug: "academy-school",
    name: "Academy — School & Education Portal",
    category: "service",
    serviceKind: "website",
    projectTypeLabel: "Client portal or account workspace",
    audience: "Schools, academies, and training centres",
    tagline: "Parents and students find what they need without hunting through PDFs.",
    summary:
      "A calm school site with admissions, calendar, news, downloads, and a parent-facing portal that puts notices, term reports, and forms in one place.",
    price: 2950000,
    packageId: "pkg-client-portal",
    depositRate: 0.4,
    timelineWeeks: 7,
    readyInDays: 28,
    pages: [
      "Home with calendar strip",
      "Admissions",
      "Programs / curriculum",
      "News and announcements",
      "Parent / student portal (auth)",
      "Resources and downloads",
    ],
    features: [
      "Authenticated parent portal",
      "Forms and signed downloads",
      "Term calendar feed",
      "Email broadcast for notices",
      "Role-aware moderation",
      "Accessibility-first reading",
    ],
    stack: ["Next.js", "Supabase auth", "Resend", "Sanity CMS"],
    outcomes: [
      "Less admin overhead per term",
      "Faster, calmer parent communication",
      "An archive of announcements that scales",
    ],
    preview: { from: "#0d1d3a", to: "#102e58", accent: "#8fb6ff" },
    demoUrl: null,
  },
  {
    id: "tpl-cohort-learning",
    slug: "cohort-learning",
    name: "Cohort — Courses & Online Learning",
    category: "creative",
    serviceKind: "custom_software",
    projectTypeLabel: "Client portal or account workspace",
    audience: "Coaches, schools, and course creators ready to monetise teaching",
    tagline: "Lessons, member sign-in, progress, and a payment path that doesn't break.",
    summary:
      "A learning surface with course pages, member auth, lesson playback, progress tracking, and Paystack-ready paid enrolment.",
    price: 3450000,
    packageId: "pkg-client-portal",
    depositRate: 0.4,
    timelineWeeks: 8,
    readyInDays: 32,
    pages: [
      "Course catalog",
      "Course detail / curriculum",
      "Lesson player",
      "Member dashboard",
      "Enrol & pay flow",
      "Tutor / instructor profile",
    ],
    features: [
      "Member accounts + roles",
      "Lesson progress tracking",
      "Paid enrolment via Paystack",
      "Quiz or check-in module",
      "Cohort calendar + replays",
      "Email reminders + drip",
    ],
    stack: ["Next.js", "Supabase", "Mux/Bunny video", "Paystack"],
    outcomes: [
      "Recurring revenue from cohorts",
      "Cleaner student experience",
      "A learning platform you can extend",
    ],
    preview: { from: "#1b0a30", to: "#2e1656", accent: "#c79cff" },
    demoUrl: null,
  },
  {
    id: "tpl-sanctuary-church",
    slug: "sanctuary-church",
    name: "Sanctuary — Church & Ministry",
    category: "service",
    serviceKind: "website",
    projectTypeLabel: "Executive company website",
    audience: "Congregations, charities, and faith-based organisations",
    tagline: "Events, giving, and stories that read beautifully on phones and large screens.",
    summary:
      "A respectful, story-led ministry site with a service calendar, sermon archive, secure giving, and a calm volunteer surface.",
    price: 1650000,
    packageId: "pkg-executive-presence",
    depositRate: 0.45,
    timelineWeeks: 4,
    readyInDays: 16,
    pages: [
      "Home with service times",
      "About / leadership",
      "Sermons / media",
      "Events calendar",
      "Giving (secure)",
      "Volunteer / serve",
    ],
    features: [
      "Sermon audio and video archive",
      "Recurring giving via Paystack",
      "Event RSVPs",
      "Volunteer signup forms",
      "Multi-campus structure",
      "Newsletter capture",
    ],
    stack: ["Next.js", "Sanity CMS", "Paystack subscriptions", "Mailchimp"],
    outcomes: [
      "Higher engagement on stories and sermons",
      "More predictable giving",
      "Less weekly admin for volunteers",
    ],
    preview: { from: "#22180a", to: "#3a2710", accent: "#e8b770" },
    demoUrl: null,
  },
  {
    id: "tpl-strata-operations",
    slug: "strata-operations",
    name: "Strata — Operations Control Room",
    category: "internal",
    serviceKind: "internal_system",
    projectTypeLabel: "Internal operations dashboard",
    audience: "Service businesses, dispatch teams, and multi-role operations leads",
    tagline: "Replace the spreadsheet sprawl with one disciplined operations surface.",
    summary:
      "A multi-role internal platform: leads, projects, stages, approvals, and management reporting. Designed for the moment a team outgrows shared sheets.",
    price: 3900000,
    packageId: "pkg-control-room",
    depositRate: 0.4,
    timelineWeeks: 8,
    readyInDays: 36,
    pages: [
      "Role-based dashboards",
      "Lead pipeline",
      "Project stages with approvals",
      "Reporting view",
      "Audit log",
      "Settings & roles",
    ],
    features: [
      "Role-based access control",
      "Configurable pipeline stages",
      "Approvals + sign-offs",
      "Reporting tiles",
      "Audit log on every write",
      "Notifications + email digest",
    ],
    stack: ["Next.js", "Supabase (RLS)", "Resend", "Charts"],
    outcomes: [
      "Operational visibility across teams",
      "Less manual coordination by chat",
      "A system the team trusts to stay current",
    ],
    preview: { from: "#0c1422", to: "#152135", accent: "#7da9ff" },
    demoUrl: null,
  },
  {
    id: "tpl-relay-portal",
    slug: "relay-portal",
    name: "Relay — Client Portal Accelerator",
    category: "internal",
    serviceKind: "custom_software",
    projectTypeLabel: "Client portal or account workspace",
    audience: "Service businesses replacing endless email threads with a real workspace",
    tagline: "Onboarding, updates, files, approvals, and payment checkpoints in one room.",
    summary:
      "A secure client-facing portal with onboarding, status updates, a file vault, approvals, and a payment-aware delivery path.",
    price: 4650000,
    packageId: "pkg-client-portal",
    depositRate: 0.4,
    timelineWeeks: 9,
    readyInDays: 40,
    pages: [
      "Client onboarding",
      "Project workspace",
      "File vault",
      "Approvals queue",
      "Payments + receipts",
      "Support thread",
    ],
    features: [
      "Secure access keys + auth",
      "Files with previews",
      "Approval flow with audit",
      "Payment proof upload",
      "Branded receipts (PDF)",
      "Real-time notifications",
    ],
    stack: ["Next.js", "Supabase (RLS)", "Resend", "Cloudinary"],
    outcomes: [
      "Less back-and-forth in email",
      "A delivery record clients trust",
      "Faster approvals and milestone unlocks",
    ],
    preview: { from: "#0f1d2c", to: "#163048", accent: "#7af0d4" },
    demoUrl: null,
  },
  {
    id: "tpl-vector-mobile",
    slug: "vector-mobile",
    name: "Vector — Mobile Customer App",
    category: "mobile",
    serviceKind: "mobile_app",
    projectTypeLabel: "Mobile app",
    audience: "Brands and operators with a customer base on phones",
    tagline: "A real installable app — planned, built, and released the way it should be.",
    summary:
      "A cross-platform mobile app: onboarding, account, core flow, push notifications, and the release plan that turns version 1.0 into a real shipped product.",
    price: 4850000,
    packageId: "pkg-control-room",
    depositRate: 0.45,
    timelineWeeks: 11,
    readyInDays: 49,
    pages: [
      "Onboarding (3 screens)",
      "Account / profile",
      "Core feature flow",
      "Notifications inbox",
      "Settings",
      "Help / support",
    ],
    features: [
      "iOS + Android via React Native",
      "Push notifications",
      "Auth + account sync",
      "Offline-tolerant data layer",
      "Release pipeline (TestFlight, internal track)",
      "Analytics + crash reporting",
    ],
    stack: ["React Native", "Expo", "Supabase", "OneSignal"],
    outcomes: [
      "A real launchable mobile app",
      "Higher retention from push",
      "A release process that doesn't stall",
    ],
    preview: { from: "#180f25", to: "#2a1742", accent: "#ff8fdc" },
    demoUrl: null,
  },
  {
    id: "tpl-canvas-agency",
    slug: "canvas-agency",
    name: "Canvas — Agency / Studio Website",
    category: "creative",
    serviceKind: "website",
    projectTypeLabel: "Lead generation or campaign funnel",
    audience: "Creative, marketing, and consulting teams selling case-led work",
    tagline: "Lead with proof — case stories, services, and a confident first impression.",
    summary:
      "An agency site that puts the work first: a curated reel, named case studies with real metrics, a focused services page, and a contact path that screens for fit.",
    price: 1850000,
    packageId: "pkg-executive-presence",
    depositRate: 0.45,
    timelineWeeks: 4,
    readyInDays: 16,
    pages: [
      "Home (case-led reel)",
      "Selected work",
      "Case study (4 pre-styled)",
      "Services",
      "About",
      "Contact / brief",
    ],
    features: [
      "Editorial case study layout",
      "Service-to-case linking",
      "Metric tiles + testimonials",
      "Lead-screen brief form",
      "Press wall module",
      "Performance-tuned images",
    ],
    stack: ["Next.js", "Sanity CMS", "Tailwind tokens", "Vercel"],
    outcomes: [
      "Higher-fit inbound briefs",
      "Cleaner positioning narrative",
      "A site you can update without devs",
    ],
    preview: { from: "#1c1b18", to: "#2a2722", accent: "#f3eedc" },
    demoUrl: null,
  },
];

export const studioTemplateCategories: Array<{
  id: string;
  label: string;
  blurb: string;
}> = [
  {
    id: "business",
    label: "Business",
    blurb: "Company sites, executive positioning, and lead-generation funnels.",
  },
  {
    id: "commerce",
    label: "Commerce",
    blurb: "Storefronts, multi-seller marketplaces, and premium catalog sites.",
  },
  {
    id: "service",
    label: "Service",
    blurb: "Bookings, property listings, schools, and ministry sites.",
  },
  {
    id: "creative",
    label: "Creative",
    blurb: "Portfolios, course platforms, and agency websites.",
  },
  {
    id: "internal",
    label: "Internal",
    blurb: "Operations control rooms and client portals for serious teams.",
  },
  {
    id: "mobile",
    label: "Mobile",
    blurb: "Cross-platform apps planned, built, and released with discipline.",
  },
];

export function getStudioTemplateBySlug(slug: string): StudioTemplate | null {
  const normalized = slug?.trim().toLowerCase();
  if (!normalized) return null;
  return studioTemplates.find((tpl) => tpl.slug === normalized) ?? null;
}

export function listStudioTemplatesByCategory(categoryId: string): StudioTemplate[] {
  return studioTemplates.filter((tpl) => tpl.category === categoryId);
}

/**
 * Studio leadership — surfaced on /teams. The four delivery pods (Orbit,
 * Axis, Nova, Vector) handle the work day-to-day; this list names the
 * accountable leadership behind them so prospects know who is actually
 * answering for outcomes.
 */
export const studioLeadership: StudioLeader[] = [
  {
    id: "lead-founder",
    name: "Henry Chukwuemeka",
    role: "Founder & Studio Lead",
    bio: "Founder of Henry & Co. Sets the studio's standard for clarity, calm delivery, and the discipline behind every milestone.",
    focus: ["Studio direction", "Senior strategy", "Final scope sign-off"],
  },
  {
    id: "lead-design",
    name: "Design & UX Direction",
    role: "Lead, Design Pod",
    bio: "Owns the visual standard across executive websites, commerce, and product UX. Keeps interface language consistent from brief to launch.",
    focus: ["Brand systems", "Interface language", "Design QA"],
  },
  {
    id: "lead-engineering",
    name: "Engineering Direction",
    role: "Lead, Engineering Pod",
    bio: "Owns architecture, performance, and security across studio builds — from a six-page company site to a multi-role operations platform.",
    focus: ["Architecture", "Performance", "Security review"],
  },
  {
    id: "lead-delivery",
    name: "Delivery & Client Success",
    role: "Lead, Project Delivery",
    bio: "Owns the milestone calendar, weekly client updates, scope discipline, and the part where launches actually happen on time.",
    focus: ["Milestone delivery", "Client updates", "Scope governance"],
  },
];
