-- =============================================================================
-- MARKETPLACE CATEGORY EXPANSION
-- =============================================================================
-- Broadens the vendor category taxonomy from the four launch lanes to a full
-- everyday-commerce set (fashion, beauty, groceries, automotive, and the rest),
-- so a seller of almost anything finds a home. The first four featured lanes are
-- untouched; this only ADDS the new categories.
--
-- Idempotent + non-destructive: `on conflict (slug) do nothing`, so re-running is
-- a no-op and any category an operator has already curated is never overwritten.
-- Mirrors apps/marketplace/lib/marketplace/seed-catalog.ts (the seed source of
-- truth) — keep the two in step when the taxonomy changes.
-- =============================================================================

insert into public.marketplace_categories
  (slug, name, description, hero_copy, sort_order, is_featured, filter_presets, trust_notes)
values
  ('fashion-apparel', 'Fashion & Apparel',
   'Clothing for men, women, and children — everyday wear to occasion pieces.',
   'Dress the day your way — apparel with honest sizing and clear materials.',
   5, true, array['verified','fast_delivery','cod'], array['Size guides included','Material stated','Easy returns window']),
  ('shoes-footwear', 'Shoes & Footwear',
   'Sneakers, formal shoes, sandals, and boots for every day and occasion.',
   'Footwear that fits and lasts — sized honestly, described plainly.',
   6, false, array['verified','cod','fast_delivery'], array['True-to-size notes','Authenticity checked','COD eligible']),
  ('bags-accessories', 'Bags & Accessories',
   'Bags, belts, wallets, and the finishing pieces that pull an outfit together.',
   'Carry it well — bags and accessories with honest materials and clear specs.',
   7, false, array['verified','fast_delivery'], array['Material stated','Quality-checked','Gift-ready']),
  ('jewelry-watches', 'Jewelry & Watches',
   'Watches, rings, chains, and everyday jewelry — stated materials, no guesswork.',
   'Pieces worth keeping — with materials stated and authenticity checked.',
   8, false, array['verified','company_owned'], array['Material stated','Authenticity checked','Gift-ready packaging']),
  ('beauty-personal-care', 'Beauty & Personal Care',
   'Skincare, haircare, fragrance, and grooming from trusted sellers.',
   'Look after yourself — beauty and care products with honest ingredients.',
   9, true, array['verified','cod','fast_delivery'], array['Ingredients listed','Authenticity checked','Sealed on dispatch']),
  ('health-wellness', 'Health & Wellness',
   'Supplements, fitness aids, and personal-health essentials.',
   'Everyday wellbeing — health products with clear labels and honest claims.',
   10, false, array['verified','cod'], array['Labels stated','No overstated claims','Sealed on dispatch']),
  ('phones-tablets', 'Phones & Tablets',
   'Smartphones, tablets, and the cases, chargers, and cover around them.',
   'Stay connected — phones and tablets, authenticity checked before dispatch.',
   11, true, array['verified','fast_delivery','company_owned'], array['Authenticity checked','Warranty stated','Fast dispatch']),
  ('computers-laptops', 'Computers & Laptops',
   'Laptops, desktops, monitors, and the components that keep them running.',
   'Kit that keeps up — computing gear with honest specs and warranty.',
   12, false, array['verified','company_owned'], array['Specs verified','Warranty included','Tested before dispatch']),
  ('audio-headphones', 'Audio & Headphones',
   'Headphones, earbuds, speakers, and sound gear for home and on the move.',
   'Sound you can trust — audio gear, authenticity checked and ready to ship.',
   13, false, array['verified','fast_delivery','cod'], array['Authenticity checked','Warranty stated','Fast dispatch']),
  ('gaming', 'Gaming',
   'Consoles, games, controllers, and the accessories for serious play.',
   'Game on — consoles and accessories, verified and dispatch-ready.',
   14, false, array['verified','fast_delivery'], array['Authenticity checked','Warranty stated','Fast dispatch']),
  ('home-appliances', 'Home Appliances',
   'Fridges, cookers, fans, and the appliances a household runs on.',
   'The appliances that carry the home — capacity-tested with warranty.',
   15, false, array['verified','company_owned'], array['Capacity-tested','Warranty included','Install guidance']),
  ('furniture', 'Furniture',
   'Sofas, beds, tables, and storage — built to hold up at home and work.',
   'Furniture that lasts — honest materials, clear dimensions, real delivery notes.',
   16, false, array['verified','company_owned'], array['Dimensions stated','Material stated','Delivery notes clear']),
  ('kitchen-dining', 'Kitchen & Dining',
   'Cookware, utensils, dinnerware, and the tools of a working kitchen.',
   'A kitchen that works — cookware and dining goods with honest specs.',
   17, false, array['verified','cod','fast_delivery'], array['Material stated','Company stocked','Gift-ready']),
  ('groceries-gourmet', 'Groceries & Gourmet',
   'Pantry staples, packaged foods, and gourmet finds from trusted sellers.',
   'Stock the pantry — groceries and gourmet goods with clear dates and labels.',
   18, false, array['verified','cod','fast_delivery'], array['Dates stated','Sealed on dispatch','COD eligible']),
  ('baby-kids', 'Baby & Kids',
   'Baby care, kids'' clothing, and the essentials families reach for daily.',
   'For the little ones — baby and kids'' goods with honest, safe specs.',
   19, false, array['verified','cod','fast_delivery'], array['Age ranges stated','Material stated','Sealed on dispatch']),
  ('toys-games', 'Toys & Games',
   'Toys, board games, and play gear for every age.',
   'Play that lasts — toys and games with age guidance and honest specs.',
   20, false, array['verified','cod','fast_delivery'], array['Age ranges stated','Quality-checked','Gift-ready']),
  ('sports-fitness', 'Sports & Fitness',
   'Gym gear, sportswear, and equipment for training and the outdoors.',
   'Train hard — sports and fitness gear built to take the work.',
   21, false, array['verified','fast_delivery','cod'], array['Material stated','Quality-checked','Fast dispatch']),
  ('automotive-tools', 'Automotive & Tools',
   'Car care, parts, power tools, and hardware for the garage and site.',
   'Keep it running — automotive parts and tools with honest specs.',
   22, false, array['verified','company_owned'], array['Fitment noted','Warranty stated','Tested before dispatch']),
  ('books-stationery', 'Books & Stationery',
   'Books, notebooks, and the desk supplies that keep work and study moving.',
   'Read and write — books and stationery, curated and dispatch-ready.',
   23, false, array['verified','cod','fast_delivery'], array['Condition stated','Company stocked','Fast dispatch']),
  ('arts-crafts', 'Arts & Crafts',
   'Art supplies, craft materials, and handmade goods from makers.',
   'Make something — art and craft supplies with honest materials.',
   24, false, array['verified','cod'], array['Material stated','Maker-sourced','Gift-ready']),
  ('garden-outdoor', 'Garden & Outdoor',
   'Garden tools, plants, and outdoor gear for the yard and beyond.',
   'Grow and gather — garden and outdoor goods with honest specs.',
   25, false, array['verified','company_owned'], array['Material stated','Quality-checked','Delivery notes clear']),
  ('pet-supplies', 'Pet Supplies',
   'Food, toys, and care for the animals in the household.',
   'For the pets — food and supplies with clear labels and honest dates.',
   26, false, array['verified','cod','fast_delivery'], array['Dates stated','Sealed on dispatch','COD eligible']),
  ('musical-instruments', 'Musical Instruments',
   'Instruments, audio kit, and the gear that makes and records sound.',
   'Make music — instruments and studio gear, verified and dispatch-ready.',
   27, false, array['verified','company_owned'], array['Condition stated','Tested before dispatch','Warranty stated'])
on conflict (slug) do nothing;
