import type {
  MarketplaceAddress,
  MarketplaceCampaign,
  MarketplaceCategory,
  MarketplaceCollection,
  MarketplaceDispute,
  MarketplaceHomeData,
  MarketplaceNotification,
  MarketplaceOrder,
  MarketplacePayoutRequest,
  MarketplacePaymentRecord,
  MarketplaceProduct,
  MarketplaceReview,
  MarketplaceVendor,
  MarketplaceVendorApplication,
} from "@/lib/marketplace/types";

const now = new Date("2026-04-02T12:00:00.000Z");

export const demoCategories: MarketplaceCategory[] = [
  {
    id: "cat-premium-home",
    slug: "premium-home",
    name: "Premium Home",
    description: "Quiet luxury home upgrades, heirloom accents, and elegant daily-living pieces.",
    hero: "Premium home goods curated with cleaner trust and clearer delivery promises.",
    featured: true,
    productCount: 18,
    filterPresets: ["Fast delivery", "HenryCo verified", "Company stocked"],
    trustNotes: ["48-hour dispatch promise", "Style-audited listings", "Protected returns"],
  },
  {
    id: "cat-office-tech",
    slug: "office-tech",
    name: "Office & Tech",
    description: "Serious tools for sharper teams, creators, and founders.",
    hero: "Operational gear, workstations, premium accessories, and productivity hardware.",
    featured: true,
    productCount: 24,
    filterPresets: ["Business-ready", "Warranty included", "Bulk offers"],
    trustNotes: ["Verified specs", "Serial-traceable inventory", "Support-ready sellers"],
  },
  {
    id: "cat-style",
    slug: "elevated-style",
    name: "Elevated Style",
    description: "Better materials, more deliberate cuts, and clearer vendor trust.",
    hero: "Fashion with marketplace-level ease and boutique-level curation.",
    featured: true,
    productCount: 15,
    filterPresets: ["Verified sizing", "Fast exchange", "Top-rated sellers"],
    trustNotes: ["Verified size notes", "Response SLA badges", "Photo consistency checks"],
  },
];

export const demoBrands = [
  {
    id: "brand-atelier",
    slug: "atelier-oro",
    name: "Atelier Oro",
    description: "Italian-inspired home accents with warm material palettes.",
    accent: "#B2863B",
    logoUrl: null,
  },
  {
    id: "brand-lattice",
    slug: "lattice-labs",
    name: "Lattice Labs",
    description: "Workstation accessories for founders and operators.",
    accent: "#4D5F34",
    logoUrl: null,
  },
  {
    id: "brand-ivory",
    slug: "ivory-thread",
    name: "Ivory Thread",
    description: "Refined wardrobe staples built for repeat wear.",
    accent: "#6D2F28",
    logoUrl: null,
  },
];

export const demoVendors: MarketplaceVendor[] = [
  {
    id: "vendor-henryco",
    slug: "henryco-verified",
    name: "HenryCo Verified",
    description:
      "Company-owned inventory with tighter QA, cleaner delivery commitments, and concierge support coverage.",
    status: "approved",
    verificationLevel: "henryco",
    trustScore: 96,
    responseSlaHours: 2,
    fulfillmentRate: 98,
    disputeRate: 1.2,
    reviewScore: 4.9,
    followersCount: 1820,
    accent: "#B2863B",
    heroImage:
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
    badges: ["HenryCo verified", "Fast dispatch", "Concierge support"],
    ownerType: "company",
    supportEmail: "marketplace@henrycogroup.com",
    supportPhone: "+2349133957084",
  },
  {
    id: "vendor-luminous",
    slug: "luminous-atelier",
    name: "Luminous Atelier",
    description:
      "A premium vendor focused on lighting, decor, and clean-lined workspace styling with strong response discipline.",
    status: "approved",
    verificationLevel: "gold",
    trustScore: 89,
    responseSlaHours: 4,
    fulfillmentRate: 95,
    disputeRate: 1.9,
    reviewScore: 4.7,
    followersCount: 624,
    accent: "#4D5F34",
    heroImage:
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
    badges: ["Gold verified", "Low dispute rate", "Editorial pick"],
    ownerType: "vendor",
    supportEmail: "hello@luminousatelier.com",
    supportPhone: "+2349133000000",
  },
];

export const demoProducts: MarketplaceProduct[] = [
  {
    id: "prod-desk-lamp",
    slug: "oro-brass-desk-lamp",
    title: "Oro Brass Desk Lamp",
    summary: "A warm brass task lamp with glare-controlled lighting and a study-grade silhouette.",
    description:
      "Designed for premium workspaces, the Oro desk lamp pairs a weighted brass stem with a softly diffused cone shade and a low-profile switch.",
    categorySlug: "office-tech",
    brandSlug: "atelier-oro",
    vendorSlug: "henryco-verified",
    inventoryOwnerType: "company",
    basePrice: 185000,
    compareAtPrice: 220000,
    currency: "NGN",
    stock: 13,
    sku: "HCO-ORO-LAMP",
    rating: 4.9,
    reviewCount: 28,
    featured: true,
    approvalStatus: "approved",
    trustBadges: ["HenryCo verified", "Serial-checked", "Fast dispatch"],
    gallery: [
      "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: {
      Finish: "Brushed brass",
      Voltage: "220V",
      Warranty: "12 months",
      Height: "48 cm",
    },
    filterData: {
      delivery: "48 hours",
      verifiedSeller: true,
      companyOwned: true,
      codEligible: true,
    },
    deliveryNote: "Dispatches within 48 hours from Lagos.",
    leadTime: "2 to 3 business days",
    codEligible: true,
  },
  {
    id: "prod-chair",
    slug: "lattice-ergonomic-chair",
    title: "Lattice Ergonomic Chair",
    summary: "Structured lumbar support, quieter wheels, and a cleaner executive profile.",
    description:
      "A refined task chair built for long workdays without the visual bulk of generic office seating.",
    categorySlug: "office-tech",
    brandSlug: "lattice-labs",
    vendorSlug: "luminous-atelier",
    inventoryOwnerType: "vendor",
    basePrice: 320000,
    compareAtPrice: 360000,
    currency: "NGN",
    stock: 7,
    sku: "LAT-ERG-CHAIR",
    rating: 4.8,
    reviewCount: 19,
    featured: true,
    approvalStatus: "approved",
    trustBadges: ["Gold verified vendor", "Installation support"],
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1519947486511-46149fa0a254?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: {
      Material: "Performance mesh + aluminum base",
      Support: "4D armrests",
      Warranty: "18 months",
      Weight: "18 kg",
    },
    filterData: {
      delivery: "5 days",
      verifiedSeller: true,
      companyOwned: false,
      codEligible: false,
    },
    deliveryNote: "White glove delivery in major cities.",
    leadTime: "4 to 6 business days",
    codEligible: false,
  },
  {
    id: "prod-throw",
    slug: "ivory-cashmere-throw",
    title: "Ivory Cashmere Throw",
    summary: "Soft weight, neutral tone, and boutique finishing for a calmer room.",
    description: "An editorial-grade throw that softens living rooms and bedrooms without leaning cluttered or loud.",
    categorySlug: "premium-home",
    brandSlug: "ivory-thread",
    vendorSlug: "henryco-verified",
    inventoryOwnerType: "company",
    basePrice: 145000,
    compareAtPrice: 168000,
    currency: "NGN",
    stock: 16,
    sku: "IVR-CASH-THROW",
    rating: 4.7,
    reviewCount: 11,
    featured: true,
    approvalStatus: "approved",
    trustBadges: ["Company stocked", "Gift-ready packaging"],
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1200&q=80",
    ],
    specifications: {
      Material: "Cashmere blend",
      Size: "180 x 130 cm",
      Care: "Dry clean only",
      Origin: "Turkey",
    },
    filterData: {
      delivery: "48 hours",
      verifiedSeller: true,
      companyOwned: true,
      codEligible: true,
    },
    deliveryNote: "Same-day dispatch on weekdays before 2 PM.",
    leadTime: "1 to 2 business days",
    codEligible: true,
  },
];

export const demoCollections: MarketplaceCollection[] = [
  {
    id: "collection-founder-desk",
    slug: "founder-desk",
    title: "Founder Desk Edit",
    description: "Everything needed to make a small workspace feel decisive, calm, and premium.",
    kicker: "Editorial Collection",
    productSlugs: ["oro-brass-desk-lamp", "lattice-ergonomic-chair"],
    highlight: "Built around trust, quiet materials, and better long-hour ergonomics.",
  },
  {
    id: "collection-soft-living",
    slug: "soft-living",
    title: "Soft Living Reset",
    description: "Low-clutter home pieces that raise the mood without pushing noise into the room.",
    kicker: "Curated Living",
    productSlugs: ["ivory-cashmere-throw"],
    highlight: "A warmer palette, simpler surfaces, and premium packaging for gifting season.",
  },
];

export const demoCampaigns: MarketplaceCampaign[] = [
  {
    id: "campaign-launch",
    slug: "opening-reserve",
    title: "Opening Reserve",
    description: "A launch-season collection of verified inventory with cleaner delivery promises and premium buyer support.",
    surface: "hero",
    accent: "#B2863B",
    ctaLabel: "Shop the reserve",
    ctaHref: "/deals",
    countdown: "72 hours left",
  },
  {
    id: "campaign-deals",
    slug: "verified-deals",
    title: "Verified Deals Only",
    description: "Marketplace offers filtered for trust, stock certainty, and dispatch discipline.",
    surface: "deals",
    accent: "#4D5F34",
    ctaLabel: "See verified deals",
    ctaHref: "/search?verified=1",
    countdown: null,
  },
];

export const demoReviews: MarketplaceReview[] = [
  {
    id: "review-1",
    productSlug: "oro-brass-desk-lamp",
    vendorSlug: "henryco-verified",
    buyerName: "Ada M.",
    rating: 5,
    title: "Looks far better in person",
    body: "The packaging, finish quality, and delivery updates all felt premium. This is the cleanest marketplace purchase I have made locally.",
    verifiedPurchase: true,
    status: "published",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 48).toISOString(),
  },
];

export const demoBuyerAddresses: MarketplaceAddress[] = [
  {
    id: "addr-1",
    label: "Home",
    recipient: "Henry Buyer",
    phone: "+2349133957084",
    line1: "14 Admiralty Way",
    line2: "Lekki Phase 1",
    city: "Lagos",
    region: "Lagos",
    country: "Nigeria",
    isDefault: true,
  },
];

export const demoBuyerOrders: MarketplaceOrder[] = [
  {
    id: "order-1",
    orderNo: "MKT-ORD-240402-001",
    status: "shipped",
    paymentStatus: "verified",
    currency: "NGN",
    subtotal: 465000,
    shippingTotal: 18000,
    discountTotal: 20000,
    grandTotal: 463000,
    placedAt: new Date(now.getTime() - 1000 * 60 * 60 * 28).toISOString(),
    buyerName: "Henry Buyer",
    buyerEmail: "buyer@henrycogroup.com",
    shippingCity: "Lagos",
    shippingRegion: "Lagos",
    timeline: [
      "Order placed",
      "Payment verified by finance",
      "Split fulfillment prepared",
      "One vendor shipment is in transit",
    ],
    groups: [
      {
        id: "group-1",
        vendorSlug: "henryco-verified",
        ownerType: "company",
        fulfillmentStatus: "shipped",
        paymentStatus: "verified",
        payoutStatus: "paid",
        subtotal: 145000,
        commissionAmount: 0,
        netVendorAmount: 145000,
        shipmentCode: "MKT-SHP-101",
        shipmentCarrier: "GIGL",
        shipmentTrackingCode: "GIGL-001",
        deliveredAt: null,
      },
      {
        id: "group-2",
        vendorSlug: "luminous-atelier",
        ownerType: "vendor",
        fulfillmentStatus: "packed",
        paymentStatus: "verified",
        payoutStatus: "eligible",
        subtotal: 320000,
        commissionAmount: 48000,
        netVendorAmount: 272000,
        shipmentCode: "MKT-SHP-102",
        shipmentCarrier: "Kwik",
        shipmentTrackingCode: "KWIK-882",
        deliveredAt: null,
      },
    ],
    items: [
      {
        id: "item-1",
        productSlug: "ivory-cashmere-throw",
        quantity: 1,
        unitPrice: 145000,
        lineTotal: 145000,
        vendorSlug: "henryco-verified",
      },
      {
        id: "item-2",
        productSlug: "lattice-ergonomic-chair",
        quantity: 1,
        unitPrice: 320000,
        lineTotal: 320000,
        vendorSlug: "luminous-atelier",
      },
    ],
    paymentRecord: {
      id: "payment-1",
      orderNo: "MKT-ORD-240402-001",
      method: "bank_transfer",
      provider: "manual",
      status: "verified",
      amount: 463000,
      reference: "TRF-20260402-991",
      bankReference: "BANK-991",
      proofUrl: null,
      proofName: null,
      proofPublicId: null,
      proofUploadedAt: null,
      walletTransactionId: null,
      submittedAt: new Date(now.getTime() - 1000 * 60 * 60 * 22).toISOString(),
      verifiedAt: new Date(now.getTime() - 1000 * 60 * 60 * 20).toISOString(),
    },
  },
];

export const demoBuyerPayments: MarketplacePaymentRecord[] = [
  {
    id: "payment-1",
    orderNo: "MKT-ORD-240402-001",
    method: "bank_transfer",
    provider: "manual",
    status: "verified",
    amount: 463000,
    reference: "TRF-20260402-991",
    bankReference: "BANK-991",
    proofUrl: null,
    proofName: null,
    proofPublicId: null,
    proofUploadedAt: null,
    walletTransactionId: null,
    submittedAt: new Date(now.getTime() - 1000 * 60 * 60 * 22).toISOString(),
    verifiedAt: new Date(now.getTime() - 1000 * 60 * 60 * 20).toISOString(),
  },
];

export const demoBuyerNotifications: MarketplaceNotification[] = [
  {
    id: "notification-1",
    title: "Payment verified",
    body: "Finance confirmed your transfer for MKT-ORD-240402-001. Fulfillment teams have been notified.",
    channel: "in_app",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 20).toISOString(),
    readAt: null,
  },
  {
    id: "notification-2",
    title: "Vendor shipment in transit",
    body: "The Luminous Atelier segment of your order is packed and has moved to the carrier handoff stage.",
    channel: "email",
    createdAt: new Date(now.getTime() - 1000 * 60 * 60 * 6).toISOString(),
    readAt: null,
  },
];

export const demoBuyerDisputes: MarketplaceDispute[] = [
  {
    id: "dispute-1",
    disputeNo: "MKT-DSP-240330-001",
    orderNo: "MKT-ORD-240402-001",
    vendorSlug: "luminous-atelier",
    status: "investigating",
    reason: "Delivery delay beyond quoted window",
    resolutionType: null,
    refundAmount: null,
    updatedAt: new Date(now.getTime() - 1000 * 60 * 60 * 3).toISOString(),
  },
];

export const demoVendorApplication: MarketplaceVendorApplication = {
  id: "vendor-app-1",
  storeName: "Luminous Atelier",
  slug: "luminous-atelier",
  legalName: "Luminous Atelier Limited",
  phone: "+2349133000000",
  categoryFocus: "Premium workspace and home pieces",
  story:
    "We source quieter workspace and home products with cleaner photography, calmer materials, and dependable delivery handling.",
  status: "approved",
  progressStep: "review",
  submittedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 9).toISOString(),
  reviewNote: "Approved after KYC verification and response-SLA confirmation.",
  documents: {
    businessRegistration: {
      kind: "businessRegistration",
      name: "business-registration.pdf",
      fileUrl: "https://files.henrycogroup.com/marketplace/demo/business-registration.pdf",
      mimeType: "application/pdf",
      size: 384000,
      publicId: "demo-business-registration",
      uploadedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 11).toISOString(),
      status: "approved",
    },
    founderIdentity: {
      kind: "founderIdentity",
      name: "founder-id.pdf",
      fileUrl: "https://files.henrycogroup.com/marketplace/demo/founder-id.pdf",
      mimeType: "application/pdf",
      size: 276000,
      publicId: "demo-founder-identity",
      uploadedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10).toISOString(),
      status: "approved",
    },
    payoutProof: {
      kind: "payoutProof",
      name: "payout-proof.pdf",
      fileUrl: "https://files.henrycogroup.com/marketplace/demo/payout-proof.pdf",
      mimeType: "application/pdf",
      size: 198000,
      publicId: "demo-payout-proof",
      uploadedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 10).toISOString(),
      status: "approved",
    },
  },
  draftPayload: {
    storeName: "Luminous Atelier",
    legalName: "Luminous Atelier Limited",
    categoryFocus: "Premium workspace and home pieces",
    story:
      "We source quieter workspace and home products with cleaner photography, calmer materials, and dependable delivery handling.",
  },
  agreementAcceptedAt: new Date(now.getTime() - 1000 * 60 * 60 * 24 * 9).toISOString(),
};

export const demoPayoutRequests: MarketplacePayoutRequest[] = [
  {
    id: "payout-1",
    reference: "MKT-PAY-240401-001",
    vendorSlug: "luminous-atelier",
    amount: 272000,
    status: "requested",
    requestedAt: new Date(now.getTime() - 1000 * 60 * 60 * 10).toISOString(),
    reviewedAt: null,
  },
];

export const demoHomeData: MarketplaceHomeData = {
  kpis: [
    {
      label: "Verified sellers",
      value: "94%",
      hint: "Only reviewed vendors or company-owned inventory can go live.",
    },
    {
      label: "Average response SLA",
      value: "3.4h",
      hint: "Trust passport surfaces real seller responsiveness.",
    },
    {
      label: "Split-order clarity",
      value: "100%",
      hint: "Every order group shows payment, shipment, and dispute state separately.",
    },
  ],
  categories: demoCategories,
  brands: demoBrands,
  vendors: demoVendors,
  products: demoProducts,
  collections: demoCollections,
  campaigns: demoCampaigns,
  reviews: demoReviews,
};
