import type {
  PropertyArea,
  PropertyAgent,
  PropertyDifferentiator,
  PropertyFaq,
  PropertyFeaturedCampaign,
  PropertyListing,
  PropertyManagedRecord,
  PropertyMetric,
  PropertyService,
  PropertySnapshot,
} from "./types";

const now = "2026-04-02T12:00:00.000Z";

export const propertyMetrics: PropertyMetric[] = [
  {
    label: "Response SLA",
    value: "< 12h",
    hint: "Premium inquiries route to HenryCo ops, not a passive inbox.",
  },
  {
    label: "Managed Portfolio",
    value: "18 homes",
    hint: "Managed stock is surfaced with stronger compliance and trust notes.",
  },
  {
    label: "Qualified Viewings",
    value: "87%",
    hint: "Scheduling flows are structured to reduce no-shows and thin leads.",
  },
];

export const propertyAreas: PropertyArea[] = [
  {
    id: "area-ikoyi",
    slug: "ikoyi-lagos",
    name: "Ikoyi",
    city: "Lagos",
    marketNote: "Prime rentals, diplomatic-grade compounds, and executive-managed homes.",
    hero: "Editorial-quality homes for executives, founders, and expatriate households.",
    averageRent: 18000000,
    averageSale: 650000000,
    hotspots: ["Banana Island fringe", "Parkview enclave", "Bourdillon corridor"],
    trustNotes: ["Verified title lane", "Viewing escort available", "Managed-property readiness"],
  },
  {
    id: "area-victoria-island",
    slug: "victoria-island-lagos",
    name: "Victoria Island",
    city: "Lagos",
    marketNote: "Corporate leases, serviced residences, and commercial visibility.",
    hero: "For teams and residents who want prestige with cleaner operations.",
    averageRent: 12000000,
    averageSale: 420000000,
    hotspots: ["Akin Adesola", "Kofo Abayomi", "Oniru edge"],
    trustNotes: ["Commercial screening", "Short-let readiness", "Vendor response monitoring"],
  },
  {
    id: "area-lekki-phase-1",
    slug: "lekki-phase-1-lagos",
    name: "Lekki Phase 1",
    city: "Lagos",
    marketNote: "Young-family demand, creative professional demand, and high-velocity viewings.",
    hero: "Calmer listing quality, stronger photos, and less noisy shortlist fatigue.",
    averageRent: 9000000,
    averageSale: 280000000,
    hotspots: ["Admiralty axis", "Freedom Way", "Chevron-adjacent pockets"],
    trustNotes: ["Viewing batching", "Owner verification notes", "Move-in coordination support"],
  },
];

export const propertyAgents: PropertyAgent[] = [
  {
    id: "agent-adaeze",
    slug: "adaeze-okonkwo",
    name: "Adaeze Okonkwo",
    label: "Relationship Manager, Prime Homes",
    phone: "+2349133957084",
    whatsapp: "+2349133957084",
    email: "property@henrycogroup.com",
    photoUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
    territories: ["ikoyi-lagos", "victoria-island-lagos"],
    badges: ["Trust escort", "Executive rentals"],
    bio: "Pairs premium listings with disciplined follow-up, cleaner owner comms, and higher-conviction viewing preparation.",
  },
  {
    id: "agent-tunde",
    slug: "tunde-adebayo",
    name: "Tunde Adebayo",
    label: "Listings Manager, Residential Sales",
    phone: "+2349133957084",
    whatsapp: null,
    email: "property@henrycogroup.com",
    photoUrl:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    territories: ["lekki-phase-1-lagos", "victoria-island-lagos"],
    badges: ["Seller coaching", "Moderation lead"],
    bio: "Optimizes listing quality, owner verification, and featured campaign fit before public release.",
  },
  {
    id: "agent-zainab",
    slug: "zainab-sani",
    name: "Zainab Sani",
    label: "Managed Property Operations",
    phone: "+2349133957084",
    whatsapp: "+2349133957084",
    email: "property@henrycogroup.com",
    photoUrl:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
    territories: ["ikoyi-lagos", "lekki-phase-1-lagos"],
    badges: ["Rent collection", "Trust operations"],
    bio: "Runs the post-listing operating layer: inspections, owner reporting, and managed-property standards.",
  },
];

export const propertyListings: PropertyListing[] = [
  {
    id: "listing-ikoyi-penthouse",
    slug: "harbour-crest-penthouse-ikoyi",
    title: "Harbour Crest Penthouse",
    summary: "A five-bed duplex penthouse with private terrace, marina-facing lounge, and concierge-led arrival sequence.",
    description:
      "Designed for executives who want space, privacy, and cleaner operations. HenryCo Property manages the viewing rail, owner communication, and final handover support for this listing.",
    kind: "rent",
    serviceType: "rent",
    intent: "managed_property",
    status: "published",
    visibility: "public",
    locationSlug: "ikoyi-lagos",
    locationLabel: "Ikoyi, Lagos",
    district: "Bourdillon",
    addressLine: "Bourdillon Crescent",
    price: 32000000,
    currency: "NGN",
    priceInterval: "per year",
    bedrooms: 5,
    bathrooms: 6,
    sizeSqm: 540,
    parkingSpaces: 4,
    furnished: true,
    petFriendly: false,
    shortletReady: false,
    managedByHenryCo: true,
    featured: true,
    promoted: true,
    heroImage:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1600&q=80"
    ],
    floorPlanUrl: null,
    amenities: ["Private terrace", "Lift access", "Staff quarters", "Smart security", "Generator"],
    trustBadges: ["Managed by HenryCo", "Owner verified", "Premium viewing protocol"],
    headlineMetrics: ["5 beds", "540 sqm", "Concierge arrival"],
    verificationNotes: ["Title documents reviewed", "Service-charge clarity provided"],
    riskScore: 38,
    riskFlags: ["managed_stock", "editorial_ready"],
    policyVersion: "demo",
    policySummary: "Demo listing seeded as published inventory.",
    availableFrom: "2026-04-20T00:00:00.000Z",
    availableNow: false,
    ownerUserId: null,
    normalizedEmail: "owner@harbourcrest.com",
    ownerName: "Harbour Crest Holdings",
    ownerPhone: "+2349133957084",
    ownerEmail: "owner@harbourcrest.com",
    agentId: "agent-adaeze",
    listedAt: now,
    updatedAt: now,
  },
  {
    id: "listing-vi-residence",
    slug: "eden-quay-serviced-residence-vi",
    title: "Eden Quay Serviced Residence",
    summary: "A serviced three-bed residence set up for corporate leases, relocation stays, and clean weekly operations.",
    description:
      "Built for founders, relocation teams, and operators who need a polished residence without management noise. HenryCo screens inquiries, runs viewing scheduling, and supports occupancy readiness.",
    kind: "shortlet",
    serviceType: "shortlet",
    intent: "managed_property",
    status: "published",
    visibility: "public",
    locationSlug: "victoria-island-lagos",
    locationLabel: "Victoria Island, Lagos",
    district: "Akin Adesola",
    addressLine: "Akin Adesola Street",
    price: 650000,
    currency: "NGN",
    priceInterval: "per night",
    bedrooms: 3,
    bathrooms: 4,
    sizeSqm: 260,
    parkingSpaces: 2,
    furnished: true,
    petFriendly: false,
    shortletReady: true,
    managedByHenryCo: true,
    featured: true,
    promoted: false,
    heroImage:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=80"
    ],
    floorPlanUrl: null,
    amenities: ["Daily housekeeping", "Fiber internet", "Generator", "Gym access", "Airport assist"],
    trustBadges: ["Managed by HenryCo", "Short-let ready", "Response under 30 mins"],
    headlineMetrics: ["3 beds", "Serviced", "Corporate-ready"],
    verificationNotes: ["Inventory checklist structured", "Guest operations SOP available"],
    riskScore: 54,
    riskFlags: ["shortlet_ops", "managed_stock"],
    policyVersion: "demo",
    policySummary: "Demo listing seeded as published inventory.",
    availableFrom: now,
    availableNow: true,
    ownerUserId: null,
    normalizedEmail: "ops@edenquay.com",
    ownerName: "Eden Quay Suites",
    ownerPhone: "+2349133957084",
    ownerEmail: "ops@edenquay.com",
    agentId: "agent-adaeze",
    listedAt: now,
    updatedAt: now,
  },
  {
    id: "listing-lekki-townhouse",
    slug: "cove-garden-townhouse-lekki",
    title: "Cove Garden Townhouse",
    summary: "A four-bed family townhouse with rooftop lounge, quiet street access, and strong move-in readiness.",
    description:
      "This listing is set up for families who want less stress in the decision process. HenryCo Property keeps the shortlist, follow-up, and viewing coordination structured from first inquiry to keys.",
    kind: "rent",
    serviceType: "rent",
    intent: "owner_listed",
    status: "published",
    visibility: "public",
    locationSlug: "lekki-phase-1-lagos",
    locationLabel: "Lekki Phase 1, Lagos",
    district: "Admiralty",
    addressLine: "Admiralty Way",
    price: 14500000,
    currency: "NGN",
    priceInterval: "per year",
    bedrooms: 4,
    bathrooms: 5,
    sizeSqm: 390,
    parkingSpaces: 3,
    furnished: false,
    petFriendly: true,
    shortletReady: false,
    managedByHenryCo: false,
    featured: true,
    promoted: false,
    heroImage:
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=80"
    ],
    floorPlanUrl: null,
    amenities: ["Rooftop lounge", "Family room", "BQ", "Fitted kitchen", "Water treatment"],
    trustBadges: ["Owner verified", "Move-in prep available"],
    headlineMetrics: ["4 beds", "390 sqm", "Family-ready"],
    verificationNotes: ["Owner contact matched", "Service-charge notes available on request"],
    riskScore: 46,
    riskFlags: ["family_stock"],
    policyVersion: "demo",
    policySummary: "Demo listing seeded as published inventory.",
    availableFrom: "2026-04-10T00:00:00.000Z",
    availableNow: true,
    ownerUserId: null,
    normalizedEmail: "owner@covegarden.ng",
    ownerName: "Cove Garden Homes",
    ownerPhone: "+2349133957084",
    ownerEmail: "owner@covegarden.ng",
    agentId: "agent-tunde",
    listedAt: now,
    updatedAt: now,
  },
  {
    id: "listing-vi-office",
    slug: "ledger-house-commercial-suite-vi",
    title: "Ledger House Commercial Suite",
    summary: "A premium floor plate for advisory firms, founder offices, and polished client-facing teams.",
    description:
      "HenryCo Property moderates commercial listing quality more tightly than generic boards, so floor plans, service-charge context, and fit-out notes are not buried under weak copy.",
    kind: "commercial",
    serviceType: "commercial",
    intent: "agent_listed",
    status: "published",
    visibility: "public",
    locationSlug: "victoria-island-lagos",
    locationLabel: "Victoria Island, Lagos",
    district: "Kofo Abayomi",
    addressLine: "Kofo Abayomi Street",
    price: 210000000,
    currency: "NGN",
    priceInterval: "per year",
    bedrooms: null,
    bathrooms: 4,
    sizeSqm: 720,
    parkingSpaces: 10,
    furnished: false,
    petFriendly: false,
    shortletReady: false,
    managedByHenryCo: false,
    featured: false,
    promoted: true,
    heroImage:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=1600&q=80"
    ],
    floorPlanUrl: null,
    amenities: ["Meeting rooms", "Reception zone", "Backup power", "Parking", "Access control"],
    trustBadges: ["Commercial screening", "Fit-out note provided"],
    headlineMetrics: ["720 sqm", "VI frontage", "Corporate-grade"],
    verificationNotes: ["Landlord counsel verified", "Fit-out handover schedule defined"],
    riskScore: 62,
    riskFlags: ["commercial", "high_value"],
    policyVersion: "demo",
    policySummary: "Demo listing seeded as published inventory.",
    availableFrom: "2026-05-01T00:00:00.000Z",
    availableNow: false,
    ownerUserId: null,
    normalizedEmail: "leasing@ledgerhouse.ng",
    ownerName: "Ledger House",
    ownerPhone: "+2349133957084",
    ownerEmail: "leasing@ledgerhouse.ng",
    agentId: "agent-tunde",
    listedAt: now,
    updatedAt: now,
  },
];

export const propertyManagedRecords: PropertyManagedRecord[] = [
  {
    id: "managed-harbour",
    title: "Harbour Crest Portfolio",
    serviceType: "Managed residential collection",
    status: "active",
    ownerName: "Harbour Crest Holdings",
    locationLabel: "Ikoyi, Lagos",
    portfolioValue: 1900000000,
    serviceLines: ["Occupancy oversight", "Owner reporting", "Maintenance vendor coordination"],
    narrative: "HenryCo runs inspections, tenant comms, and owner reporting with a cleaner operating cadence.",
    assignedManagerId: "agent-zainab",
    updatedAt: now,
  },
  {
    id: "managed-eden",
    title: "Eden Quay Guest Residences",
    serviceType: "Managed short-let operations",
    status: "active",
    ownerName: "Eden Quay Suites",
    locationLabel: "Victoria Island, Lagos",
    portfolioValue: 980000000,
    serviceLines: ["Guest ops", "Inventory assurance", "Revenue oversight"],
    narrative: "Built for owners who want hospitality polish without fragmented operator handoffs.",
    assignedManagerId: "agent-zainab",
    updatedAt: now,
  },
];

export const propertyCampaigns: PropertyFeaturedCampaign[] = [
  {
    id: "campaign-managed",
    slug: "managed-homes-signature",
    surface: "hero",
    title: "Managed homes with calmer follow-through",
    description: "Listings with tighter readiness checks, clearer owner rails, and better post-viewing follow-up.",
    ctaLabel: "Explore managed homes",
    ctaHref: "/managed",
    accent: "#B06C3E",
    listingIds: ["listing-ikoyi-penthouse", "listing-vi-residence"],
  },
  {
    id: "campaign-commercial",
    slug: "commercial-briefing",
    surface: "featured",
    title: "Commercial spaces with cleaner screening",
    description: "For teams that want fewer dead-end viewings and better pre-tour context.",
    ctaLabel: "View commercial listings",
    ctaHref: "/search?kind=commercial",
    accent: "#7C4D31",
    listingIds: ["listing-vi-office"],
  },
];

export const propertyServices: PropertyService[] = [
  {
    id: "service-managed",
    title: "Managed Property Trust Services",
    summary: "HenryCo can operate the property after it is listed, occupied, and handed over.",
    bullets: ["Owner reporting", "Maintenance coordination", "Rent follow-up", "Viewing and inspection standards"],
  },
  {
    id: "service-marketing",
    title: "Listing Marketing and Positioning",
    summary: "Sharper presentation, stronger photography direction, and better inquiry conversion.",
    bullets: ["Editorial listing copy", "Premium media sequencing", "Featured campaign placement", "Viewing-prep workflows"],
  },
  {
    id: "service-tenant",
    title: "Inquiry and Viewing Operations",
    summary: "HenryCo can handle response sequencing, screening, and viewing scheduling with calmer rigor.",
    bullets: ["Lead triage", "Scheduling coordination", "Reminder automation", "No-show reduction"],
  },
];

export const propertyFaqs: PropertyFaq[] = [
  {
    id: "faq-1",
    question: "What makes a HenryCo-managed property different?",
    answer: "Managed properties carry stronger readiness checks, operator follow-through, viewing coordination, and owner reporting than standard pass-through listings.",
  },
  {
    id: "faq-2",
    question: "Can I submit a property before my media is perfect?",
    answer: "Yes. HenryCo can accept a submission with baseline media, then request improved assets before public approval if the listing needs a stronger premium presentation.",
  },
  {
    id: "faq-3",
    question: "How are viewing requests confirmed?",
    answer: "Viewing requests are logged, assigned, and moved through confirmation and reminder steps server-side, with email and WhatsApp follow-up where configuration allows.",
  },
  {
    id: "faq-4",
    question: "Do you support commercial properties?",
    answer: "Yes. Commercial listings get fit-out context, screening notes, and more disciplined inquiry handling so teams avoid low-information tours.",
  },
  {
    id: "faq-5",
    question: "Can HenryCo manage a property after occupancy?",
    answer: "Yes. Managed-property services can include owner reporting, maintenance vendor coordination, rent follow-up, inspections, and occupancy support.",
  },
];

export const propertyDifferentiators: PropertyDifferentiator[] = [
  {
    id: "diff-1",
    name: "Trust passports on listings",
    description: "Each premium listing carries verification, service, and readiness notes that reduce low-information browsing.",
    pros: ["Builds confidence faster", "Improves inquiry quality"],
    cons: ["Needs disciplined ops upkeep"],
    difficulty: "high",
    innovationScore: 9,
  },
  {
    id: "diff-2",
    name: "Viewing confidence rails",
    description: "The platform treats viewings like staged operations with backup slots, reminders, and agent accountability.",
    pros: ["Reduces no-shows", "Creates stronger follow-up"],
    cons: ["Requires structured scheduling"],
    difficulty: "high",
    innovationScore: 9,
  },
  {
    id: "diff-3",
    name: "Managed-property layer",
    description: "Listings can move naturally into ongoing trust operations instead of ending at lead capture.",
    pros: ["Higher retention", "Stronger owner value"],
    cons: ["Operationally heavier"],
    difficulty: "very_high",
    innovationScore: 10,
  },
  {
    id: "diff-4",
    name: "Editorial listing moderation",
    description: "Weak copy and weak media do not go live untouched; HenryCo improves the listing surface before release.",
    pros: ["Better premium feel", "Higher conversion quality"],
    cons: ["Slower than instant posting"],
    difficulty: "high",
    innovationScore: 8,
  },
  {
    id: "diff-5",
    name: "Unified account property memory",
    description: "Saved listings, viewings, documents, and notifications are mirrored for future HenryCo account unification.",
    pros: ["Cross-division continuity", "Better CRM backbone"],
    cons: ["Needs data discipline"],
    difficulty: "high",
    innovationScore: 9,
  },
  {
    id: "diff-6",
    name: "Owner briefing rail",
    description: "Owner-facing updates can be generated from inquiry, viewing, and managed-property events without manual chaos.",
    pros: ["Raises owner trust", "Improves responsiveness"],
    cons: ["Needs alert tuning"],
    difficulty: "medium",
    innovationScore: 8,
  },
  {
    id: "diff-7",
    name: "Area intelligence pages",
    description: "Location pages explain context, not just stock, which shortens decision time for serious buyers and tenants.",
    pros: ["Premium discovery", "Better SEO and trust"],
    cons: ["Needs good market copy"],
    difficulty: "medium",
    innovationScore: 7,
  },
  {
    id: "diff-8",
    name: "Short-let readiness scoring",
    description: "Properties intended for flexible stays can surface with operational readiness signals, not just nightly pricing.",
    pros: ["Better for corporate stays", "Supports management upsell"],
    cons: ["Needs ongoing standards"],
    difficulty: "high",
    innovationScore: 8,
  },
];

export const demoPropertySnapshot: PropertySnapshot = {
  metrics: propertyMetrics,
  areas: propertyAreas,
  agents: propertyAgents,
  listings: propertyListings,
  inquiries: [],
  viewingRequests: [],
  applications: [],
  inspections: [],
  policyEvents: [],
  managedRecords: propertyManagedRecords,
  campaigns: propertyCampaigns,
  notifications: [],
  savedListings: [],
  services: propertyServices,
  faqs: propertyFaqs,
  differentiators: propertyDifferentiators,
};
