import type { StudioPackage, StudioService, StudioTeamProfile } from "@/lib/studio/types";
import type { StudioRequestConfig } from "@/lib/studio/request-config";

export type StudioRequestPathway = "package" | "custom";

export type RequestBuilderSelectionProps = {
  services: StudioService[];
  packages: StudioPackage[];
  teams: StudioTeamProfile[];
  requestConfig: StudioRequestConfig;
  serviceKind: StudioService["kind"];
  setServiceKind: (value: StudioService["kind"]) => void;
  pathway: StudioRequestPathway;
  setPathway: (value: StudioRequestPathway) => void;
  filteredPackages: StudioPackage[];
  selectedPackage: StudioPackage | null;
  setSelectedPackageId: (value: string) => void;
  selectedProjectType: string;
  setSelectedProjectType: (value: string) => void;
  selectedPlatform: string;
  setSelectedPlatform: (value: string) => void;
  selectedDesign: string;
  setSelectedDesign: (value: string) => void;
  preferredLanguage: string;
  setPreferredLanguage: (value: string) => void;
  selectedPages: string[];
  setSelectedPages: (value: string[]) => void;
  selectedModules: string[];
  setSelectedModules: (value: string[]) => void;
  selectedAddOns: string[];
  setSelectedAddOns: (value: string[]) => void;
  selectedTech: string[];
  setSelectedTech: (value: string[]) => void;
  selectedProgrammingLanguage: string;
  setSelectedProgrammingLanguage: (value: string) => void;
  selectedFramework: string;
  setSelectedFramework: (value: string) => void;
  selectedBackend: string;
  setSelectedBackend: (value: string) => void;
  selectedHosting: string;
  setSelectedHosting: (value: string) => void;
  businessType: string;
  setBusinessType: (value: string) => void;
  budgetBand: string;
  setBudgetBand: (value: string) => void;
  urgency: string;
  setUrgency: (value: string) => void;
  timeline: string;
  setTimeline: (value: string) => void;
  goals: string;
  setGoals: (value: string) => void;
  scopeNotes: string;
  setScopeNotes: (value: string) => void;
  inspirationSummary: string;
  setInspirationSummary: (value: string) => void;
  selectedTeamId: string;
  setSelectedTeamId: (value: string) => void;
};
