import * as React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";
import { getBrandedDocumentsCopy, type AppLocale } from "@henryco/i18n";

import { BrandedDocument } from "../components/BrandedDocument";
import { DocumentSection, DefinitionList } from "../components/DocumentSection";
import { DataTable, type DataTableColumn } from "../components/DataTable";
import { LegalFooter } from "../components/SignatureBlock";
import {
  formatDateTime,
  formatKobo,
  statusToLabel,
  titleCase,
} from "../format";
import { letterSpacing, palette, typeScale } from "../tokens";

/**
 * V3 PASS 21 — LogisticsB2BStatement PDF template.
 *
 * Monthly aggregated statement for a B2B account. Lists every
 * shipment booked in the period, summarises volume, on-time
 * performance, and total spend, then renders the settlement table.
 *
 * Generated by the owner workspace + emailed monthly via the
 * logistics-automation cron (V3 follow-up wave will wire the send).
 */

export type LogisticsB2BStatementRow = {
  id: string;
  trackingCode: string;
  bookedAt: string;
  deliveredAt?: string | null;
  status: string;
  serviceType: string;
  zone?: string | null;
  recipientName: string;
  amountKobo: number;
};

export type LogisticsB2BStatementProps = {
  account: {
    id: string;
    name: string;
    legalName?: string | null;
    billingTerms: string;
    billingEmail?: string | null;
  };
  period: {
    label: string;
    startsAt: string;
    endsAt: string;
  };
  totals: {
    shipments: number;
    delivered: number;
    onTimePct: number;
    grossKobo: number;
    currency: string;
  };
  rows: LogisticsB2BStatementRow[];
  locale?: AppLocale;
};

const styles = StyleSheet.create({
  banner: {
    marginTop: 16,
    backgroundColor: "#D77539",
    color: palette.ink,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bannerLabel: {
    fontSize: typeScale.hairline,
    fontFamily: "HenryCoSans",
    color: "#1A100A",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: letterSpacing.kicker * 6,
  },
  bannerValue: {
    fontSize: typeScale.subhead,
    fontFamily: "HenryCoMono",
    color: "#1A100A",
    fontWeight: 700,
  },
});

export function LogisticsB2BStatementDocument({
  account,
  period,
  totals,
  rows,
  locale = "en",
}: LogisticsB2BStatementProps) {
  const t = getBrandedDocumentsCopy(locale).logisticsB2b;
  const columns: Array<DataTableColumn<LogisticsB2BStatementRow>> = [
    {
      key: "trackingCode",
      header: t.columnTracking,
      flex: 1.2,
      mono: true,
      render: (row) => row.trackingCode,
    },
    {
      key: "recipient",
      header: t.columnRecipient,
      flex: 2,
      render: (row) => row.recipientName,
    },
    {
      key: "service",
      header: t.columnService,
      flex: 1.6,
      render: (row) =>
        `${titleCase(row.serviceType)}${row.zone ? ` · ${row.zone}` : ""}`,
    },
    {
      key: "status",
      header: t.columnStatus,
      flex: 1,
      render: (row) => statusToLabel(row.status),
    },
    {
      key: "amount",
      header: t.columnAmount,
      flex: 1.2,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.amountKobo, totals.currency),
    },
  ];

  return (
    <BrandedDocument
      locale={locale}
      metadata={{
        title: `B2B statement · ${account.name} · ${period.label}`,
        subject: t.subject,
        keywords: ["logistics", "b2b", "statement", "henryco", account.name],
      }}
      header={{
        documentType: t.documentType,
        title: account.name,
        subtitle: `${period.label} · ${t.subtitleShipments(totals.shipments)}`,
        meta: [
          { label: t.metaPeriod, value: period.label },
          { label: t.metaStarts, value: formatDateTime(period.startsAt) },
          { label: t.metaEnds, value: formatDateTime(period.endsAt) },
        ],
        divisionLabel: t.divisionLabel,
      }}
      division="logistics"
    >
      <View style={styles.banner}>
        <Text style={styles.bannerLabel}>{t.grossSpend}</Text>
        <Text style={styles.bannerValue}>
          {formatKobo(totals.grossKobo, totals.currency)}
        </Text>
      </View>

      <DocumentSection kicker={t.sectionAccount} tone="elevated">
        <DefinitionList
          rows={[
            { label: t.rowName, value: account.name },
            { label: t.rowLegalName, value: account.legalName ?? account.name },
            {
              label: t.rowBillingTerms,
              value: titleCase(account.billingTerms),
            },
            {
              label: t.rowBillingEmail,
              value: account.billingEmail ?? "—",
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker={t.sectionPeriodSummary}>
        <DefinitionList
          rows={[
            { label: t.rowShipments, value: String(totals.shipments) },
            { label: t.rowDelivered, value: String(totals.delivered) },
            {
              label: t.rowOnTime,
              value: `${totals.onTimePct}%`,
            },
            {
              label: t.rowGrossSpend,
              value: formatKobo(totals.grossKobo, totals.currency),
              mono: true,
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker={t.sectionItemised}>
        <DataTable
          columns={columns}
          rows={rows}
          striped
          emptyMessage={t.emptyShipments}
        />
      </DocumentSection>

      <LegalFooter lines={[t.legalLine1, t.legalLine2]} />
    </BrandedDocument>
  );
}
