import * as React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

import { BrandedDocument } from "../components/BrandedDocument";
import { DocumentSection, DefinitionList } from "../components/DocumentSection";
import { DataTable, type DataTableColumn } from "../components/DataTable";
import { LegalFooter } from "../components/SignatureBlock";
import {
  formatDateTime,
  formatKobo,
  statusToLabel,
  titleCase,
} from "../format";
import { letterSpacing, palette, typeScale } from "../tokens";

/**
 * V3 PASS 21 — LogisticsB2BStatement PDF template.
 *
 * Monthly aggregated statement for a B2B account. Lists every
 * shipment booked in the period, summarises volume, on-time
 * performance, and total spend, then renders the settlement table.
 *
 * Generated by the owner workspace + emailed monthly via the
 * logistics-automation cron (V3 follow-up wave will wire the send).
 */

export type LogisticsB2BStatementRow = {
  id: string;
  trackingCode: string;
  bookedAt: string;
  deliveredAt?: string | null;
  status: string;
  serviceType: string;
  zone?: string | null;
  recipientName: string;
  amountKobo: number;
};

export type LogisticsB2BStatementProps = {
  account: {
    id: string;
    name: string;
    legalName?: string | null;
    billingTerms: string;
    billingEmail?: string | null;
  };
  period: {
    label: string;
    startsAt: string;
    endsAt: string;
  };
  totals: {
    shipments: number;
    delivered: number;
    onTimePct: number;
    grossKobo: number;
    currency: string;
  };
  rows: LogisticsB2BStatementRow[];
};

const styles = StyleSheet.create({
  banner: {
    marginTop: 16,
    backgroundColor: "#D77539",
    color: palette.ink,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bannerLabel: {
    fontSize: typeScale.hairline,
    fontFamily: "HenryCoSans",
    color: "#1A100A",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: letterSpacing.kicker * 6,
  },
  bannerValue: {
    fontSize: typeScale.subhead,
    fontFamily: "HenryCoMono",
    color: "#1A100A",
    fontWeight: 700,
  },
});

export function LogisticsB2BStatementDocument({
  account,
  period,
  totals,
  rows,
}: LogisticsB2BStatementProps) {
  const columns: Array<DataTableColumn<LogisticsB2BStatementRow>> = [
    {
      key: "trackingCode",
      header: "Tracking",
      flex: 1.2,
      mono: true,
      render: (row) => row.trackingCode,
    },
    {
      key: "recipient",
      header: "Recipient",
      flex: 2,
      render: (row) => row.recipientName,
    },
    {
      key: "service",
      header: "Service",
      flex: 1.6,
      render: (row) =>
        `${titleCase(row.serviceType)}${row.zone ? ` · ${row.zone}` : ""}`,
    },
    {
      key: "status",
      header: "Status",
      flex: 1,
      render: (row) => statusToLabel(row.status),
    },
    {
      key: "amount",
      header: "Amount",
      flex: 1.2,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.amountKobo, totals.currency),
    },
  ];

  return (
    <BrandedDocument
      metadata={{
        title: `B2B statement · ${account.name} · ${period.label}`,
        subject: "HenryCo Logistics B2B statement",
        keywords: ["logistics", "b2b", "statement", "henryco", account.name],
      }}
      header={{
        documentType: "B2B statement",
        title: account.name,
        subtitle: `${period.label} · ${totals.shipments} shipments`,
        meta: [
          { label: "Period", value: period.label },
          { label: "Starts", value: formatDateTime(period.startsAt) },
          { label: "Ends", value: formatDateTime(period.endsAt) },
        ],
        divisionLabel: "Logistics · B2B",
      }}
      division="logistics"
    >
      <View style={styles.banner}>
        <Text style={styles.bannerLabel}>Gross spend</Text>
        <Text style={styles.bannerValue}>
          {formatKobo(totals.grossKobo, totals.currency)}
        </Text>
      </View>

      <DocumentSection kicker="Account" tone="elevated">
        <DefinitionList
          rows={[
            { label: "Name", value: account.name },
            { label: "Legal name", value: account.legalName ?? account.name },
            {
              label: "Billing terms",
              value: titleCase(account.billingTerms),
            },
            {
              label: "Billing email",
              value: account.billingEmail ?? "—",
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker="Period summary">
        <DefinitionList
          rows={[
            { label: "Shipments", value: String(totals.shipments) },
            { label: "Delivered", value: String(totals.delivered) },
            {
              label: "On-time",
              value: `${totals.onTimePct}%`,
            },
            {
              label: "Gross spend",
              value: formatKobo(totals.grossKobo, totals.currency),
              mono: true,
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker="Itemised shipments">
        <DataTable
          columns={columns}
          rows={rows}
          striped
          emptyMessage="No shipments in this period."
        />
      </DocumentSection>

      <LegalFooter
        lines={[
          "This statement summarises shipment activity booked through your HenryCo B2B account during the period above. Amounts are gross of any negotiated rebate, which is settled separately on the agreed cadence.",
          "Discrepancies must be raised within the dispute window stated in your service agreement; we cannot re-bill outside that window.",
        ]}
      />
    </BrandedDocument>
  );
}
