import * as React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

import { BrandedDocument } from "../components/BrandedDocument";
import { DocumentSection, DefinitionList } from "../components/DocumentSection";
import { DataTable, type DataTableColumn } from "../components/DataTable";
import { LegalFooter } from "../components/SignatureBlock";
import { formatDateTime, formatKobo, titleCase } from "../format";
import { letterSpacing, palette, typeScale } from "../tokens";

/**
 * V3 PASS 21 — VendorTaxDocument PDF template.
 *
 * Annual tax summary for a marketplace vendor — the HenryCo equivalent
 * of a 1099-K / VAT-output statement. Aggregates settled gross,
 * commissions, fees, refunds, and net payouts by month, then totals
 * the year. The vendor uses this document for their tax filing; we
 * are explicit that we do not file on their behalf.
 *
 * Generated by the vendor workspace once per fiscal year (or on
 * demand for in-year preview). The cron will emit it in January.
 */

export type VendorTaxMonthlyRow = {
  monthLabel: string;
  monthStart: string;
  ordersCount: number;
  grossKobo: number;
  commissionKobo: number;
  processingFeeKobo: number;
  refundsKobo: number;
  netPayoutKobo: number;
};

export type VendorTaxDocumentProps = {
  vendor: {
    id: string;
    name: string;
    legalName?: string | null;
    storeSlug: string;
    settlementCurrency: string;
    taxId?: string | null;
    taxRegion?: string | null;
    taxClassification?: string | null;
    payoutMethod: string;
  };
  fiscalYear: number;
  generatedAt: string;
  rows: VendorTaxMonthlyRow[];
  totals: {
    orders: number;
    grossKobo: number;
    commissionKobo: number;
    processingFeeKobo: number;
    refundsKobo: number;
    netPayoutKobo: number;
  };
};

const styles = StyleSheet.create({
  banner: {
    marginTop: 16,
    backgroundColor: "#7E5E1F",
    color: palette.paper,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bannerLabel: {
    fontSize: typeScale.hairline,
    fontFamily: "HenryCoSans",
    color: palette.paper,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: letterSpacing.kicker * 6,
  },
  bannerValue: {
    fontSize: typeScale.subhead,
    fontFamily: "HenryCoMono",
    color: palette.paper,
    fontWeight: 700,
  },
});

export function VendorTaxDocumentDocument({
  vendor,
  fiscalYear,
  generatedAt,
  rows,
  totals,
}: VendorTaxDocumentProps) {
  const currency = vendor.settlementCurrency;

  const columns: Array<DataTableColumn<VendorTaxMonthlyRow>> = [
    {
      key: "month",
      header: "Month",
      flex: 1.2,
      render: (row) => row.monthLabel,
    },
    {
      key: "orders",
      header: "Orders",
      flex: 0.7,
      align: "right",
      mono: true,
      render: (row) => String(row.ordersCount),
    },
    {
      key: "gross",
      header: "Gross",
      flex: 1.2,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.grossKobo, currency),
    },
    {
      key: "commission",
      header: "Commission",
      flex: 1.2,
      align: "right",
      mono: true,
      render: (row) =>
        row.commissionKobo > 0 ? `-${formatKobo(row.commissionKobo, currency)}` : "—",
    },
    {
      key: "fee",
      header: "Fee",
      flex: 1,
      align: "right",
      mono: true,
      render: (row) =>
        row.processingFeeKobo > 0
          ? `-${formatKobo(row.processingFeeKobo, currency)}`
          : "—",
    },
    {
      key: "refunds",
      header: "Refunds",
      flex: 1,
      align: "right",
      mono: true,
      render: (row) =>
        row.refundsKobo > 0 ? `-${formatKobo(row.refundsKobo, currency)}` : "—",
    },
    {
      key: "net",
      header: "Net payout",
      flex: 1.3,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.netPayoutKobo, currency),
    },
  ];

  return (
    <BrandedDocument
      metadata={{
        title: `Vendor tax summary · ${vendor.name} · ${fiscalYear}`,
        subject: "HenryCo Marketplace annual vendor tax summary",
        keywords: ["marketplace", "vendor", "tax", "annual", String(fiscalYear)],
      }}
      header={{
        documentType: "Annual tax summary",
        title: vendor.name,
        subtitle: `Fiscal year ${fiscalYear} · ${totals.orders} order${totals.orders === 1 ? "" : "s"}`,
        meta: [
          { label: "Fiscal year", value: String(fiscalYear) },
          { label: "Settlement", value: currency },
          {
            label: "Tax ID",
            value: vendor.taxId ?? "On file",
          },
        ],
        divisionLabel: "Marketplace · Tax summary",
      }}
      division="marketplace"
    >
      <View style={styles.banner}>
        <Text style={styles.bannerLabel}>Total gross · {fiscalYear}</Text>
        <Text style={styles.bannerValue}>
          {formatKobo(totals.grossKobo, currency)}
        </Text>
      </View>

      <DocumentSection kicker="Vendor identity" tone="elevated">
        <DefinitionList
          rows={[
            { label: "Store", value: vendor.name },
            { label: "Slug", value: vendor.storeSlug, mono: true },
            { label: "Legal name", value: vendor.legalName ?? vendor.name },
            {
              label: "Tax classification",
              value: vendor.taxClassification
                ? titleCase(vendor.taxClassification)
                : "Sole proprietor",
            },
            { label: "Tax region", value: vendor.taxRegion ?? "Nigeria" },
            { label: "Tax ID", value: vendor.taxId ?? "On file", mono: true },
            { label: "Payout method", value: titleCase(vendor.payoutMethod) },
            { label: "Settlement currency", value: currency },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker="Year totals">
        <DefinitionList
          rows={[
            { label: "Orders settled", value: String(totals.orders) },
            {
              label: "Gross revenue",
              value: formatKobo(totals.grossKobo, currency),
              mono: true,
            },
            {
              label: "Platform commission",
              value: `-${formatKobo(totals.commissionKobo, currency)}`,
              mono: true,
            },
            {
              label: "Processing fees",
              value: `-${formatKobo(totals.processingFeeKobo, currency)}`,
              mono: true,
            },
            {
              label: "Refunds + chargebacks",
              value:
                totals.refundsKobo > 0
                  ? `-${formatKobo(totals.refundsKobo, currency)}`
                  : formatKobo(0, currency),
              mono: true,
            },
            {
              label: "Net payouts",
              value: formatKobo(totals.netPayoutKobo, currency),
              mono: true,
            },
            { label: "Generated", value: formatDateTime(generatedAt) },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker="Monthly breakdown">
        <DataTable
          columns={columns}
          rows={rows}
          striped
          emptyMessage="No settled orders in this fiscal year."
          footerRow={{
            description: `Net payouts · ${fiscalYear}`,
            amount: formatKobo(totals.netPayoutKobo, currency),
          }}
        />
      </DocumentSection>

      <LegalFooter
        lines={[
          `This document is an informational summary of marketplace earnings for fiscal year ${fiscalYear}. Henry Holdings Limited does not file taxes on a vendor's behalf and makes no warranty as to suitability for any specific jurisdiction's return.`,
          "Cross-check this summary against your monthly payout statements. Discrepancies must be raised through the vendor workspace dispute channel before filing.",
          "Where required by your jurisdiction, Henry Holdings Limited will file information returns (1099-K-equivalent) with the relevant authority. A copy is retained with your vendor record.",
        ]}
      />
    </BrandedDocument>
  );
}
