import * as React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";
import { getBrandedDocumentsCopy, type AppLocale } from "@henryco/i18n";

import { BrandedDocument } from "../components/BrandedDocument";
import { DocumentSection, DefinitionList } from "../components/DocumentSection";
import { DataTable, type DataTableColumn } from "../components/DataTable";
import { LegalFooter } from "../components/SignatureBlock";
import {
  formatDateTime,
  formatKobo,
  statusToLabel,
  titleCase,
} from "../format";
import { letterSpacing, palette, typeScale } from "../tokens";

/**
 * V3 PASS 21 — VendorPayoutStatement PDF template.
 *
 * Monthly payout statement for a marketplace vendor. Lists every
 * fulfilled order group settling in the period, the platform
 * commission and processing fees withheld, and the net payout.
 *
 * Settlement currency is per-vendor (V2 multi-currency foundation).
 * FX snapshots are recorded inline when the order currency differs
 * from the vendor's settlement currency.
 *
 * Generated by the vendor workspace + emailed via the
 * marketplace-automation cron at payout cadence.
 */

export type VendorPayoutStatementRow = {
  id: string;
  orderNo: string;
  fulfilledAt: string;
  buyerLabel: string;
  serviceLabel?: string | null;
  status: string;
  grossAmountKobo: number;
  commissionKobo: number;
  processingFeeKobo: number;
  refundsKobo: number;
  netAmountKobo: number;
  fxRate?: number | null;
  orderCurrency?: string | null;
};

export type VendorPayoutStatementProps = {
  vendor: {
    id: string;
    name: string;
    legalName?: string | null;
    storeSlug: string;
    settlementCurrency: string;
    payoutMethod: string;
    payoutDestination?: string | null;
    taxId?: string | null;
  };
  period: {
    label: string;
    startsAt: string;
    endsAt: string;
  };
  totals: {
    orders: number;
    grossKobo: number;
    commissionKobo: number;
    processingFeeKobo: number;
    refundsKobo: number;
    netPayoutKobo: number;
  };
  rows: VendorPayoutStatementRow[];
  payoutReference?: string | null;
  scheduledFor?: string | null;
  generatedAt: string;
  locale?: AppLocale;
};

const styles = StyleSheet.create({
  banner: {
    marginTop: 16,
    backgroundColor: "#B2863B",
    color: palette.ink,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bannerLabel: {
    fontSize: typeScale.hairline,
    fontFamily: "HenryCoSans",
    color: "#1A140A",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: letterSpacing.kicker * 6,
  },
  bannerValue: {
    fontSize: typeScale.subhead,
    fontFamily: "HenryCoMono",
    color: "#1A140A",
    fontWeight: 700,
  },
});

export function VendorPayoutStatementDocument({
  vendor,
  period,
  totals,
  rows,
  payoutReference,
  scheduledFor,
  generatedAt,
  locale = "en",
}: VendorPayoutStatementProps) {
  const t = getBrandedDocumentsCopy(locale).vendorPayout;
  const currency = vendor.settlementCurrency;

  const columns: Array<DataTableColumn<VendorPayoutStatementRow>> = [
    {
      key: "orderNo",
      header: t.columnOrder,
      flex: 1.2,
      mono: true,
      render: (row) => row.orderNo,
    },
    {
      key: "fulfilledAt",
      header: t.columnFulfilled,
      flex: 1.4,
      render: (row) => formatDateTime(row.fulfilledAt),
    },
    {
      key: "buyer",
      header: t.columnBuyer,
      flex: 1.6,
      render: (row) => row.buyerLabel,
    },
    {
      key: "status",
      header: t.columnStatus,
      flex: 1,
      render: (row) => statusToLabel(row.status),
    },
    {
      key: "gross",
      header: t.columnGross,
      flex: 1.1,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.grossAmountKobo, currency),
    },
    {
      key: "commission",
      header: t.columnCommission,
      flex: 1.1,
      align: "right",
      mono: true,
      render: (row) => `-${formatKobo(row.commissionKobo, currency)}`,
    },
    {
      key: "fee",
      header: t.columnFee,
      flex: 0.9,
      align: "right",
      mono: true,
      render: (row) => `-${formatKobo(row.processingFeeKobo, currency)}`,
    },
    {
      key: "refunds",
      header: t.columnRefunds,
      flex: 0.9,
      align: "right",
      mono: true,
      render: (row) =>
        row.refundsKobo > 0 ? `-${formatKobo(row.refundsKobo, currency)}` : "—",
    },
    {
      key: "net",
      header: t.columnNet,
      flex: 1.2,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.netAmountKobo, currency),
    },
  ];

  return (
    <BrandedDocument
      locale={locale}
      metadata={{
        title: `Vendor payout · ${vendor.name} · ${period.label}`,
        subject: t.subject,
        keywords: ["marketplace", "vendor", "payout", "statement", vendor.name],
      }}
      header={{
        documentType: t.documentType,
        title: vendor.name,
        subtitle: `${period.label} · ${t.subtitleOrders(totals.orders)}`,
        meta: [
          { label: t.metaPeriod, value: period.label },
          { label: t.metaSettlement, value: currency },
          {
            label: t.metaReference,
            value: payoutReference ?? "—",
          },
        ],
        divisionLabel: t.divisionLabel,
      }}
      division="marketplace"
    >
      <View style={styles.banner}>
        <Text style={styles.bannerLabel}>{t.netPayout}</Text>
        <Text style={styles.bannerValue}>
          {formatKobo(totals.netPayoutKobo, currency)}
        </Text>
      </View>

      <DocumentSection kicker={t.sectionVendor} tone="elevated">
        <DefinitionList
          rows={[
            { label: t.rowStore, value: vendor.name },
            { label: t.rowSlug, value: vendor.storeSlug, mono: true },
            { label: t.rowLegalName, value: vendor.legalName ?? vendor.name },
            { label: t.rowTaxId, value: vendor.taxId ?? t.onFile },
            { label: t.rowPayoutMethod, value: titleCase(vendor.payoutMethod) },
            {
              label: t.rowDestination,
              value: vendor.payoutDestination ?? t.onFile,
              mono: true,
            },
            {
              label: t.rowSettlementCurrency,
              value: currency,
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker={t.sectionPeriodSummary}>
        <DefinitionList
          rows={[
            { label: t.rowOrdersSettled, value: String(totals.orders) },
            {
              label: t.rowGrossRevenue,
              value: formatKobo(totals.grossKobo, currency),
              mono: true,
            },
            {
              label: t.rowPlatformCommission,
              value: `-${formatKobo(totals.commissionKobo, currency)}`,
              mono: true,
            },
            {
              label: t.rowProcessingFees,
              value: `-${formatKobo(totals.processingFeeKobo, currency)}`,
              mono: true,
            },
            {
              label: t.rowRefundsChargebacks,
              value:
                totals.refundsKobo > 0
                  ? `-${formatKobo(totals.refundsKobo, currency)}`
                  : formatKobo(0, currency),
              mono: true,
            },
            {
              label: t.rowNetPayout,
              value: formatKobo(totals.netPayoutKobo, currency),
              mono: true,
            },
            {
              label: t.rowScheduledFor,
              value: scheduledFor ? formatDateTime(scheduledFor) : t.awaitingCycle,
            },
            {
              label: t.rowGenerated,
              value: formatDateTime(generatedAt),
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker={t.sectionItemised}>
        <DataTable
          columns={columns}
          rows={rows}
          striped
          emptyMessage={t.emptyOrders}
          footerRow={{
            description: t.footerNet,
            amount: formatKobo(totals.netPayoutKobo, currency),
          }}
        />
      </DocumentSection>

      <LegalFooter lines={[t.legalLine1, t.legalLine2, t.legalLine3]} />
    </BrandedDocument>
  );
}
