import * as React from "react";
import { Text, View, StyleSheet } from "@react-pdf/renderer";

import { BrandedDocument } from "../components/BrandedDocument";
import { DocumentSection, DefinitionList } from "../components/DocumentSection";
import { DataTable, type DataTableColumn } from "../components/DataTable";
import { LegalFooter } from "../components/SignatureBlock";
import {
  formatDateTime,
  formatKobo,
  statusToLabel,
  titleCase,
} from "../format";
import { letterSpacing, palette, typeScale } from "../tokens";

/**
 * V3 PASS 21 — VendorPayoutStatement PDF template.
 *
 * Monthly payout statement for a marketplace vendor. Lists every
 * fulfilled order group settling in the period, the platform
 * commission and processing fees withheld, and the net payout.
 *
 * Settlement currency is per-vendor (V2 multi-currency foundation).
 * FX snapshots are recorded inline when the order currency differs
 * from the vendor's settlement currency.
 *
 * Generated by the vendor workspace + emailed via the
 * marketplace-automation cron at payout cadence.
 */

export type VendorPayoutStatementRow = {
  id: string;
  orderNo: string;
  fulfilledAt: string;
  buyerLabel: string;
  serviceLabel?: string | null;
  status: string;
  grossAmountKobo: number;
  commissionKobo: number;
  processingFeeKobo: number;
  refundsKobo: number;
  netAmountKobo: number;
  fxRate?: number | null;
  orderCurrency?: string | null;
};

export type VendorPayoutStatementProps = {
  vendor: {
    id: string;
    name: string;
    legalName?: string | null;
    storeSlug: string;
    settlementCurrency: string;
    payoutMethod: string;
    payoutDestination?: string | null;
    taxId?: string | null;
  };
  period: {
    label: string;
    startsAt: string;
    endsAt: string;
  };
  totals: {
    orders: number;
    grossKobo: number;
    commissionKobo: number;
    processingFeeKobo: number;
    refundsKobo: number;
    netPayoutKobo: number;
  };
  rows: VendorPayoutStatementRow[];
  payoutReference?: string | null;
  scheduledFor?: string | null;
  generatedAt: string;
};

const styles = StyleSheet.create({
  banner: {
    marginTop: 16,
    backgroundColor: "#B2863B",
    color: palette.ink,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bannerLabel: {
    fontSize: typeScale.hairline,
    fontFamily: "HenryCoSans",
    color: "#1A140A",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: letterSpacing.kicker * 6,
  },
  bannerValue: {
    fontSize: typeScale.subhead,
    fontFamily: "HenryCoMono",
    color: "#1A140A",
    fontWeight: 700,
  },
});

export function VendorPayoutStatementDocument({
  vendor,
  period,
  totals,
  rows,
  payoutReference,
  scheduledFor,
  generatedAt,
}: VendorPayoutStatementProps) {
  const currency = vendor.settlementCurrency;

  const columns: Array<DataTableColumn<VendorPayoutStatementRow>> = [
    {
      key: "orderNo",
      header: "Order",
      flex: 1.2,
      mono: true,
      render: (row) => row.orderNo,
    },
    {
      key: "fulfilledAt",
      header: "Fulfilled",
      flex: 1.4,
      render: (row) => formatDateTime(row.fulfilledAt),
    },
    {
      key: "buyer",
      header: "Buyer",
      flex: 1.6,
      render: (row) => row.buyerLabel,
    },
    {
      key: "status",
      header: "Status",
      flex: 1,
      render: (row) => statusToLabel(row.status),
    },
    {
      key: "gross",
      header: "Gross",
      flex: 1.1,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.grossAmountKobo, currency),
    },
    {
      key: "commission",
      header: "Commission",
      flex: 1.1,
      align: "right",
      mono: true,
      render: (row) => `-${formatKobo(row.commissionKobo, currency)}`,
    },
    {
      key: "fee",
      header: "Fee",
      flex: 0.9,
      align: "right",
      mono: true,
      render: (row) => `-${formatKobo(row.processingFeeKobo, currency)}`,
    },
    {
      key: "refunds",
      header: "Refunds",
      flex: 0.9,
      align: "right",
      mono: true,
      render: (row) =>
        row.refundsKobo > 0 ? `-${formatKobo(row.refundsKobo, currency)}` : "—",
    },
    {
      key: "net",
      header: "Net",
      flex: 1.2,
      align: "right",
      mono: true,
      render: (row) => formatKobo(row.netAmountKobo, currency),
    },
  ];

  return (
    <BrandedDocument
      metadata={{
        title: `Vendor payout · ${vendor.name} · ${period.label}`,
        subject: "HenryCo Marketplace vendor payout statement",
        keywords: ["marketplace", "vendor", "payout", "statement", vendor.name],
      }}
      header={{
        documentType: "Payout statement",
        title: vendor.name,
        subtitle: `${period.label} · ${totals.orders} order${totals.orders === 1 ? "" : "s"}`,
        meta: [
          { label: "Period", value: period.label },
          { label: "Settlement", value: currency },
          {
            label: "Reference",
            value: payoutReference ?? "—",
          },
        ],
        divisionLabel: "Marketplace · Vendor payout",
      }}
      division="marketplace"
    >
      <View style={styles.banner}>
        <Text style={styles.bannerLabel}>Net payout</Text>
        <Text style={styles.bannerValue}>
          {formatKobo(totals.netPayoutKobo, currency)}
        </Text>
      </View>

      <DocumentSection kicker="Vendor" tone="elevated">
        <DefinitionList
          rows={[
            { label: "Store", value: vendor.name },
            { label: "Slug", value: vendor.storeSlug, mono: true },
            { label: "Legal name", value: vendor.legalName ?? vendor.name },
            { label: "Tax ID", value: vendor.taxId ?? "On file" },
            { label: "Payout method", value: titleCase(vendor.payoutMethod) },
            {
              label: "Destination",
              value: vendor.payoutDestination ?? "On file",
              mono: true,
            },
            {
              label: "Settlement currency",
              value: currency,
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker="Period summary">
        <DefinitionList
          rows={[
            { label: "Orders settled", value: String(totals.orders) },
            {
              label: "Gross revenue",
              value: formatKobo(totals.grossKobo, currency),
              mono: true,
            },
            {
              label: "Platform commission",
              value: `-${formatKobo(totals.commissionKobo, currency)}`,
              mono: true,
            },
            {
              label: "Processing fees",
              value: `-${formatKobo(totals.processingFeeKobo, currency)}`,
              mono: true,
            },
            {
              label: "Refunds + chargebacks",
              value:
                totals.refundsKobo > 0
                  ? `-${formatKobo(totals.refundsKobo, currency)}`
                  : formatKobo(0, currency),
              mono: true,
            },
            {
              label: "Net payout",
              value: formatKobo(totals.netPayoutKobo, currency),
              mono: true,
            },
            {
              label: "Scheduled for",
              value: scheduledFor ? formatDateTime(scheduledFor) : "Awaiting cycle",
            },
            {
              label: "Generated",
              value: formatDateTime(generatedAt),
            },
          ]}
        />
      </DocumentSection>

      <DocumentSection kicker="Itemised orders">
        <DataTable
          columns={columns}
          rows={rows}
          striped
          emptyMessage="No orders settled in this period."
          footerRow={{
            description: "Net for selected period",
            amount: formatKobo(totals.netPayoutKobo, currency),
          }}
        />
      </DocumentSection>

      <LegalFooter
        lines={[
          "This statement reflects orders that cleared the auto-release window during the period above. Refunds or disputes opened after the cut-off appear on the next statement.",
          "Tax position is the vendor's responsibility; Henry Holdings Limited withholds only the commission and processing fees disclosed in your vendor agreement.",
          "Discrepancies must be raised within 14 days through the vendor workspace dispute channel; we cannot re-issue payouts outside that window.",
        ]}
      />
    </BrandedDocument>
  );
}
