import { getDivisionConfig } from "@henryco/config";
import { upsertLearnRecord, type LearnUpsertMeta, syncLearnDivision } from "@/lib/learn/store";

export const LEARN_BOOTSTRAP_VERSION = "2026-06-10-academy-v4-expansion";

const cloudinaryCloud = String(process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME || process.env.CLOUDINARY_CLOUD_NAME || "henryco").trim();
const cloudinaryFolder = String(process.env.NEXT_PUBLIC_CLOUDINARY_FOLDER || process.env.CLOUDINARY_FOLDER || "henryco/learn").trim();

/**
 * Build a Cloudinary delivery URL for a seeded resource. Cloudinary is the
 * canonical video/asset host (preflight §3). When the asset hasn't been
 * uploaded yet, this still returns a stable URL that resolves to the
 * fallback "asset placeholder" PDF/image inside the configured folder.
 *
 * Real instructor authoring writes the actual upload URL via Cloudinary
 * unsigned upload; the seed serves as a baseline only.
 */
function cloudinaryResourceUrl(filename: string, kind: "raw" | "video" = "raw"): string {
  return `https://res.cloudinary.com/${cloudinaryCloud}/${kind}/upload/${cloudinaryFolder}/seed/${filename}`;
}

export function seedId(value: number) {
  return `00000000-0000-4000-8000-${String(value).padStart(12, "0")}`;
}

export const createdAt = "2026-04-02T18:00:00.000Z";
export const updatedAt = "2026-04-02T18:00:00.000Z";
export const learn = getDivisionConfig("learn");

export const categoryIds = {
  marketplace: seedId(101),
  internalOps: seedId(102),
  leadership: seedId(103),
  digital: seedId(104),
  onboarding: seedId(105),
  creativeDigital: seedId(106),
};

export const instructorIds = {
  ada: seedId(201),
  chika: seedId(202),
  tobi: seedId(203),
  grace: seedId(204),
  emeka: seedId(205),
  ngozi: seedId(206),
  bola: seedId(207),
};

export const planIds = {
  free: seedId(251),
  sellerCert: seedId(252),
  academyPro: seedId(253),
  internal: seedId(254),
};

const categories: Array<Record<string, unknown>> = [
  {
    id: categoryIds.marketplace,
    slug: "marketplace-academy",
    name: "Marketplace Academy",
    description: "Seller education, trust systems, and vendor certification.",
    hero_copy: "Teach vendors how to launch cleanly, earn trust, and grow responsibly.",
    accent: "#8F6A2E",
    icon: "Store",
    is_featured: true,
    sort_order: 1,
    course_count: 0,
    audience_tags: ["vendors", "sellers", "marketplace teams"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.internalOps,
    slug: "internal-operations",
    name: "Internal Operations",
    description: "Assigned internal training for service and logistics teams.",
    hero_copy: "Build reliable internal teams through calm, accountable training systems.",
    accent: learn.accent,
    icon: "ShieldCheck",
    is_featured: true,
    sort_order: 2,
    course_count: 0,
    audience_tags: ["staff", "ops", "internal teams"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.leadership,
    slug: "manager-academy",
    name: "Manager Academy",
    description: "Team leadership, escalation judgment, and support management.",
    hero_copy: "Train leads and managers to intervene earlier and coach with more clarity.",
    accent: "#4E6D8C",
    icon: "BriefcaseBusiness",
    is_featured: true,
    sort_order: 3,
    course_count: 0,
    audience_tags: ["managers", "support leads", "owners"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.digital,
    slug: "business-growth",
    name: "Business Growth",
    description: "Premium growth, systems thinking, positioning, and capability building.",
    hero_copy: "Help founders and operators grow with less chaos and better leverage.",
    accent: "#835C9A",
    icon: "TrendingUp",
    is_featured: true,
    sort_order: 4,
    course_count: 0,
    audience_tags: ["founders", "operators", "public learners"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.onboarding,
    slug: "client-onboarding",
    name: "Client Onboarding",
    description: "Help clients understand how Henry Onyx services, milestones, and support flows work.",
    hero_copy: "Turn onboarding into confidence instead of confusion.",
    accent: "#557D68",
    icon: "Compass",
    is_featured: false,
    sort_order: 5,
    course_count: 0,
    audience_tags: ["clients", "partners", "new customers"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.creativeDigital,
    slug: "creative-digital",
    name: "Creative & Digital Skills",
    description: "Practical brand, content, social selling, and digital marketing skills for Nigerian businesses.",
    hero_copy: "Build the brand, content, and online-selling skills that actually move sales here.",
    accent: "#B2863B",
    icon: "Sparkles",
    is_featured: true,
    sort_order: 6,
    course_count: 0,
    audience_tags: ["founders", "creators", "sellers", "marketers"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

const instructors: Array<Record<string, unknown>> = [
  {
    id: instructorIds.ada,
    slug: "ada-henry",
    full_name: "Ada Henry",
    title: "Academy Product Lead",
    bio: "Ada leads Henry Onyx learning strategy across public academy programs, partner enablement, and structured growth education.",
    expertise: ["academy strategy", "seller education", "offer design"],
    accent: learn.accent,
    avatar_url: null,
    spotlight_quote: "Premium learning feels calm, precise, and deeply actionable.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.chika,
    slug: "chika-okafor",
    full_name: "Chika Okafor",
    title: "Support Operations Director",
    bio: "Chika trains Henry Onyx team leads on escalation systems, service recovery, and manager intervention design.",
    expertise: ["support management", "team coaching", "escalations"],
    accent: "#4E6D8C",
    avatar_url: null,
    spotlight_quote: "Good support leadership removes panic before it spreads.",
    rating: 4.8,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.tobi,
    slug: "tobi-nwosu",
    full_name: "Tobi Nwosu",
    title: "Logistics Systems Lead",
    bio: "Tobi runs operational training for dispatch, riders, and proof-of-delivery readiness.",
    expertise: ["logistics", "dispatch", "proof of delivery"],
    accent: "#D06F32",
    avatar_url: null,
    spotlight_quote: "Reliable dispatch is a communication system before it is a speed system.",
    rating: 4.8,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.grace,
    slug: "grace-yusuf",
    full_name: "Grace Yusuf",
    title: "Customer Experience Lead",
    bio: "Grace focuses on premium service rituals, onboarding clarity, and customer trust through smoother operations.",
    expertise: ["customer experience", "service quality", "client onboarding"],
    accent: "#557D68",
    avatar_url: null,
    spotlight_quote: "The best onboarding lowers stress before questions start piling up.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.emeka,
    slug: "emeka-odili",
    full_name: "Emeka Odili",
    title: "Vendor Trust Director",
    bio: "Emeka leads seller trust, moderation quality, and vendor certification systems inside Henry Onyx Marketplace.",
    expertise: ["vendor trust", "moderation", "dispute prevention"],
    accent: "#8F6A2E",
    avatar_url: null,
    spotlight_quote: "Trust is earned through routine discipline, not a single polished moment.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.ngozi,
    slug: "ngozi-eze",
    full_name: "Ngozi Eze",
    title: "Finance & Pricing Lead",
    bio: "Ngozi teaches small-business owners how to price for profit, keep clean books, and read the numbers that actually run a business.",
    expertise: ["pricing", "bookkeeping", "cash flow", "unit economics"],
    accent: "#557D68",
    avatar_url: null,
    spotlight_quote: "You cannot grow what you refuse to measure.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.bola,
    slug: "bola-adeyemi",
    full_name: "Bola Adeyemi",
    title: "Brand & Digital Marketing Lead",
    bio: "Bola helps founders and sellers build a brand people trust and sell confidently on WhatsApp, Instagram, and beyond — without a big ad budget.",
    expertise: ["brand", "content", "social selling", "digital marketing"],
    accent: "#B2863B",
    avatar_url: null,
    spotlight_quote: "A clear brand sells before you ever open your mouth.",
    rating: 4.8,
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

const plans: Array<Record<string, unknown>> = [
  {
    id: planIds.free,
    slug: "academy-free",
    name: "Academy Free",
    description: "Open-access starter learning for public discovery and onboarding tracks.",
    price: 0,
    currency: "NGN",
    billing_type: "one_time",
    access_scope: "selected public courses",
    perks: ["Free enrollment", "Public onboarding tracks", "Progress dashboard"],
    is_public: true,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: planIds.sellerCert,
    slug: "seller-certification",
    name: "Seller Certification",
    description: "Certification-grade training for vendors who want Henry Onyx-recognized trust status.",
    price: 95000,
    currency: "NGN",
    billing_type: "one_time",
    access_scope: "certification courses",
    perks: ["Certification exam", "Downloadable certificate", "Verification-ready completion record"],
    is_public: true,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: planIds.academyPro,
    slug: "academy-pro",
    name: "Academy Pro",
    description: "Premium business education for operators, founders, and service teams.",
    price: 125000,
    currency: "NGN",
    billing_type: "one_time",
    access_scope: "advanced business programs",
    perks: ["Premium growth tracks", "Downloadable workbooks", "Completion certificate"],
    is_public: true,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: planIds.internal,
    slug: "internal-sponsored",
    name: "Internal Sponsored",
    description: "Company-sponsored access for Henry Onyx internal teams, onboarding, and compliance.",
    price: 0,
    currency: "NGN",
    billing_type: "internal",
    access_scope: "internal assignments",
    perks: ["Assigned training", "Completion monitoring", "Internal certification"],
    is_public: false,
    created_at: createdAt,
    updated_at: updatedAt,
  },
];
const courseBlueprints: Array<Record<string, unknown>> = [
  {
    id: seedId(301),
    slug: "marketplace-seller-launch",
    category_id: categoryIds.marketplace,
    primary_instructor_id: instructorIds.ada,
    title: "Marketplace Seller Launch",
    subtitle: "Get a Henry Onyx marketplace store confidently ready for day-one trust.",
    summary: "A premium starter course covering storefront setup, trust signals, and first-publish readiness.",
    description: "Marketplace Seller Launch gives vendors the calm, trust-first foundation needed before their first Henry Onyx sale.",
    duration_text: "2h 05m",
    estimated_minutes: 125,
    difficulty: "beginner",
    prerequisites: ["Basic product catalog prepared"],
    outcomes: ["Launch with a trust-first storefront structure", "Prepare seller operations before taking orders"],
    tags: ["seller", "launch", "marketplace", "trust"],
    visibility: "public",
    access_model: "free",
    plan_id: planIds.free,
    price: 0,
    currency: "NGN",
    featured: true,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Complete both modules and pass the readiness quiz.",
    status: "published",
    modules: [
      {
        id: seedId(401),
        title: "Storefront Foundations",
        summary: "Clarify promise, trust edge, and buyer confidence.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(501),
          slug: "store-promise",
          title: "Define the Store Promise Before Publishing",
          summary: "Strong sellers launch around clarity, not noise.",
          body_markdown: "## Store promise\n\nClarify who the store is for, what it promises, and why buyers should trust it before products go live.",
          duration_minutes: 28,
          lesson_type: "video",
          is_preview: true,
          resources: [
            {
              id: seedId(801),
              label: "Store positioning worksheet",
              resource_type: "worksheet",
              url: cloudinaryResourceUrl("store-positioning.pdf"),
            },
          ],
        },
      },
      {
        id: seedId(402),
        title: "Publish Readiness",
        summary: "Check listing quality and fulfillment confidence.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(502),
          slug: "publish-readiness",
          title: "Quality Control Before First Publish",
          summary: "Reduce moderation loops by publishing cleanly.",
          body_markdown: "## Publish readiness\n\nUse listing quality, fulfillment notes, and support clarity to protect trust before launch.",
          duration_minutes: 31,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(802),
              label: "Listing quality checklist",
              resource_type: "checklist",
              url: cloudinaryResourceUrl("listing-quality.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(901),
      title: "Seller launch readiness quiz",
      description: "Check whether the store is truly ready for first publish.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1001),
          prompt: "What should be clarified before the first product upload?",
          options: ["Store promise and buyer fit", "Holiday campaign copy", "A second warehouse"],
          correct_answer: ["Store promise and buyer fit"],
          explanation: "Trust begins with clarity.",
        },
        {
          id: seedId(1002),
          prompt: "What reduces moderation loops?",
          options: ["Clean listing quality", "More emojis", "Longer titles"],
          correct_answer: ["Clean listing quality"],
          explanation: "Prepared listings move through review faster.",
        },
      ],
    },
  },
  {
    id: seedId(302),
    slug: "verified-seller-certification",
    category_id: categoryIds.marketplace,
    primary_instructor_id: instructorIds.emeka,
    title: "Verified Seller Certification",
    subtitle: "Earn the operations-grade certification Henry Onyx uses to recognize reliable vendors.",
    summary: "A deeper seller certification covering trust operations, dispute prevention, and recovery handling.",
    description: "Verified Seller Certification focuses on repeatable reliability, stronger recovery routines, and public-facing trust.",
    duration_text: "3h 15m",
    estimated_minutes: 195,
    difficulty: "advanced",
    prerequisites: ["Marketplace Seller Launch completed"],
    outcomes: ["Understand the scorecard behind seller trust", "Qualify for a public-facing Henry Onyx certification layer"],
    tags: ["seller", "certification", "vendor", "trust"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.sellerCert,
    price: 95000,
    currency: "NGN",
    featured: true,
    is_certification: true,
    passing_score: 80,
    completion_rule: "Complete modules and pass the certification exam.",
    status: "published",
    modules: [
      {
        id: seedId(403),
        title: "Trust Operations",
        summary: "Decode the signals Henry Onyx tracks.",
        unlock_rule: "sequential",
        estimated_minutes: 95,
        lesson: {
          id: seedId(503),
          slug: "trust-operations",
          title: "How Trust Scores Are Earned",
          summary: "Certification depends on repeatable execution, not a one-time review.",
          body_markdown: "## Trust operations\n\nLearn the signals Henry Onyx tracks and how those signals shape seller visibility.",
          duration_minutes: 39,
          lesson_type: "video",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(404),
        title: "Issue Recovery",
        summary: "Reduce disputes and recover credibility after a miss.",
        unlock_rule: "sequential",
        estimated_minutes: 100,
        lesson: {
          id: seedId(504),
          slug: "issue-recovery",
          title: "Recover Trust After a Service Failure",
          summary: "Ownership and clarity matter more than defensiveness.",
          body_markdown: "## Issue recovery\n\nCertified sellers know how to respond clearly, take ownership, and protect future trust after a miss.",
          duration_minutes: 34,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(803),
              label: "Dispute prevention playbook",
              resource_type: "guide",
              url: cloudinaryResourceUrl("dispute-prevention.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(902),
      title: "Seller certification exam",
      description: "Measure operational judgment needed for verified-seller status.",
      pass_score: 80,
      max_attempts: 3,
      questions: [
        {
          id: seedId(1003),
          prompt: "What sustains trust over time?",
          options: ["Repeatable execution", "A single campaign", "Lower price alone"],
          correct_answer: ["Repeatable execution"],
          explanation: "Certification reflects repeatable reliability.",
        },
        {
          id: seedId(1004),
          prompt: "What protects recovery after a miss?",
          options: ["Fast ownership and clear next steps", "Silence", "Blame shifting"],
          correct_answer: ["Fast ownership and clear next steps"],
          explanation: "Ownership and clarity rebuild trust faster.",
        },
      ],
    },
  },
  {
    id: seedId(303),
    slug: "care-service-excellence",
    category_id: categoryIds.internalOps,
    primary_instructor_id: instructorIds.grace,
    title: "Care Service Excellence",
    subtitle: "Internal training for pickup, garment care, customer handling, and premium service discipline.",
    summary: "A Henry Onyx internal track for care staff who must deliver premium service quality across pickup and handoff moments.",
    description: "Care Service Excellence trains internal care staff on service rituals, quality control, and recovery handling.",
    duration_text: "2h 10m",
    estimated_minutes: 130,
    difficulty: "intermediate",
    prerequisites: ["Henry Onyx staff account"],
    outcomes: ["Deliver premium service rituals consistently", "Reduce avoidable quality-control lapses"],
    tags: ["internal", "care", "service", "compliance"],
    visibility: "internal",
    access_model: "sponsored",
    plan_id: planIds.internal,
    price: 0,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 80,
    completion_rule: "Assigned staff must finish all lessons and pass the assessment.",
    status: "published",
    modules: [
      {
        id: seedId(405),
        title: "Premium Service Rituals",
        summary: "Deliver calm, premium interactions from intake through handoff.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(505),
          slug: "intake-standard",
          title: "Intake Standard and Customer Assurance",
          summary: "Create trust at the counter and during pickup.",
          body_markdown: "## Intake standard\n\nA premium service experience starts at intake with clarity, confidence, and accurate capture of details.",
          duration_minutes: 26,
          lesson_type: "reading",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(406),
        title: "Quality Control and Recovery",
        summary: "Catch issues early and recover service confidence when exceptions happen.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(506),
          slug: "service-recovery",
          title: "Service Recovery for Premium Brands",
          summary: "Recover credibility quickly after a miss.",
          body_markdown: "## Service recovery\n\nPremium teams recover by acting early, communicating clearly, and preserving customer dignity.",
          duration_minutes: 24,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(804),
              label: "Service recovery framework",
              resource_type: "guide",
              url: cloudinaryResourceUrl("service-recovery.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(903),
      title: "Care service excellence assessment",
      description: "Confirm internal service readiness for care staff.",
      pass_score: 80,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1005),
          prompt: "Where does premium service confidence begin?",
          options: ["At intake", "After dispatch", "Only after payment"],
          correct_answer: ["At intake"],
          explanation: "Confidence starts when the customer first hands over responsibility.",
        },
        {
          id: seedId(1006),
          prompt: "What is central to premium recovery?",
          options: ["Early ownership", "Silence", "Blame shifting"],
          correct_answer: ["Early ownership"],
          explanation: "Clear ownership rebuilds trust faster.",
        },
      ],
    },
  },
  {
    id: seedId(304),
    slug: "support-manager-academy",
    category_id: categoryIds.leadership,
    primary_instructor_id: instructorIds.chika,
    title: "Support Manager Academy",
    subtitle: "Lead service, escalations, and team coaching without operational drift.",
    summary: "An internal training program for managers and support leads who handle escalations, coaching, and service-level decisions.",
    description: "Support Manager Academy equips Henry Onyx team leads and support managers with escalation judgment, coaching rhythms, and visibility practices.",
    duration_text: "2h 30m",
    estimated_minutes: 150,
    difficulty: "advanced",
    prerequisites: ["Henry Onyx manager or support-lead assignment"],
    outcomes: ["Handle escalations with better judgment", "Improve visibility and intervention timing"],
    tags: ["internal", "leadership", "support", "manager"],
    visibility: "internal",
    access_model: "sponsored",
    plan_id: planIds.internal,
    price: 0,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 85,
    completion_rule: "Finish the academy and pass the manager decision assessment.",
    status: "published",
    modules: [
      {
        id: seedId(407),
        title: "Escalation Judgment",
        summary: "Decide quickly and cleanly when service risk increases.",
        unlock_rule: "sequential",
        estimated_minutes: 75,
        lesson: {
          id: seedId(507),
          slug: "escalation-triggers",
          title: "Escalation Triggers That Matter",
          summary: "Recognize when a manager must step in before customer trust erodes.",
          body_markdown: "## Escalation triggers\n\nManagers add value when they intervene at the right threshold, not after chaos is visible to everyone.",
          duration_minutes: 28,
          lesson_type: "reading",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(408),
        title: "Coaching and Visibility",
        summary: "Use manager routines that lift the whole support system.",
        unlock_rule: "sequential",
        estimated_minutes: 75,
        lesson: {
          id: seedId(508),
          slug: "visibility-boards",
          title: "Visibility Boards and Intervention Signals",
          summary: "See risk earlier and intervene with less friction.",
          body_markdown: "## Visibility boards\n\nThe best service environments make risk visible before it becomes expensive.",
          duration_minutes: 26,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(805),
              label: "Manager intervention tracker",
              resource_type: "template",
              url: cloudinaryResourceUrl("intervention-tracker.xlsx"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(904),
      title: "Manager decision assessment",
      description: "Evaluate escalation and coaching judgment.",
      pass_score: 85,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1007),
          prompt: "When should a manager intervene?",
          options: ["At the right risk threshold", "Only after a complaint explodes", "Never if the queue is busy"],
          correct_answer: ["At the right risk threshold"],
          explanation: "Intervening at the correct threshold prevents avoidable trust damage.",
        },
        {
          id: seedId(1008),
          prompt: "Why do visibility boards matter?",
          options: ["They surface risk earlier", "They replace service teams", "They remove accountability"],
          correct_answer: ["They surface risk earlier"],
          explanation: "Visibility shortens intervention time.",
        },
      ],
    },
  },
  {
    id: seedId(305),
    slug: "logistics-rider-readiness",
    category_id: categoryIds.internalOps,
    primary_instructor_id: instructorIds.tobi,
    title: "Logistics Rider Readiness",
    subtitle: "Dispatch safely, communicate clearly, and execute reliable proof-of-delivery routines.",
    summary: "An internal rider training program focused on dispatch readiness, customer handling, and delivery proof discipline.",
    description: "Logistics Rider Readiness supports Henry Onyx Logistics teams with dispatch, safety, and proof-of-delivery standards.",
    duration_text: "1h 55m",
    estimated_minutes: 115,
    difficulty: "intermediate",
    prerequisites: ["Internal rider or fleet-team assignment"],
    outcomes: ["Improve proof-of-delivery accuracy", "Reduce avoidable route incidents and trust failures"],
    tags: ["internal", "logistics", "dispatch", "rider"],
    visibility: "internal",
    access_model: "sponsored",
    plan_id: planIds.internal,
    price: 0,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 80,
    completion_rule: "Complete all rider readiness lessons and pass the dispatch exam.",
    status: "published",
    modules: [
      {
        id: seedId(409),
        title: "Dispatch Reliability",
        summary: "Handle pickup and route communication with more control.",
        unlock_rule: "sequential",
        estimated_minutes: 55,
        lesson: {
          id: seedId(509),
          slug: "dispatch-communication",
          title: "Dispatch Communication Standards",
          summary: "Use calm updates and better expectation-setting during active runs.",
          body_markdown: "## Dispatch communication\n\nBuyers and senders trust what they can understand. Dispatch updates must be early, clear, and aligned with actual route conditions.",
          duration_minutes: 22,
          lesson_type: "reading",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(410),
        title: "Proof and Safety Discipline",
        summary: "Strengthen delivery proof and incident prevention.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(510),
          slug: "proof-of-delivery",
          title: "Proof-of-Delivery Discipline",
          summary: "Capture proof cleanly, accurately, and consistently.",
          body_markdown: "## Proof discipline\n\nProof-of-delivery protects operations, finance, support, and customer trust. Weak proof creates friction everywhere else.",
          duration_minutes: 24,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(806),
              label: "Incident report template",
              resource_type: "template",
              url: cloudinaryResourceUrl("incident-template.docx"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(905),
      title: "Dispatch readiness exam",
      description: "Validate rider readiness and route judgment.",
      pass_score: 80,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1009),
          prompt: "What makes dispatch updates trustworthy?",
          options: ["Clarity aligned with real route conditions", "Frequent guessing", "Late updates only"],
          correct_answer: ["Clarity aligned with real route conditions"],
          explanation: "Accuracy and timing matter more than volume.",
        },
        {
          id: seedId(1010),
          prompt: "Why does proof-of-delivery matter?",
          options: ["It protects multiple teams and trust", "It is optional", "It only helps finance"],
          correct_answer: ["It protects multiple teams and trust"],
          explanation: "Proof quality reduces downstream friction.",
        },
      ],
    },
  },
  {
    id: seedId(306),
    slug: "business-growth-foundations",
    category_id: categoryIds.digital,
    primary_instructor_id: instructorIds.ada,
    title: "Business Growth Foundations",
    subtitle: "Clarify positioning, offers, and operations before growth compounds the wrong system.",
    summary: "A premium public course for service businesses that want sharper positioning, stronger offers, and calmer growth systems.",
    description: "Business Growth Foundations helps service founders and operators improve positioning, delivery clarity, and growth systems before scaling.",
    duration_text: "2h 25m",
    estimated_minutes: 145,
    difficulty: "intermediate",
    prerequisites: ["An active service or product offer"],
    outcomes: ["Sharpen business positioning and offer structure", "Build a clearer path from lead to delivery"],
    tags: ["business", "growth", "founder", "offer"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 125000,
    currency: "NGN",
    featured: true,
    is_certification: true,
    passing_score: 75,
    completion_rule: "Complete all lessons and pass the business growth assessment.",
    status: "published",
    modules: [
      {
        id: seedId(411),
        title: "Positioning and Offer Design",
        summary: "Define what you sell, for whom, and why the market should trust it.",
        unlock_rule: "sequential",
        estimated_minutes: 70,
        lesson: {
          id: seedId(511),
          slug: "offer-clarity",
          title: "Offer Clarity Before Promotion",
          summary: "Make the offer easier to buy before spending to attract attention.",
          body_markdown: "## Offer clarity\n\nGrowth gets expensive when the offer itself is fuzzy. Simplify what you sell, who it is for, and how it creates confidence.",
          duration_minutes: 29,
          lesson_type: "video",
          is_preview: true,
          resources: [],
        },
      },
      {
        id: seedId(412),
        title: "Growth Systems and Delivery",
        summary: "Align marketing ambition with delivery discipline.",
        unlock_rule: "sequential",
        estimated_minutes: 75,
        lesson: {
          id: seedId(512),
          slug: "growth-bottlenecks",
          title: "Find the Bottleneck Before You Scale",
          summary: "Spot the real constraint that will break first under growth.",
          body_markdown: "## Growth bottlenecks\n\nMost growth problems are delivery problems disguised as marketing ambition. Fix the system before increasing volume.",
          duration_minutes: 31,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(807),
              label: "Growth bottleneck worksheet",
              resource_type: "worksheet",
              url: cloudinaryResourceUrl("growth-bottleneck.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(906),
      title: "Business growth assessment",
      description: "Measure readiness to grow without operational drift.",
      pass_score: 75,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1011),
          prompt: "What makes growth expensive too early?",
          options: ["A fuzzy offer", "A clearer promise", "Better fulfillment"],
          correct_answer: ["A fuzzy offer"],
          explanation: "Weak offer clarity wastes acquisition effort.",
        },
        {
          id: seedId(1012),
          prompt: "What often hides behind growth problems?",
          options: ["Delivery bottlenecks", "Too much clarity", "Excess trust"],
          correct_answer: ["Delivery bottlenecks"],
          explanation: "Operational friction often limits growth first.",
        },
      ],
    },
  },
  {
    id: seedId(307),
    slug: "henryco-client-onboarding",
    category_id: categoryIds.onboarding,
    primary_instructor_id: instructorIds.grace,
    title: "Henry Onyx Client Onboarding",
    subtitle: "Understand how Henry Onyx projects, requests, approvals, and support flows work from day one.",
    summary: "A free public onboarding track that helps new Henry Onyx clients understand process, communication, approvals, and support expectations.",
    description: "Henry Onyx Client Onboarding clarifies the operating model, milestone expectations, collaboration rituals, and support channels that keep projects calm.",
    duration_text: "1h 30m",
    estimated_minutes: 90,
    difficulty: "beginner",
    prerequisites: ["None"],
    outcomes: ["Understand Henry Onyx workflows faster", "Reduce avoidable friction during onboarding"],
    tags: ["onboarding", "client", "services", "process"],
    visibility: "public",
    access_model: "free",
    plan_id: planIds.free,
    price: 0,
    currency: "NGN",
    featured: true,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Finish the onboarding lessons and complete the readiness check.",
    status: "published",
    modules: [
      {
        id: seedId(413),
        title: "How Henry Onyx Works",
        summary: "See the service lifecycle from request to delivery.",
        unlock_rule: "sequential",
        estimated_minutes: 45,
        lesson: {
          id: seedId(513),
          slug: "project-rhythm",
          title: "Project Rhythm and Milestones",
          summary: "Understand how Henry Onyx structures requests, milestones, and approvals.",
          body_markdown: "## Project rhythm\n\nClients move faster when they understand what happens next, who owns each step, and what approvals unlock progress.",
          duration_minutes: 19,
          lesson_type: "reading",
          is_preview: true,
          resources: [],
        },
      },
      {
        id: seedId(414),
        title: "Support and Handoffs",
        summary: "Know how support, revisions, and handoffs work cleanly.",
        unlock_rule: "sequential",
        estimated_minutes: 45,
        lesson: {
          id: seedId(514),
          slug: "support-escalation",
          title: "Support, Escalation, and Next-Step Clarity",
          summary: "Use the support system with less friction.",
          body_markdown: "## Support and escalation\n\nHenry Onyx support works best when requests are contextualized clearly and routed through the correct lane.",
          duration_minutes: 18,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(808),
              label: "Client onboarding checklist",
              resource_type: "checklist",
              url: cloudinaryResourceUrl("client-onboarding-checklist.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(907),
      title: "Client onboarding readiness check",
      description: "Confirm the client understands the operating model.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1013),
          prompt: "What keeps project delivery calmer?",
          options: ["Clear ownership of next steps", "More disconnected channels", "Skipping approvals"],
          correct_answer: ["Clear ownership of next steps"],
          explanation: "Clarity lowers friction throughout the project.",
        },
        {
          id: seedId(1014),
          prompt: "How should support requests be handled?",
          options: ["Route them with context", "Send incomplete requests", "Escalate everything immediately"],
          correct_answer: ["Route them with context"],
          explanation: "Contextual requests are resolved faster.",
        },
      ],
    },
  },
  {
    id: seedId(308),
    slug: "selling-on-whatsapp-and-instagram",
    category_id: categoryIds.creativeDigital,
    primary_instructor_id: instructorIds.bola,
    title: "Selling on WhatsApp & Instagram",
    subtitle: "Turn chats and posts into orders — the way sales actually happen in Nigeria.",
    summary: "A practical course on running a clean, trusted, high-converting social storefront on WhatsApp and Instagram.",
    description: "Most Nigerian sales close in a DM or a WhatsApp chat. This course shows you how to set up a trusted profile, post so people buy, reply in a way that closes, and collect payment without back-and-forth — so you stop losing ready buyers.",
    duration_text: "2h 20m",
    estimated_minutes: 140,
    difficulty: "beginner",
    prerequisites: ["A product or service you can sell", "A WhatsApp Business or Instagram account"],
    outcomes: ["Set up a profile and catalog buyers instantly trust", "Run a chat-to-payment flow that closes faster with fewer drop-offs"],
    tags: ["social selling", "whatsapp", "instagram", "marketing"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 65000,
    currency: "NGN",
    featured: true,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Complete both modules and pass the conversion quiz.",
    status: "published",
    modules: [
      {
        id: seedId(415),
        title: "A Storefront People Trust",
        summary: "Profile, catalog, and proof that make a stranger comfortable buying.",
        unlock_rule: "sequential",
        estimated_minutes: 70,
        lesson: {
          id: seedId(515),
          slug: "trusted-social-profile",
          title: "Set Up a Profile That Earns the First Order",
          summary: "Trust is the real conversion lever — build it into your bio, catalog, and proof.",
          body_markdown: "## A profile that sells\n\nBuyers decide in seconds whether you look real. Use a clear display name, a one-line promise, a reachable contact, a tidy catalog with prices, and visible proof (delivered orders, reviews, before/after). Hide your prices and you train buyers to scroll past.",
          duration_minutes: 30,
          lesson_type: "video",
          is_preview: true,
          resources: [
            {
              id: seedId(809),
              label: "Social storefront setup checklist",
              resource_type: "checklist",
              url: cloudinaryResourceUrl("social-storefront-checklist.pdf"),
            },
          ],
        },
      },
      {
        id: seedId(416),
        title: "Chat-to-Payment",
        summary: "Reply, handle objections, and collect payment without endless back-and-forth.",
        unlock_rule: "sequential",
        estimated_minutes: 70,
        lesson: {
          id: seedId(516),
          slug: "chat-to-payment",
          title: "Close the Sale Inside the Chat",
          summary: "A simple reply flow that answers the real question and asks for the order.",
          body_markdown: "## From 'how much?' to paid\n\nMost sales die in slow, vague replies. Answer price + what's included + delivery in one message, confirm the order details back to the buyer, then send one clear way to pay. Always ask for the order — 'Should I lock this in for you?' closes more than another product photo.",
          duration_minutes: 28,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(810),
              label: "Reply templates that convert",
              resource_type: "template",
              url: cloudinaryResourceUrl("conversion-reply-templates.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(908),
      title: "Social selling conversion quiz",
      description: "Check that your storefront and chat flow are built to close.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1015),
          prompt: "What most improves first-time buyer trust on a social storefront?",
          options: ["Visible prices and proof of delivered orders", "More hashtags", "Hiding prices until they ask"],
          correct_answer: ["Visible prices and proof of delivered orders"],
          explanation: "Clarity and proof remove the hesitation that kills first orders.",
        },
        {
          id: seedId(1016),
          prompt: "What closes more sales inside a chat?",
          options: ["Answering clearly and asking for the order", "Sending more product photos", "Waiting for the buyer to decide alone"],
          correct_answer: ["Answering clearly and asking for the order"],
          explanation: "A clear answer plus a direct ask converts a ready buyer.",
        },
      ],
    },
  },
  {
    id: seedId(309),
    slug: "money-and-bookkeeping-for-small-business",
    category_id: categoryIds.digital,
    primary_instructor_id: instructorIds.ngozi,
    title: "Money & Bookkeeping for Small Business",
    subtitle: "Know your numbers, separate business from personal, and stop guessing about profit.",
    summary: "A no-jargon course on tracking money cleanly so you always know what you made, what you owe, and what is safe to spend.",
    description: "Most small businesses confuse cash in the account with profit — and run into trouble. This course gives you a simple, repeatable way to record income and expenses, separate business from personal money, and read the three numbers that tell you if the business is actually healthy.",
    duration_text: "2h 00m",
    estimated_minutes: 120,
    difficulty: "beginner",
    prerequisites: ["An operating business or side income"],
    outcomes: ["Keep clean, consistent books in under 15 minutes a week", "Know your real profit, not just your bank balance"],
    tags: ["finance", "bookkeeping", "cash flow", "small business"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 75000,
    currency: "NGN",
    featured: true,
    is_certification: true,
    passing_score: 75,
    completion_rule: "Complete all lessons and pass the bookkeeping assessment.",
    status: "published",
    modules: [
      {
        id: seedId(417),
        title: "Clean Records, Every Week",
        summary: "A simple system for recording income and expenses you will actually keep up.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(517),
          slug: "weekly-bookkeeping-habit",
          title: "The 15-Minute Weekly Books Habit",
          summary: "Separate accounts and a weekly routine beat a perfect system you abandon.",
          body_markdown: "## Keep it simple, keep it weekly\n\nOpen a dedicated business account and pay yourself a salary out of it — never spend business money as personal. Once a week, record every inflow and outflow in one sheet with date, amount, and category. Consistency matters far more than fancy software.",
          duration_minutes: 26,
          lesson_type: "video",
          is_preview: true,
          resources: [
            {
              id: seedId(811),
              label: "Simple income & expense tracker",
              resource_type: "template",
              url: cloudinaryResourceUrl("income-expense-tracker.xlsx"),
            },
          ],
        },
      },
      {
        id: seedId(418),
        title: "The Three Numbers That Matter",
        summary: "Revenue, true profit, and cash runway — and why the bank balance lies.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(518),
          slug: "profit-vs-cash",
          title: "Why Your Bank Balance Is Not Your Profit",
          summary: "Money owed, stock bought, and money you'll owe later all hide inside that balance.",
          body_markdown: "## Profit is not the balance\n\nYour account can look healthy while the business is losing money — because it holds deposits you must deliver on, stock you already paid for, and taxes you'll owe later. Track revenue, subtract real costs to find profit, and always know how many weeks of expenses your cash can cover.",
          duration_minutes: 27,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(812),
              label: "Profit & cash-runway worksheet",
              resource_type: "worksheet",
              url: cloudinaryResourceUrl("profit-runway-worksheet.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(909),
      title: "Bookkeeping assessment",
      description: "Confirm you can keep clean books and read your real numbers.",
      pass_score: 75,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1017),
          prompt: "What is the first step to clean business books?",
          options: ["A separate business account and a weekly recording habit", "A bigger marketing budget", "Spending business money for personal needs"],
          correct_answer: ["A separate business account and a weekly recording habit"],
          explanation: "Separation plus consistency makes every other report reliable.",
        },
        {
          id: seedId(1018),
          prompt: "Why is your bank balance not your profit?",
          options: ["It hides deposits owed, stock already paid for, and future tax", "Banks add hidden profit", "Profit and balance are always equal"],
          correct_answer: ["It hides deposits owed, stock already paid for, and future tax"],
          explanation: "Profit is revenue minus real costs — not whatever sits in the account today.",
        },
      ],
    },
  },
  {
    id: seedId(310),
    slug: "pricing-and-profit-for-service-businesses",
    category_id: categoryIds.digital,
    primary_instructor_id: instructorIds.ngozi,
    title: "Pricing & Profit for Service Businesses",
    subtitle: "Charge what the work is worth — with numbers that back you up.",
    summary: "Learn to price services for real profit, raise rates with confidence, and stop underpricing out of fear.",
    description: "Underpricing is the quietest way a good business dies. This course shows you how to cost a service properly, build a price that includes profit (not just survival), present it with confidence, and raise rates without losing the clients worth keeping.",
    duration_text: "1h 50m",
    estimated_minutes: 110,
    difficulty: "intermediate",
    prerequisites: ["A service offer you currently sell"],
    outcomes: ["Build prices from real costs plus a deliberate profit margin", "Raise rates and present pricing without flinching"],
    tags: ["pricing", "profit", "services", "margins"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 85000,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 75,
    completion_rule: "Complete all lessons and pass the pricing assessment.",
    status: "published",
    modules: [
      {
        id: seedId(419),
        title: "Cost, Then Profit",
        summary: "Find your true cost to deliver before you ever name a price.",
        unlock_rule: "sequential",
        estimated_minutes: 55,
        lesson: {
          id: seedId(519),
          slug: "price-from-cost",
          title: "Build the Price From the Cost Up",
          summary: "If you don't know what delivery costs, every price is a guess.",
          body_markdown: "## Price from cost up\n\nAdd up everything a job consumes: your time, materials, transport, tools, and a share of fixed costs (rent, data, subscriptions). That's your cost floor. Your price is the floor plus a deliberate profit margin — not a number you picked because a competitor charges it.",
          duration_minutes: 26,
          lesson_type: "video",
          is_preview: true,
          resources: [
            {
              id: seedId(813),
              label: "Service costing & margin calculator",
              resource_type: "template",
              url: cloudinaryResourceUrl("service-costing-calculator.xlsx"),
            },
          ],
        },
      },
      {
        id: seedId(420),
        title: "Present & Raise With Confidence",
        summary: "Communicate value, handle 'it's too expensive', and raise rates cleanly.",
        unlock_rule: "sequential",
        estimated_minutes: 55,
        lesson: {
          id: seedId(520),
          slug: "present-and-raise-prices",
          title: "Say Your Price Without Flinching",
          summary: "Anchor on the outcome, hold your number, and give existing clients fair notice.",
          body_markdown: "## Own your price\n\nLead with the outcome the client gets, state the price plainly, and stop talking. Don't discount the moment someone hesitates — offer a smaller scope instead. When raising rates, give existing clients clear notice and a reason tied to value, not apology.",
          duration_minutes: 24,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(814),
              label: "Price-conversation scripts",
              resource_type: "guide",
              url: cloudinaryResourceUrl("price-conversation-scripts.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(910),
      title: "Pricing assessment",
      description: "Confirm you can price for profit and defend the number.",
      pass_score: 75,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1019),
          prompt: "What should a price always be built on?",
          options: ["Your true cost to deliver plus a deliberate margin", "Whatever a competitor charges", "The lowest number that wins the job"],
          correct_answer: ["Your true cost to deliver plus a deliberate margin"],
          explanation: "Costing first ensures every sale actually makes money.",
        },
        {
          id: seedId(1020),
          prompt: "What's the better response when a client says 'it's too expensive'?",
          options: ["Offer a smaller scope, not an automatic discount", "Immediately cut the price", "End the conversation"],
          correct_answer: ["Offer a smaller scope, not an automatic discount"],
          explanation: "Adjust what's delivered, not your worth.",
        },
      ],
    },
  },
  {
    id: seedId(311),
    slug: "customer-service-that-wins-repeat-buyers",
    category_id: categoryIds.digital,
    primary_instructor_id: instructorIds.grace,
    title: "Customer Service That Wins Repeat Buyers",
    subtitle: "Turn one-time customers into people who come back and refer you.",
    summary: "A practical customer-service course for any business: respond well, recover from mistakes, and build loyalty that compounds.",
    description: "It costs far less to keep a customer than to find a new one — and great service is the cheapest marketing there is. This course teaches the response habits, recovery moves, and follow-up rituals that turn a single purchase into repeat orders and referrals.",
    duration_text: "1h 40m",
    estimated_minutes: 100,
    difficulty: "beginner",
    prerequisites: ["Customers or clients you serve"],
    outcomes: ["Respond in a way that builds trust under pressure", "Recover from a mistake so the customer stays — and refers"],
    tags: ["customer service", "retention", "loyalty", "communication"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 55000,
    currency: "NGN",
    featured: false,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Complete both modules and pass the service quiz.",
    status: "published",
    modules: [
      {
        id: seedId(421),
        title: "Respond So They Trust You",
        summary: "Speed, clarity, and tone that calm a customer instead of stalling them.",
        unlock_rule: "sequential",
        estimated_minutes: 50,
        lesson: {
          id: seedId(521),
          slug: "response-that-builds-trust",
          title: "The First Reply Sets the Whole Tone",
          summary: "Acknowledge fast, set a clear expectation, and never leave a customer guessing.",
          body_markdown: "## The reply that keeps them\n\nA quick acknowledgement — even 'Got it, I'll confirm by 4pm' — beats a perfect answer that comes too late. Be warm, be specific about the next step, and follow through on the time you promised. Silence is what loses customers, not honesty about a delay.",
          duration_minutes: 24,
          lesson_type: "video",
          is_preview: true,
          resources: [],
        },
      },
      {
        id: seedId(422),
        title: "Recover & Keep Them Coming Back",
        summary: "Turn a complaint into loyalty, then earn the next order with simple follow-up.",
        unlock_rule: "sequential",
        estimated_minutes: 50,
        lesson: {
          id: seedId(522),
          slug: "recover-and-retain",
          title: "Recover From a Mistake — and Win Them for Life",
          summary: "Own it, fix it, and follow up; a well-handled problem builds more loyalty than a smooth sale.",
          body_markdown: "## Recovery beats perfection\n\nWhen something goes wrong, take ownership without excuses, make it right quickly, and add one small gesture. Then close the loop later: a short 'How is everything now?' message turns a saved customer into a repeat buyer and a referral source.",
          duration_minutes: 23,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(815),
              label: "Service recovery & follow-up scripts",
              resource_type: "guide",
              url: cloudinaryResourceUrl("service-followup-scripts.pdf"),
            },
            {
              id: seedId(816),
              label: "Repeat-customer follow-up calendar",
              resource_type: "template",
              url: cloudinaryResourceUrl("followup-calendar.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(911),
      title: "Customer service quiz",
      description: "Confirm the habits that turn buyers into repeat customers.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1021),
          prompt: "What loses customers fastest?",
          options: ["Silence and being left to guess", "An honest update about a delay", "A quick acknowledgement"],
          correct_answer: ["Silence and being left to guess"],
          explanation: "Customers forgive delays they're informed about; silence feels like neglect.",
        },
        {
          id: seedId(1022),
          prompt: "What builds the most loyalty?",
          options: ["Owning a mistake and making it right", "Pretending nothing went wrong", "Blaming the supplier"],
          correct_answer: ["Owning a mistake and making it right"],
          explanation: "A well-handled problem often creates more loyalty than a flawless sale.",
        },
      ],
    },
  },
  {
    id: seedId(312),
    slug: "brand-and-content-foundations",
    category_id: categoryIds.creativeDigital,
    primary_instructor_id: instructorIds.bola,
    title: "Brand & Content Foundations",
    subtitle: "Look professional, sound like yourself, and post content that brings buyers.",
    summary: "Build a simple, consistent brand and a content rhythm that earns attention and trust — no design degree required.",
    description: "A strong brand makes a small business look bigger and a stranger feel safe buying. This course covers the few brand basics that matter, how to find a voice people remember, and a lightweight content plan you can actually keep up with so your page stays alive.",
    duration_text: "2h 05m",
    estimated_minutes: 125,
    difficulty: "beginner",
    prerequisites: ["A business or offer you want to promote"],
    outcomes: ["Set up consistent brand basics that look professional anywhere", "Plan content you can sustain that moves people toward buying"],
    tags: ["brand", "content", "marketing", "identity"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 75000,
    currency: "NGN",
    featured: false,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Complete both modules and pass the brand quiz.",
    status: "published",
    modules: [
      {
        id: seedId(423),
        title: "Brand Basics That Matter",
        summary: "Name, colours, logo usage, and a one-line promise that stays consistent.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(523),
          slug: "brand-basics",
          title: "The Few Brand Choices That Actually Matter",
          summary: "Consistency beats fancy — pick a look and a promise and repeat them everywhere.",
          body_markdown: "## Consistency is the brand\n\nYou don't need a studio. Pick two or three colours, one clear logo or wordmark, one font pairing, and a one-line promise — then use them the same way on every post, receipt, and profile. Recognition comes from repetition, not from redesigning every week.",
          duration_minutes: 28,
          lesson_type: "video",
          is_preview: true,
          resources: [
            {
              id: seedId(817),
              label: "One-page brand basics worksheet",
              resource_type: "worksheet",
              url: cloudinaryResourceUrl("brand-basics-worksheet.pdf"),
            },
          ],
        },
      },
      {
        id: seedId(424),
        title: "A Content Rhythm You Can Keep",
        summary: "A simple weekly mix that keeps the page alive and moves people to buy.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(524),
          slug: "content-rhythm",
          title: "Post With a Plan, Not With Pressure",
          summary: "Mix proof, teaching, and offers on a rhythm you can sustain.",
          body_markdown: "## A rhythm beats bursts\n\nRotate three kinds of posts: proof (happy customers, finished work), value (a tip that helps your buyer), and offers (what to buy and how). A steady three-a-week you can keep beats a flood you abandon. Batch a week of content in one sitting so a busy week never kills your page.",
          duration_minutes: 26,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(818),
              label: "Weekly content planner",
              resource_type: "template",
              url: cloudinaryResourceUrl("weekly-content-planner.pdf"),
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(912),
      title: "Brand & content quiz",
      description: "Confirm the brand and content basics that build recognition.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1023),
          prompt: "What makes a small brand recognisable?",
          options: ["Using the same colours, logo, and promise consistently", "Redesigning the look every week", "Copying a big competitor exactly"],
          correct_answer: ["Using the same colours, logo, and promise consistently"],
          explanation: "Recognition is built through repetition, not constant change.",
        },
        {
          id: seedId(1024),
          prompt: "What content rhythm works best for a small business?",
          options: ["A sustainable mix of proof, value, and offers", "Only hard-sell posts", "A burst of posts then long silence"],
          correct_answer: ["A sustainable mix of proof, value, and offers"],
          explanation: "A steady, balanced rhythm keeps attention and moves people to buy.",
        },
      ],
    },
  },
];
const paths: Array<Record<string, unknown>> = [
  {
    id: seedId(1101),
    slug: "marketplace-seller-academy",
    title: "Marketplace Seller Academy",
    summary: "From first storefront clarity to verified seller trust.",
    description: "A structured academy path for new and growing vendors who want to launch well and earn trust inside Henry Onyx Marketplace.",
    hero_image_url: null,
    audience: "Public vendors and seller teams",
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.sellerCert,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1201), item_type: "course", course_slug: "marketplace-seller-launch", label: "Seller launch", description: "Build the storefront and trust basics first.", sort_order: 1, required: true },
      { id: seedId(1202), item_type: "course", course_slug: "verified-seller-certification", label: "Seller certification", description: "Move into the deeper certification layer.", sort_order: 2, required: true },
      { id: seedId(1203), item_type: "course", course_slug: "henryco-client-onboarding", label: "Platform onboarding", description: "Understand the wider Henry Onyx operating model.", sort_order: 3, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1102),
    slug: "care-staff-academy",
    title: "Care Staff Academy",
    summary: "Internal service quality, escalation readiness, and completion monitoring.",
    description: "This internal path combines service rituals and manager visibility for teams responsible for care quality and customer trust.",
    hero_image_url: null,
    audience: "Internal care and support teams",
    visibility: "internal",
    access_model: "internal",
    plan_id: planIds.internal,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1204), item_type: "course", course_slug: "care-service-excellence", label: "Service excellence", description: "Core quality and recovery training.", sort_order: 1, required: true },
      { id: seedId(1205), item_type: "course", course_slug: "support-manager-academy", label: "Manager escalation", description: "Required for leads and support managers.", sort_order: 2, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1103),
    slug: "logistics-readiness-track",
    title: "Logistics Readiness Track",
    summary: "Dispatch communication, rider proof, and manager response readiness.",
    description: "A Henry Onyx internal path that aligns rider execution with escalation management and support visibility.",
    hero_image_url: null,
    audience: "Internal logistics teams",
    visibility: "internal",
    access_model: "internal",
    plan_id: planIds.internal,
    featured: false,
    status: "published",
    items: [
      { id: seedId(1206), item_type: "course", course_slug: "logistics-rider-readiness", label: "Rider readiness", description: "Dispatch and proof-of-delivery discipline.", sort_order: 1, required: true },
      { id: seedId(1207), item_type: "course", course_slug: "support-manager-academy", label: "Escalation management", description: "Recommended for team leads and shift managers.", sort_order: 2, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1104),
    slug: "business-growth-academy",
    title: "Business Growth Academy",
    summary: "Sharpen offers, reduce bottlenecks, and onboard clients more cleanly.",
    description: "A public academy track for operators and founders who want stronger growth systems and smoother onboarding outcomes.",
    hero_image_url: null,
    audience: "Founders, operators, and growth teams",
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1208), item_type: "course", course_slug: "business-growth-foundations", label: "Growth foundations", description: "Positioning, offers, and bottlenecks.", sort_order: 1, required: true },
      { id: seedId(1209), item_type: "course", course_slug: "henryco-client-onboarding", label: "Client onboarding", description: "Create smoother onboarding and approval flows.", sort_order: 2, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1105),
    slug: "sell-and-grow-online",
    title: "Sell & Grow Online",
    summary: "Build a brand, sell on social, and keep the customers you win.",
    description: "A public academy path for sellers and founders who want to look professional, close more orders in chats and DMs, and turn first-time buyers into repeat customers.",
    hero_image_url: null,
    audience: "Sellers, founders, and online businesses",
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1210), item_type: "course", course_slug: "brand-and-content-foundations", label: "Brand & content", description: "Look professional and post content that brings buyers.", sort_order: 1, required: true },
      { id: seedId(1211), item_type: "course", course_slug: "selling-on-whatsapp-and-instagram", label: "Sell on social", description: "Turn chats and posts into paid orders.", sort_order: 2, required: true },
      { id: seedId(1212), item_type: "course", course_slug: "customer-service-that-wins-repeat-buyers", label: "Keep your customers", description: "Win repeat orders and referrals.", sort_order: 3, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
];
const reviews: Array<Record<string, unknown>> = [
  { id: seedId(1301), course_id: seedId(301), user_id: null, normalized_email: "vendor.launch@henryonyx.com", rating: 5, title: "Sharper than most marketplace courses", body: "The course made our storefront feel intentional instead of rushed.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1302), course_id: seedId(306), user_id: null, normalized_email: "growth.operator@henryonyx.com", rating: 5, title: "Clear growth thinking", body: "It made us fix the system behind growth before spending to scale.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1303), course_id: seedId(307), user_id: null, normalized_email: "client.onboarding@henryonyx.com", rating: 4, title: "Helpful before kickoff", body: "The onboarding course answered questions we usually ask weeks later.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1304), course_id: seedId(308), user_id: null, normalized_email: "social.seller@henryonyx.com", rating: 5, title: "My DMs finally convert", body: "The chat-to-payment flow alone paid for the course in a week. Way fewer 'I'll get back to you' replies.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1305), course_id: seedId(309), user_id: null, normalized_email: "shop.owner@henryonyx.com", rating: 5, title: "I finally know my real profit", body: "I thought I was doing well because my account looked full. This showed me what I was actually making.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1306), course_id: seedId(311), user_id: null, normalized_email: "repeat.buyers@henryonyx.com", rating: 5, title: "Customers come back now", body: "The recovery and follow-up scripts turned a few complaints into my most loyal customers.", status: "published", created_at: createdAt, updated_at: updatedAt },
];
const assignments: Array<Record<string, unknown>> = [
  { id: seedId(1401), course_id: seedId(303), path_id: seedId(1102), user_id: null, normalized_email: "care.ops@henryonyx.com", assignee_role: "care_staff", assigned_by_user_id: null, sponsor_name: "Henry Onyx Fabric Care", note: "Required for all new care staff within the first two weeks.", required: true, due_at: "2026-04-16T18:00:00.000Z", assigned_at: createdAt, status: "assigned" },
  { id: seedId(1402), course_id: seedId(305), path_id: seedId(1103), user_id: null, normalized_email: "fleet.leads@henryonyx.com", assignee_role: "logistics_lead", assigned_by_user_id: null, sponsor_name: "Henry Onyx Logistics", note: "Required before moving into independent dispatch coverage.", required: true, due_at: "2026-04-18T18:00:00.000Z", assigned_at: createdAt, status: "assigned" },
];
const settings: Array<Record<string, unknown>> = [
  { id: seedId(1501), key: "bootstrap_version", value: { version: LEARN_BOOTSTRAP_VERSION }, created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1502), key: "academy_support", value: { email: learn.supportEmail, phone: learn.supportPhone, hours: "Mon-Fri 9:00-18:00 WAT" }, created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1503), key: "academy_banner", value: { title: "New courses are live.", body: "Sell on WhatsApp & Instagram, price for profit, keep clean books, and build a brand that brings buyers — plus marketplace certification and internal readiness, all in one premium academy." }, created_at: createdAt, updated_at: updatedAt },
];
const roleMemberships: Array<Record<string, unknown>> = [
  { id: seedId(1601), user_id: null, normalized_email: "academy@henryonyx.com", scope_type: "platform", scope_id: null, role: "academy_owner", is_active: true, created_at: createdAt, updated_at: updatedAt },
];

export async function seedLearnBaseline(meta?: LearnUpsertMeta) {
  await syncLearnDivision();

  for (const category of categories) await upsertLearnRecord("learn_course_categories", category, meta);
  for (const instructor of instructors) await upsertLearnRecord("learn_instructors", instructor, meta);
  for (const plan of plans) await upsertLearnRecord("learn_plans", plan, meta);

  for (const course of courseBlueprints) {
    const item = course as Record<string, unknown>;
    await upsertLearnRecord(
      "learn_courses",
      {
        id: item.id,
        slug: item.slug,
        category_id: item.category_id,
        primary_instructor_id: item.primary_instructor_id,
        title: item.title,
        subtitle: item.subtitle,
        summary: item.summary,
        description: item.description,
        hero_image_url: null,
        preview_video_url: null,
        duration_text: item.duration_text,
        estimated_minutes: item.estimated_minutes,
        difficulty: item.difficulty,
        prerequisites: item.prerequisites,
        outcomes: item.outcomes,
        tags: item.tags,
        visibility: item.visibility,
        access_model: item.access_model,
        plan_id: item.plan_id,
        price: item.price,
        currency: item.currency,
        featured: item.featured,
        is_certification: item.is_certification,
        passing_score: item.passing_score,
        completion_rule: item.completion_rule,
        status: item.status,
        created_at: createdAt,
        updated_at: updatedAt,
      },
      meta
    );

    const modules = (item.modules ?? []) as Array<Record<string, unknown>>;
    for (const [moduleIndex, module] of modules.entries()) {
      await upsertLearnRecord(
        "learn_modules",
        {
          id: module.id,
          course_id: item.id,
          title: module.title,
          summary: module.summary,
          sort_order: moduleIndex + 1,
          unlock_rule: module.unlock_rule,
          estimated_minutes: module.estimated_minutes,
          created_at: createdAt,
          updated_at: updatedAt,
        },
        meta
      );

      const lesson = (module.lesson ?? {}) as Record<string, unknown>;
      await upsertLearnRecord(
        "learn_lessons",
        {
          id: lesson.id,
          course_id: item.id,
          module_id: module.id,
          slug: lesson.slug,
          title: lesson.title,
          summary: lesson.summary,
          body_markdown: lesson.body_markdown,
          video_url: null,
          duration_minutes: lesson.duration_minutes,
          lesson_type: lesson.lesson_type,
          is_preview: lesson.is_preview,
          sort_order: 1,
          created_at: createdAt,
          updated_at: updatedAt,
        },
        meta
      );

      const resources = (lesson.resources ?? []) as Array<Record<string, unknown>>;
      for (const resource of resources) {
        await upsertLearnRecord(
          "learn_lesson_resources",
          {
            id: resource.id,
            lesson_id: lesson.id,
            label: resource.label,
            resource_type: resource.resource_type,
            url: resource.url,
            created_at: createdAt,
          },
          meta
        );
      }
    }

    const quiz = (item.quiz ?? {}) as Record<string, unknown>;
    const finalLessonId = ((modules.at(-1)?.lesson ?? {}) as Record<string, unknown>).id ?? null;
    await upsertLearnRecord(
      "learn_quizzes",
      {
        id: quiz.id,
        course_id: item.id,
        lesson_id: finalLessonId,
        title: quiz.title,
        description: quiz.description,
        pass_score: quiz.pass_score,
        max_attempts: quiz.max_attempts,
        question_count: Array.isArray(quiz.questions) ? quiz.questions.length : 0,
        created_at: createdAt,
        updated_at: updatedAt,
      },
      meta
    );

    const questions = (quiz.questions ?? []) as Array<Record<string, unknown>>;
    for (const [questionIndex, question] of questions.entries()) {
      await upsertLearnRecord(
        "learn_quiz_questions",
        {
          id: question.id,
          quiz_id: quiz.id,
          prompt: question.prompt,
          question_type: "single_choice",
          options: question.options,
          correct_answer: question.correct_answer,
          explanation: question.explanation,
          sort_order: questionIndex + 1,
          created_at: createdAt,
        },
        meta
      );
    }
  }

  const courseBySlug = new Map(
    courseBlueprints.map((course) => {
      const item = course as Record<string, unknown>;
      return [String(item.slug), String(item.id)];
    })
  );

  for (const path of paths) {
    const item = path as Record<string, unknown>;
    await upsertLearnRecord(
      "learn_learning_paths",
      {
        id: item.id,
        slug: item.slug,
        title: item.title,
        summary: item.summary,
        description: item.description,
        hero_image_url: item.hero_image_url,
        audience: item.audience,
        visibility: item.visibility,
        access_model: item.access_model,
        plan_id: item.plan_id,
        featured: item.featured,
        status: item.status,
        created_at: item.created_at,
        updated_at: item.updated_at,
      },
      meta
    );

    const items = (item.items ?? []) as Array<Record<string, unknown>>;
    for (const pathItem of items) {
      await upsertLearnRecord(
        "learn_path_items",
        {
          id: pathItem.id,
          path_id: item.id,
          item_type: pathItem.item_type,
          course_id: courseBySlug.get(String(pathItem.course_slug)) ?? null,
          label: pathItem.label,
          description: pathItem.description,
          sort_order: pathItem.sort_order,
          required: pathItem.required,
          created_at: createdAt,
        },
        meta
      );
    }
  }

  for (const review of reviews) await upsertLearnRecord("learn_reviews", review, meta);
  for (const assignment of assignments) await upsertLearnRecord("learn_assignments", assignment, meta);
  for (const setting of settings) {
    await upsertLearnRecord("learn_settings", setting, meta, { onConflict: "key", idKey: "key" });
  }
  for (const membership of roleMemberships) {
    await upsertLearnRecord("learn_role_memberships", membership, meta);
  }

  return {
    categoryCount: categories.length,
    courseCount: courseBlueprints.length,
    pathCount: paths.length,
    assignmentCount: assignments.length,
  };
}
