import { getDivisionConfig } from "@henryco/config";
import { upsertLearnRecord, type LearnUpsertMeta, syncLearnDivision } from "@/lib/learn/store";

export const LEARN_BOOTSTRAP_VERSION = "2026-04-02-academy-v1";

export function seedId(value: number) {
  return `00000000-0000-4000-8000-${String(value).padStart(12, "0")}`;
}

export const createdAt = "2026-04-02T18:00:00.000Z";
export const updatedAt = "2026-04-02T18:00:00.000Z";
export const learn = getDivisionConfig("learn");

export const categoryIds = {
  marketplace: seedId(101),
  internalOps: seedId(102),
  leadership: seedId(103),
  digital: seedId(104),
  onboarding: seedId(105),
};

export const instructorIds = {
  ada: seedId(201),
  chika: seedId(202),
  tobi: seedId(203),
  grace: seedId(204),
  emeka: seedId(205),
};

export const planIds = {
  free: seedId(251),
  sellerCert: seedId(252),
  academyPro: seedId(253),
  internal: seedId(254),
};

const categories: Array<Record<string, unknown>> = [
  {
    id: categoryIds.marketplace,
    slug: "marketplace-academy",
    name: "Marketplace Academy",
    description: "Seller education, trust systems, and vendor certification.",
    hero_copy: "Teach vendors how to launch cleanly, earn trust, and grow responsibly.",
    accent: "#8F6A2E",
    icon: "Store",
    is_featured: true,
    sort_order: 1,
    course_count: 0,
    audience_tags: ["vendors", "sellers", "marketplace teams"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.internalOps,
    slug: "internal-operations",
    name: "Internal Operations",
    description: "Assigned internal training for service and logistics teams.",
    hero_copy: "Build reliable internal teams through calm, accountable training systems.",
    accent: learn.accent,
    icon: "ShieldCheck",
    is_featured: true,
    sort_order: 2,
    course_count: 0,
    audience_tags: ["staff", "ops", "internal teams"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.leadership,
    slug: "manager-academy",
    name: "Manager Academy",
    description: "Team leadership, escalation judgment, and support management.",
    hero_copy: "Train leads and managers to intervene earlier and coach with more clarity.",
    accent: "#4E6D8C",
    icon: "BriefcaseBusiness",
    is_featured: true,
    sort_order: 3,
    course_count: 0,
    audience_tags: ["managers", "support leads", "owners"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.digital,
    slug: "business-growth",
    name: "Business Growth",
    description: "Premium growth, systems thinking, positioning, and capability building.",
    hero_copy: "Help founders and operators grow with less chaos and better leverage.",
    accent: "#835C9A",
    icon: "TrendingUp",
    is_featured: true,
    sort_order: 4,
    course_count: 0,
    audience_tags: ["founders", "operators", "public learners"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: categoryIds.onboarding,
    slug: "client-onboarding",
    name: "Client Onboarding",
    description: "Help clients understand how HenryCo services, milestones, and support flows work.",
    hero_copy: "Turn onboarding into confidence instead of confusion.",
    accent: "#557D68",
    icon: "Compass",
    is_featured: false,
    sort_order: 5,
    course_count: 0,
    audience_tags: ["clients", "partners", "new customers"],
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

const instructors: Array<Record<string, unknown>> = [
  {
    id: instructorIds.ada,
    slug: "ada-henry",
    full_name: "Ada Henry",
    title: "Academy Product Lead",
    bio: "Ada leads HenryCo learning strategy across public academy programs, partner enablement, and structured growth education.",
    expertise: ["academy strategy", "seller education", "offer design"],
    accent: learn.accent,
    avatar_url: null,
    spotlight_quote: "Premium learning feels calm, precise, and deeply actionable.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.chika,
    slug: "chika-okafor",
    full_name: "Chika Okafor",
    title: "Support Operations Director",
    bio: "Chika trains HenryCo team leads on escalation systems, service recovery, and manager intervention design.",
    expertise: ["support management", "team coaching", "escalations"],
    accent: "#4E6D8C",
    avatar_url: null,
    spotlight_quote: "Good support leadership removes panic before it spreads.",
    rating: 4.8,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.tobi,
    slug: "tobi-nwosu",
    full_name: "Tobi Nwosu",
    title: "Logistics Systems Lead",
    bio: "Tobi runs operational training for dispatch, riders, and proof-of-delivery readiness.",
    expertise: ["logistics", "dispatch", "proof of delivery"],
    accent: "#D06F32",
    avatar_url: null,
    spotlight_quote: "Reliable dispatch is a communication system before it is a speed system.",
    rating: 4.8,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.grace,
    slug: "grace-yusuf",
    full_name: "Grace Yusuf",
    title: "Customer Experience Lead",
    bio: "Grace focuses on premium service rituals, onboarding clarity, and customer trust through smoother operations.",
    expertise: ["customer experience", "service quality", "client onboarding"],
    accent: "#557D68",
    avatar_url: null,
    spotlight_quote: "The best onboarding lowers stress before questions start piling up.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: instructorIds.emeka,
    slug: "emeka-odili",
    full_name: "Emeka Odili",
    title: "Vendor Trust Director",
    bio: "Emeka leads seller trust, moderation quality, and vendor certification systems inside HenryCo Marketplace.",
    expertise: ["vendor trust", "moderation", "dispute prevention"],
    accent: "#8F6A2E",
    avatar_url: null,
    spotlight_quote: "Trust is earned through routine discipline, not a single polished moment.",
    rating: 4.9,
    created_at: createdAt,
    updated_at: updatedAt,
  },
];

const plans: Array<Record<string, unknown>> = [
  {
    id: planIds.free,
    slug: "academy-free",
    name: "Academy Free",
    description: "Open-access starter learning for public discovery and onboarding tracks.",
    price: 0,
    currency: "NGN",
    billing_type: "one_time",
    access_scope: "selected public courses",
    perks: ["Free enrollment", "Public onboarding tracks", "Progress dashboard"],
    is_public: true,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: planIds.sellerCert,
    slug: "seller-certification",
    name: "Seller Certification",
    description: "Certification-grade training for vendors who want HenryCo-recognized trust status.",
    price: 95000,
    currency: "NGN",
    billing_type: "one_time",
    access_scope: "certification courses",
    perks: ["Certification exam", "Downloadable certificate", "Verification-ready completion record"],
    is_public: true,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: planIds.academyPro,
    slug: "academy-pro",
    name: "Academy Pro",
    description: "Premium business education for operators, founders, and service teams.",
    price: 125000,
    currency: "NGN",
    billing_type: "one_time",
    access_scope: "advanced business programs",
    perks: ["Premium growth tracks", "Downloadable workbooks", "Completion certificate"],
    is_public: true,
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: planIds.internal,
    slug: "internal-sponsored",
    name: "Internal Sponsored",
    description: "Company-sponsored access for HenryCo internal teams, onboarding, and compliance.",
    price: 0,
    currency: "NGN",
    billing_type: "internal",
    access_scope: "internal assignments",
    perks: ["Assigned training", "Completion monitoring", "Internal certification"],
    is_public: false,
    created_at: createdAt,
    updated_at: updatedAt,
  },
];
const courseBlueprints: Array<Record<string, unknown>> = [
  {
    id: seedId(301),
    slug: "marketplace-seller-launch",
    category_id: categoryIds.marketplace,
    primary_instructor_id: instructorIds.ada,
    title: "Marketplace Seller Launch",
    subtitle: "Get a HenryCo marketplace store confidently ready for day-one trust.",
    summary: "A premium starter course covering storefront setup, trust signals, and first-publish readiness.",
    description: "Marketplace Seller Launch gives vendors the calm, trust-first foundation needed before their first HenryCo sale.",
    duration_text: "2h 05m",
    estimated_minutes: 125,
    difficulty: "beginner",
    prerequisites: ["Basic product catalog prepared"],
    outcomes: ["Launch with a trust-first storefront structure", "Prepare seller operations before taking orders"],
    tags: ["seller", "launch", "marketplace", "trust"],
    visibility: "public",
    access_model: "free",
    plan_id: planIds.free,
    price: 0,
    currency: "NGN",
    featured: true,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Complete both modules and pass the readiness quiz.",
    status: "published",
    modules: [
      {
        id: seedId(401),
        title: "Storefront Foundations",
        summary: "Clarify promise, trust edge, and buyer confidence.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(501),
          slug: "store-promise",
          title: "Define the Store Promise Before Publishing",
          summary: "Strong sellers launch around clarity, not noise.",
          body_markdown: "## Store promise\n\nClarify who the store is for, what it promises, and why buyers should trust it before products go live.",
          duration_minutes: 28,
          lesson_type: "video",
          is_preview: true,
          resources: [
            {
              id: seedId(801),
              label: "Store positioning worksheet",
              resource_type: "worksheet",
              url: "https://example.com/learn/store-positioning.pdf",
            },
          ],
        },
      },
      {
        id: seedId(402),
        title: "Publish Readiness",
        summary: "Check listing quality and fulfillment confidence.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(502),
          slug: "publish-readiness",
          title: "Quality Control Before First Publish",
          summary: "Reduce moderation loops by publishing cleanly.",
          body_markdown: "## Publish readiness\n\nUse listing quality, fulfillment notes, and support clarity to protect trust before launch.",
          duration_minutes: 31,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(802),
              label: "Listing quality checklist",
              resource_type: "checklist",
              url: "https://example.com/learn/listing-quality.pdf",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(901),
      title: "Seller launch readiness quiz",
      description: "Check whether the store is truly ready for first publish.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1001),
          prompt: "What should be clarified before the first product upload?",
          options: ["Store promise and buyer fit", "Holiday campaign copy", "A second warehouse"],
          correct_answer: ["Store promise and buyer fit"],
          explanation: "Trust begins with clarity.",
        },
        {
          id: seedId(1002),
          prompt: "What reduces moderation loops?",
          options: ["Clean listing quality", "More emojis", "Longer titles"],
          correct_answer: ["Clean listing quality"],
          explanation: "Prepared listings move through review faster.",
        },
      ],
    },
  },
  {
    id: seedId(302),
    slug: "verified-seller-certification",
    category_id: categoryIds.marketplace,
    primary_instructor_id: instructorIds.emeka,
    title: "Verified Seller Certification",
    subtitle: "Earn the operations-grade certification HenryCo uses to recognize reliable vendors.",
    summary: "A deeper seller certification covering trust operations, dispute prevention, and recovery handling.",
    description: "Verified Seller Certification focuses on repeatable reliability, stronger recovery routines, and public-facing trust.",
    duration_text: "3h 15m",
    estimated_minutes: 195,
    difficulty: "advanced",
    prerequisites: ["Marketplace Seller Launch completed"],
    outcomes: ["Understand the scorecard behind seller trust", "Qualify for a public-facing HenryCo certification layer"],
    tags: ["seller", "certification", "vendor", "trust"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.sellerCert,
    price: 95000,
    currency: "NGN",
    featured: true,
    is_certification: true,
    passing_score: 80,
    completion_rule: "Complete modules and pass the certification exam.",
    status: "published",
    modules: [
      {
        id: seedId(403),
        title: "Trust Operations",
        summary: "Decode the signals HenryCo tracks.",
        unlock_rule: "sequential",
        estimated_minutes: 95,
        lesson: {
          id: seedId(503),
          slug: "trust-operations",
          title: "How Trust Scores Are Earned",
          summary: "Certification depends on repeatable execution, not a one-time review.",
          body_markdown: "## Trust operations\n\nLearn the signals HenryCo tracks and how those signals shape seller visibility.",
          duration_minutes: 39,
          lesson_type: "video",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(404),
        title: "Issue Recovery",
        summary: "Reduce disputes and recover credibility after a miss.",
        unlock_rule: "sequential",
        estimated_minutes: 100,
        lesson: {
          id: seedId(504),
          slug: "issue-recovery",
          title: "Recover Trust After a Service Failure",
          summary: "Ownership and clarity matter more than defensiveness.",
          body_markdown: "## Issue recovery\n\nCertified sellers know how to respond clearly, take ownership, and protect future trust after a miss.",
          duration_minutes: 34,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(803),
              label: "Dispute prevention playbook",
              resource_type: "guide",
              url: "https://example.com/learn/dispute-prevention.pdf",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(902),
      title: "Seller certification exam",
      description: "Measure operational judgment needed for verified-seller status.",
      pass_score: 80,
      max_attempts: 3,
      questions: [
        {
          id: seedId(1003),
          prompt: "What sustains trust over time?",
          options: ["Repeatable execution", "A single campaign", "Lower price alone"],
          correct_answer: ["Repeatable execution"],
          explanation: "Certification reflects repeatable reliability.",
        },
        {
          id: seedId(1004),
          prompt: "What protects recovery after a miss?",
          options: ["Fast ownership and clear next steps", "Silence", "Blame shifting"],
          correct_answer: ["Fast ownership and clear next steps"],
          explanation: "Ownership and clarity rebuild trust faster.",
        },
      ],
    },
  },
  {
    id: seedId(303),
    slug: "care-service-excellence",
    category_id: categoryIds.internalOps,
    primary_instructor_id: instructorIds.grace,
    title: "Care Service Excellence",
    subtitle: "Internal training for pickup, garment care, customer handling, and premium service discipline.",
    summary: "A HenryCo internal track for care staff who must deliver premium service quality across pickup and handoff moments.",
    description: "Care Service Excellence trains internal care staff on service rituals, quality control, and recovery handling.",
    duration_text: "2h 10m",
    estimated_minutes: 130,
    difficulty: "intermediate",
    prerequisites: ["HenryCo staff account"],
    outcomes: ["Deliver premium service rituals consistently", "Reduce avoidable quality-control lapses"],
    tags: ["internal", "care", "service", "compliance"],
    visibility: "internal",
    access_model: "sponsored",
    plan_id: planIds.internal,
    price: 0,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 80,
    completion_rule: "Assigned staff must finish all lessons and pass the assessment.",
    status: "published",
    modules: [
      {
        id: seedId(405),
        title: "Premium Service Rituals",
        summary: "Deliver calm, premium interactions from intake through handoff.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(505),
          slug: "intake-standard",
          title: "Intake Standard and Customer Assurance",
          summary: "Create trust at the counter and during pickup.",
          body_markdown: "## Intake standard\n\nA premium service experience starts at intake with clarity, confidence, and accurate capture of details.",
          duration_minutes: 26,
          lesson_type: "reading",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(406),
        title: "Quality Control and Recovery",
        summary: "Catch issues early and recover service confidence when exceptions happen.",
        unlock_rule: "sequential",
        estimated_minutes: 65,
        lesson: {
          id: seedId(506),
          slug: "service-recovery",
          title: "Service Recovery for Premium Brands",
          summary: "Recover credibility quickly after a miss.",
          body_markdown: "## Service recovery\n\nPremium teams recover by acting early, communicating clearly, and preserving customer dignity.",
          duration_minutes: 24,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(804),
              label: "Service recovery framework",
              resource_type: "guide",
              url: "https://example.com/learn/service-recovery.pdf",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(903),
      title: "Care service excellence assessment",
      description: "Confirm internal service readiness for care staff.",
      pass_score: 80,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1005),
          prompt: "Where does premium service confidence begin?",
          options: ["At intake", "After dispatch", "Only after payment"],
          correct_answer: ["At intake"],
          explanation: "Confidence starts when the customer first hands over responsibility.",
        },
        {
          id: seedId(1006),
          prompt: "What is central to premium recovery?",
          options: ["Early ownership", "Silence", "Blame shifting"],
          correct_answer: ["Early ownership"],
          explanation: "Clear ownership rebuilds trust faster.",
        },
      ],
    },
  },
  {
    id: seedId(304),
    slug: "support-manager-academy",
    category_id: categoryIds.leadership,
    primary_instructor_id: instructorIds.chika,
    title: "Support Manager Academy",
    subtitle: "Lead service, escalations, and team coaching without operational drift.",
    summary: "An internal training program for managers and support leads who handle escalations, coaching, and service-level decisions.",
    description: "Support Manager Academy equips HenryCo team leads and support managers with escalation judgment, coaching rhythms, and visibility practices.",
    duration_text: "2h 30m",
    estimated_minutes: 150,
    difficulty: "advanced",
    prerequisites: ["HenryCo manager or support-lead assignment"],
    outcomes: ["Handle escalations with better judgment", "Improve visibility and intervention timing"],
    tags: ["internal", "leadership", "support", "manager"],
    visibility: "internal",
    access_model: "sponsored",
    plan_id: planIds.internal,
    price: 0,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 85,
    completion_rule: "Finish the academy and pass the manager decision assessment.",
    status: "published",
    modules: [
      {
        id: seedId(407),
        title: "Escalation Judgment",
        summary: "Decide quickly and cleanly when service risk increases.",
        unlock_rule: "sequential",
        estimated_minutes: 75,
        lesson: {
          id: seedId(507),
          slug: "escalation-triggers",
          title: "Escalation Triggers That Matter",
          summary: "Recognize when a manager must step in before customer trust erodes.",
          body_markdown: "## Escalation triggers\n\nManagers add value when they intervene at the right threshold, not after chaos is visible to everyone.",
          duration_minutes: 28,
          lesson_type: "reading",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(408),
        title: "Coaching and Visibility",
        summary: "Use manager routines that lift the whole support system.",
        unlock_rule: "sequential",
        estimated_minutes: 75,
        lesson: {
          id: seedId(508),
          slug: "visibility-boards",
          title: "Visibility Boards and Intervention Signals",
          summary: "See risk earlier and intervene with less friction.",
          body_markdown: "## Visibility boards\n\nThe best service environments make risk visible before it becomes expensive.",
          duration_minutes: 26,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(805),
              label: "Manager intervention tracker",
              resource_type: "template",
              url: "https://example.com/learn/intervention-tracker.xlsx",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(904),
      title: "Manager decision assessment",
      description: "Evaluate escalation and coaching judgment.",
      pass_score: 85,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1007),
          prompt: "When should a manager intervene?",
          options: ["At the right risk threshold", "Only after a complaint explodes", "Never if the queue is busy"],
          correct_answer: ["At the right risk threshold"],
          explanation: "Intervening at the correct threshold prevents avoidable trust damage.",
        },
        {
          id: seedId(1008),
          prompt: "Why do visibility boards matter?",
          options: ["They surface risk earlier", "They replace service teams", "They remove accountability"],
          correct_answer: ["They surface risk earlier"],
          explanation: "Visibility shortens intervention time.",
        },
      ],
    },
  },
  {
    id: seedId(305),
    slug: "logistics-rider-readiness",
    category_id: categoryIds.internalOps,
    primary_instructor_id: instructorIds.tobi,
    title: "Logistics Rider Readiness",
    subtitle: "Dispatch safely, communicate clearly, and execute reliable proof-of-delivery routines.",
    summary: "An internal rider training program focused on dispatch readiness, customer handling, and delivery proof discipline.",
    description: "Logistics Rider Readiness supports HenryCo Logistics teams with dispatch, safety, and proof-of-delivery standards.",
    duration_text: "1h 55m",
    estimated_minutes: 115,
    difficulty: "intermediate",
    prerequisites: ["Internal rider or fleet-team assignment"],
    outcomes: ["Improve proof-of-delivery accuracy", "Reduce avoidable route incidents and trust failures"],
    tags: ["internal", "logistics", "dispatch", "rider"],
    visibility: "internal",
    access_model: "sponsored",
    plan_id: planIds.internal,
    price: 0,
    currency: "NGN",
    featured: false,
    is_certification: true,
    passing_score: 80,
    completion_rule: "Complete all rider readiness lessons and pass the dispatch exam.",
    status: "published",
    modules: [
      {
        id: seedId(409),
        title: "Dispatch Reliability",
        summary: "Handle pickup and route communication with more control.",
        unlock_rule: "sequential",
        estimated_minutes: 55,
        lesson: {
          id: seedId(509),
          slug: "dispatch-communication",
          title: "Dispatch Communication Standards",
          summary: "Use calm updates and better expectation-setting during active runs.",
          body_markdown: "## Dispatch communication\n\nBuyers and senders trust what they can understand. Dispatch updates must be early, clear, and aligned with actual route conditions.",
          duration_minutes: 22,
          lesson_type: "reading",
          is_preview: false,
          resources: [],
        },
      },
      {
        id: seedId(410),
        title: "Proof and Safety Discipline",
        summary: "Strengthen delivery proof and incident prevention.",
        unlock_rule: "sequential",
        estimated_minutes: 60,
        lesson: {
          id: seedId(510),
          slug: "proof-of-delivery",
          title: "Proof-of-Delivery Discipline",
          summary: "Capture proof cleanly, accurately, and consistently.",
          body_markdown: "## Proof discipline\n\nProof-of-delivery protects operations, finance, support, and customer trust. Weak proof creates friction everywhere else.",
          duration_minutes: 24,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(806),
              label: "Incident report template",
              resource_type: "template",
              url: "https://example.com/learn/incident-template.docx",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(905),
      title: "Dispatch readiness exam",
      description: "Validate rider readiness and route judgment.",
      pass_score: 80,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1009),
          prompt: "What makes dispatch updates trustworthy?",
          options: ["Clarity aligned with real route conditions", "Frequent guessing", "Late updates only"],
          correct_answer: ["Clarity aligned with real route conditions"],
          explanation: "Accuracy and timing matter more than volume.",
        },
        {
          id: seedId(1010),
          prompt: "Why does proof-of-delivery matter?",
          options: ["It protects multiple teams and trust", "It is optional", "It only helps finance"],
          correct_answer: ["It protects multiple teams and trust"],
          explanation: "Proof quality reduces downstream friction.",
        },
      ],
    },
  },
  {
    id: seedId(306),
    slug: "business-growth-foundations",
    category_id: categoryIds.digital,
    primary_instructor_id: instructorIds.ada,
    title: "Business Growth Foundations",
    subtitle: "Clarify positioning, offers, and operations before growth compounds the wrong system.",
    summary: "A premium public course for service businesses that want sharper positioning, stronger offers, and calmer growth systems.",
    description: "Business Growth Foundations helps service founders and operators improve positioning, delivery clarity, and growth systems before scaling.",
    duration_text: "2h 25m",
    estimated_minutes: 145,
    difficulty: "intermediate",
    prerequisites: ["An active service or product offer"],
    outcomes: ["Sharpen business positioning and offer structure", "Build a clearer path from lead to delivery"],
    tags: ["business", "growth", "founder", "offer"],
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    price: 125000,
    currency: "NGN",
    featured: true,
    is_certification: true,
    passing_score: 75,
    completion_rule: "Complete all lessons and pass the business growth assessment.",
    status: "published",
    modules: [
      {
        id: seedId(411),
        title: "Positioning and Offer Design",
        summary: "Define what you sell, for whom, and why the market should trust it.",
        unlock_rule: "sequential",
        estimated_minutes: 70,
        lesson: {
          id: seedId(511),
          slug: "offer-clarity",
          title: "Offer Clarity Before Promotion",
          summary: "Make the offer easier to buy before spending to attract attention.",
          body_markdown: "## Offer clarity\n\nGrowth gets expensive when the offer itself is fuzzy. Simplify what you sell, who it is for, and how it creates confidence.",
          duration_minutes: 29,
          lesson_type: "video",
          is_preview: true,
          resources: [],
        },
      },
      {
        id: seedId(412),
        title: "Growth Systems and Delivery",
        summary: "Align marketing ambition with delivery discipline.",
        unlock_rule: "sequential",
        estimated_minutes: 75,
        lesson: {
          id: seedId(512),
          slug: "growth-bottlenecks",
          title: "Find the Bottleneck Before You Scale",
          summary: "Spot the real constraint that will break first under growth.",
          body_markdown: "## Growth bottlenecks\n\nMost growth problems are delivery problems disguised as marketing ambition. Fix the system before increasing volume.",
          duration_minutes: 31,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(807),
              label: "Growth bottleneck worksheet",
              resource_type: "worksheet",
              url: "https://example.com/learn/growth-bottleneck.pdf",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(906),
      title: "Business growth assessment",
      description: "Measure readiness to grow without operational drift.",
      pass_score: 75,
      max_attempts: 4,
      questions: [
        {
          id: seedId(1011),
          prompt: "What makes growth expensive too early?",
          options: ["A fuzzy offer", "A clearer promise", "Better fulfillment"],
          correct_answer: ["A fuzzy offer"],
          explanation: "Weak offer clarity wastes acquisition effort.",
        },
        {
          id: seedId(1012),
          prompt: "What often hides behind growth problems?",
          options: ["Delivery bottlenecks", "Too much clarity", "Excess trust"],
          correct_answer: ["Delivery bottlenecks"],
          explanation: "Operational friction often limits growth first.",
        },
      ],
    },
  },
  {
    id: seedId(307),
    slug: "henryco-client-onboarding",
    category_id: categoryIds.onboarding,
    primary_instructor_id: instructorIds.grace,
    title: "HenryCo Client Onboarding",
    subtitle: "Understand how HenryCo projects, requests, approvals, and support flows work from day one.",
    summary: "A free public onboarding track that helps new HenryCo clients understand process, communication, approvals, and support expectations.",
    description: "HenryCo Client Onboarding clarifies the operating model, milestone expectations, collaboration rituals, and support channels that keep projects calm.",
    duration_text: "1h 30m",
    estimated_minutes: 90,
    difficulty: "beginner",
    prerequisites: ["None"],
    outcomes: ["Understand HenryCo workflows faster", "Reduce avoidable friction during onboarding"],
    tags: ["onboarding", "client", "services", "process"],
    visibility: "public",
    access_model: "free",
    plan_id: planIds.free,
    price: 0,
    currency: "NGN",
    featured: true,
    is_certification: false,
    passing_score: 70,
    completion_rule: "Finish the onboarding lessons and complete the readiness check.",
    status: "published",
    modules: [
      {
        id: seedId(413),
        title: "How HenryCo Works",
        summary: "See the service lifecycle from request to delivery.",
        unlock_rule: "sequential",
        estimated_minutes: 45,
        lesson: {
          id: seedId(513),
          slug: "project-rhythm",
          title: "Project Rhythm and Milestones",
          summary: "Understand how HenryCo structures requests, milestones, and approvals.",
          body_markdown: "## Project rhythm\n\nClients move faster when they understand what happens next, who owns each step, and what approvals unlock progress.",
          duration_minutes: 19,
          lesson_type: "reading",
          is_preview: true,
          resources: [],
        },
      },
      {
        id: seedId(414),
        title: "Support and Handoffs",
        summary: "Know how support, revisions, and handoffs work cleanly.",
        unlock_rule: "sequential",
        estimated_minutes: 45,
        lesson: {
          id: seedId(514),
          slug: "support-escalation",
          title: "Support, Escalation, and Next-Step Clarity",
          summary: "Use the support system with less friction.",
          body_markdown: "## Support and escalation\n\nHenryCo support works best when requests are contextualized clearly and routed through the correct lane.",
          duration_minutes: 18,
          lesson_type: "reading",
          is_preview: false,
          resources: [
            {
              id: seedId(808),
              label: "Client onboarding checklist",
              resource_type: "checklist",
              url: "https://example.com/learn/client-onboarding-checklist.pdf",
            },
          ],
        },
      },
    ],
    quiz: {
      id: seedId(907),
      title: "Client onboarding readiness check",
      description: "Confirm the client understands the operating model.",
      pass_score: 70,
      max_attempts: 5,
      questions: [
        {
          id: seedId(1013),
          prompt: "What keeps project delivery calmer?",
          options: ["Clear ownership of next steps", "More disconnected channels", "Skipping approvals"],
          correct_answer: ["Clear ownership of next steps"],
          explanation: "Clarity lowers friction throughout the project.",
        },
        {
          id: seedId(1014),
          prompt: "How should support requests be handled?",
          options: ["Route them with context", "Send incomplete requests", "Escalate everything immediately"],
          correct_answer: ["Route them with context"],
          explanation: "Contextual requests are resolved faster.",
        },
      ],
    },
  },
];
const paths: Array<Record<string, unknown>> = [
  {
    id: seedId(1101),
    slug: "marketplace-seller-academy",
    title: "Marketplace Seller Academy",
    summary: "From first storefront clarity to verified seller trust.",
    description: "A structured academy path for new and growing vendors who want to launch well and earn trust inside HenryCo Marketplace.",
    hero_image_url: null,
    audience: "Public vendors and seller teams",
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.sellerCert,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1201), item_type: "course", course_slug: "marketplace-seller-launch", label: "Seller launch", description: "Build the storefront and trust basics first.", sort_order: 1, required: true },
      { id: seedId(1202), item_type: "course", course_slug: "verified-seller-certification", label: "Seller certification", description: "Move into the deeper certification layer.", sort_order: 2, required: true },
      { id: seedId(1203), item_type: "course", course_slug: "henryco-client-onboarding", label: "Platform onboarding", description: "Understand the wider HenryCo operating model.", sort_order: 3, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1102),
    slug: "care-staff-academy",
    title: "Care Staff Academy",
    summary: "Internal service quality, escalation readiness, and completion monitoring.",
    description: "This internal path combines service rituals and manager visibility for teams responsible for care quality and customer trust.",
    hero_image_url: null,
    audience: "Internal care and support teams",
    visibility: "internal",
    access_model: "internal",
    plan_id: planIds.internal,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1204), item_type: "course", course_slug: "care-service-excellence", label: "Service excellence", description: "Core quality and recovery training.", sort_order: 1, required: true },
      { id: seedId(1205), item_type: "course", course_slug: "support-manager-academy", label: "Manager escalation", description: "Required for leads and support managers.", sort_order: 2, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1103),
    slug: "logistics-readiness-track",
    title: "Logistics Readiness Track",
    summary: "Dispatch communication, rider proof, and manager response readiness.",
    description: "A HenryCo internal path that aligns rider execution with escalation management and support visibility.",
    hero_image_url: null,
    audience: "Internal logistics teams",
    visibility: "internal",
    access_model: "internal",
    plan_id: planIds.internal,
    featured: false,
    status: "published",
    items: [
      { id: seedId(1206), item_type: "course", course_slug: "logistics-rider-readiness", label: "Rider readiness", description: "Dispatch and proof-of-delivery discipline.", sort_order: 1, required: true },
      { id: seedId(1207), item_type: "course", course_slug: "support-manager-academy", label: "Escalation management", description: "Recommended for team leads and shift managers.", sort_order: 2, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
  {
    id: seedId(1104),
    slug: "business-growth-academy",
    title: "Business Growth Academy",
    summary: "Sharpen offers, reduce bottlenecks, and onboard clients more cleanly.",
    description: "A public academy track for operators and founders who want stronger growth systems and smoother onboarding outcomes.",
    hero_image_url: null,
    audience: "Founders, operators, and growth teams",
    visibility: "public",
    access_model: "paid",
    plan_id: planIds.academyPro,
    featured: true,
    status: "published",
    items: [
      { id: seedId(1208), item_type: "course", course_slug: "business-growth-foundations", label: "Growth foundations", description: "Positioning, offers, and bottlenecks.", sort_order: 1, required: true },
      { id: seedId(1209), item_type: "course", course_slug: "henryco-client-onboarding", label: "Client onboarding", description: "Create smoother onboarding and approval flows.", sort_order: 2, required: false },
    ],
    created_at: createdAt,
    updated_at: updatedAt,
  },
];
const reviews: Array<Record<string, unknown>> = [
  { id: seedId(1301), course_id: seedId(301), user_id: null, normalized_email: "vendor.launch@henrycogroup.com", rating: 5, title: "Sharper than most marketplace courses", body: "The course made our storefront feel intentional instead of rushed.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1302), course_id: seedId(306), user_id: null, normalized_email: "growth.operator@henrycogroup.com", rating: 5, title: "Clear growth thinking", body: "It made us fix the system behind growth before spending to scale.", status: "published", created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1303), course_id: seedId(307), user_id: null, normalized_email: "client.onboarding@henrycogroup.com", rating: 4, title: "Helpful before kickoff", body: "The onboarding course answered questions we usually ask weeks later.", status: "published", created_at: createdAt, updated_at: updatedAt },
];
const assignments: Array<Record<string, unknown>> = [
  { id: seedId(1401), course_id: seedId(303), path_id: seedId(1102), user_id: null, normalized_email: "care.ops@henrycogroup.com", assignee_role: "care_staff", assigned_by_user_id: null, sponsor_name: "HenryCo Fabric Care", note: "Required for all new care staff within the first two weeks.", required: true, due_at: "2026-04-16T18:00:00.000Z", assigned_at: createdAt, status: "assigned" },
  { id: seedId(1402), course_id: seedId(305), path_id: seedId(1103), user_id: null, normalized_email: "fleet.leads@henrycogroup.com", assignee_role: "logistics_lead", assigned_by_user_id: null, sponsor_name: "HenryCo Logistics", note: "Required before moving into independent dispatch coverage.", required: true, due_at: "2026-04-18T18:00:00.000Z", assigned_at: createdAt, status: "assigned" },
];
const settings: Array<Record<string, unknown>> = [
  { id: seedId(1501), key: "bootstrap_version", value: { version: LEARN_BOOTSTRAP_VERSION }, created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1502), key: "academy_support", value: { email: learn.supportEmail, phone: learn.supportPhone, hours: "Mon-Fri 9:00-18:00 WAT" }, created_at: createdAt, updated_at: updatedAt },
  { id: seedId(1503), key: "academy_banner", value: { title: "New academy tracks are live.", body: "Marketplace certification, business growth, and internal readiness paths now share one premium academy experience." }, created_at: createdAt, updated_at: updatedAt },
];
const roleMemberships: Array<Record<string, unknown>> = [
  { id: seedId(1601), user_id: null, normalized_email: "academy@henrycogroup.com", scope_type: "platform", scope_id: null, role: "academy_owner", is_active: true, created_at: createdAt, updated_at: updatedAt },
];

export async function seedLearnBaseline(meta?: LearnUpsertMeta) {
  await syncLearnDivision();

  for (const category of categories) await upsertLearnRecord("learn_course_categories", category, meta);
  for (const instructor of instructors) await upsertLearnRecord("learn_instructors", instructor, meta);
  for (const plan of plans) await upsertLearnRecord("learn_plans", plan, meta);

  for (const course of courseBlueprints) {
    const item = course as Record<string, unknown>;
    await upsertLearnRecord(
      "learn_courses",
      {
        id: item.id,
        slug: item.slug,
        category_id: item.category_id,
        primary_instructor_id: item.primary_instructor_id,
        title: item.title,
        subtitle: item.subtitle,
        summary: item.summary,
        description: item.description,
        hero_image_url: null,
        preview_video_url: null,
        duration_text: item.duration_text,
        estimated_minutes: item.estimated_minutes,
        difficulty: item.difficulty,
        prerequisites: item.prerequisites,
        outcomes: item.outcomes,
        tags: item.tags,
        visibility: item.visibility,
        access_model: item.access_model,
        plan_id: item.plan_id,
        price: item.price,
        currency: item.currency,
        featured: item.featured,
        is_certification: item.is_certification,
        passing_score: item.passing_score,
        completion_rule: item.completion_rule,
        status: item.status,
        created_at: createdAt,
        updated_at: updatedAt,
      },
      meta
    );

    const modules = (item.modules ?? []) as Array<Record<string, unknown>>;
    for (const [moduleIndex, module] of modules.entries()) {
      await upsertLearnRecord(
        "learn_modules",
        {
          id: module.id,
          course_id: item.id,
          title: module.title,
          summary: module.summary,
          sort_order: moduleIndex + 1,
          unlock_rule: module.unlock_rule,
          estimated_minutes: module.estimated_minutes,
          created_at: createdAt,
          updated_at: updatedAt,
        },
        meta
      );

      const lesson = (module.lesson ?? {}) as Record<string, unknown>;
      await upsertLearnRecord(
        "learn_lessons",
        {
          id: lesson.id,
          course_id: item.id,
          module_id: module.id,
          slug: lesson.slug,
          title: lesson.title,
          summary: lesson.summary,
          body_markdown: lesson.body_markdown,
          video_url: null,
          duration_minutes: lesson.duration_minutes,
          lesson_type: lesson.lesson_type,
          is_preview: lesson.is_preview,
          sort_order: 1,
          created_at: createdAt,
          updated_at: updatedAt,
        },
        meta
      );

      const resources = (lesson.resources ?? []) as Array<Record<string, unknown>>;
      for (const resource of resources) {
        await upsertLearnRecord(
          "learn_lesson_resources",
          {
            id: resource.id,
            lesson_id: lesson.id,
            label: resource.label,
            resource_type: resource.resource_type,
            url: resource.url,
            created_at: createdAt,
          },
          meta
        );
      }
    }

    const quiz = (item.quiz ?? {}) as Record<string, unknown>;
    const finalLessonId = ((modules.at(-1)?.lesson ?? {}) as Record<string, unknown>).id ?? null;
    await upsertLearnRecord(
      "learn_quizzes",
      {
        id: quiz.id,
        course_id: item.id,
        lesson_id: finalLessonId,
        title: quiz.title,
        description: quiz.description,
        pass_score: quiz.pass_score,
        max_attempts: quiz.max_attempts,
        question_count: Array.isArray(quiz.questions) ? quiz.questions.length : 0,
        created_at: createdAt,
        updated_at: updatedAt,
      },
      meta
    );

    const questions = (quiz.questions ?? []) as Array<Record<string, unknown>>;
    for (const [questionIndex, question] of questions.entries()) {
      await upsertLearnRecord(
        "learn_quiz_questions",
        {
          id: question.id,
          quiz_id: quiz.id,
          prompt: question.prompt,
          question_type: "single_choice",
          options: question.options,
          correct_answer: question.correct_answer,
          explanation: question.explanation,
          sort_order: questionIndex + 1,
          created_at: createdAt,
        },
        meta
      );
    }
  }

  const courseBySlug = new Map(
    courseBlueprints.map((course) => {
      const item = course as Record<string, unknown>;
      return [String(item.slug), String(item.id)];
    })
  );

  for (const path of paths) {
    const item = path as Record<string, unknown>;
    await upsertLearnRecord(
      "learn_learning_paths",
      {
        id: item.id,
        slug: item.slug,
        title: item.title,
        summary: item.summary,
        description: item.description,
        hero_image_url: item.hero_image_url,
        audience: item.audience,
        visibility: item.visibility,
        access_model: item.access_model,
        plan_id: item.plan_id,
        featured: item.featured,
        status: item.status,
        created_at: item.created_at,
        updated_at: item.updated_at,
      },
      meta
    );

    const items = (item.items ?? []) as Array<Record<string, unknown>>;
    for (const pathItem of items) {
      await upsertLearnRecord(
        "learn_path_items",
        {
          id: pathItem.id,
          path_id: item.id,
          item_type: pathItem.item_type,
          course_id: courseBySlug.get(String(pathItem.course_slug)) ?? null,
          label: pathItem.label,
          description: pathItem.description,
          sort_order: pathItem.sort_order,
          required: pathItem.required,
          created_at: createdAt,
        },
        meta
      );
    }
  }

  for (const review of reviews) await upsertLearnRecord("learn_reviews", review, meta);
  for (const assignment of assignments) await upsertLearnRecord("learn_assignments", assignment, meta);
  for (const setting of settings) {
    await upsertLearnRecord("learn_settings", setting, meta, { onConflict: "key", idKey: "key" });
  }
  for (const membership of roleMemberships) {
    await upsertLearnRecord("learn_role_memberships", membership, meta);
  }

  return {
    categoryCount: categories.length,
    courseCount: courseBlueprints.length,
    pathCount: paths.length,
    assignmentCount: assignments.length,
  };
}
