import "server-only";

import { getDivisionConfig, getDivisionUrl } from "@henryco/config";
import { createAdminSupabase } from "@/lib/supabase";

type DispatchStatus = "sent" | "queued" | "skipped" | "failed";

export type DispatchResult = {
  ok: boolean;
  status: DispatchStatus;
  reason: string | null;
  messageId: string | null;
};

type EmailTemplateInput = {
  key:
    | "application_submitted"
    | "application_received"
    | "shortlisted"
    | "rejected"
    | "interview_update"
    | "employer_verification"
    | "job_alert"
    | "recruiter_alert"
    | "internal_hiring_alert";
  heading: string;
  summary: string;
  detailLines?: string[];
  ctaLabel?: string | null;
  ctaHref?: string | null;
};

const jobs = getDivisionConfig("jobs");
const jobsBaseUrl = getDivisionUrl("jobs");

function cleanText(value?: string | null) {
  return String(value || "")
    .replace(/\r\n|\r|\n/g, "")
    .replace(/\\r\\n|\\r|\\n/g, "")
    .trim();
}

function extractEmail(value?: string | null) {
  const clean = cleanText(value).toLowerCase();
  const match = clean.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i);
  return match ? match[0] : null;
}

function normalizePhone(value?: string | null) {
  const raw = cleanText(value);
  if (!raw) return null;
  if (raw.startsWith("+")) return raw.replace(/[^\d+]/g, "");

  const digits = raw.replace(/\D+/g, "");
  if (!digits) return null;
  if (digits.startsWith("234")) return `+${digits}`;
  if (digits.startsWith("0") && digits.length === 11) return `+234${digits.slice(1)}`;
  if (digits.length >= 10) return `+${digits}`;
  return null;
}

function toAbsoluteJobsUrl(value?: string | null) {
  const clean = cleanText(value);
  if (!clean) return null;
  if (/^https?:\/\//i.test(clean)) return clean;
  return `${jobsBaseUrl}${clean.startsWith("/") ? clean : `/${clean}`}`;
}

function renderEmailTemplate(input: EmailTemplateInput) {
  const subjectMap: Record<EmailTemplateInput["key"], string> = {
    application_submitted: "Application received by HenryCo Jobs",
    application_received: "New application received",
    shortlisted: "You have been shortlisted",
    rejected: "Update on your application",
    interview_update: "Interview update",
    employer_verification: "Employer verification update",
    job_alert: "New jobs that match your alert",
    recruiter_alert: "Jobs platform queue alert",
    internal_hiring_alert: "Internal hiring alert",
  };

  const detailMarkup = (input.detailLines ?? [])
    .map((line) => `<li style="margin:0 0 8px 0;">${line}</li>`)
    .join("");

  return {
    subject: subjectMap[input.key],
    html: `
      <div style="background:#f2f7f7;padding:32px;font-family:Manrope,Segoe UI,Arial,sans-serif;color:#102124;">
        <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid rgba(16,33,36,0.08);border-radius:28px;overflow:hidden;box-shadow:0 28px 80px rgba(15,35,39,0.12);">
          <div style="padding:28px 32px;background:linear-gradient(135deg,#0d5e66 0%,#0e7c86 55%,#7fd0d4 100%);color:#f6ffff;">
            <div style="font-size:11px;letter-spacing:0.24em;text-transform:uppercase;font-weight:800;opacity:0.82;">HenryCo Jobs</div>
            <h1 style="margin:14px 0 0;font-family:Newsreader,Georgia,serif;font-size:36px;line-height:1;font-weight:600;">${input.heading}</h1>
          </div>
          <div style="padding:28px 32px;">
            <p style="margin:0 0 18px;font-size:15px;line-height:1.75;color:#30474b;">${input.summary}</p>
            ${detailMarkup ? `<ul style="margin:0 0 22px 18px;padding:0;font-size:14px;line-height:1.7;color:#30474b;">${detailMarkup}</ul>` : ""}
            ${
              input.ctaHref && input.ctaLabel
                ? `<a href="${input.ctaHref}" style="display:inline-block;padding:13px 20px;border-radius:999px;background:#0e7c86;color:#f6ffff;text-decoration:none;font-weight:700;box-shadow:0 16px 32px rgba(14,124,134,0.18);">${input.ctaLabel}</a>`
                : ""
            }
            <p style="margin:26px 0 0;font-size:13px;line-height:1.7;color:#5c6f72;">This message was generated by HenryCo Jobs, the HenryCo hiring and talent operating system.</p>
          </div>
        </div>
      </div>
    `,
    text: [input.heading, "", input.summary, ...(input.detailLines ?? []), input.ctaHref ? `${input.ctaLabel}: ${input.ctaHref}` : ""]
      .filter(Boolean)
      .join("\n"),
  };
}

async function logNotificationAudit(input: {
  actorId?: string | null;
  actorRole?: string | null;
  action: string;
  entityType?: string | null;
  entityId?: string | null;
  reason?: string | null;
  payload?: Record<string, unknown>;
}) {
  await createAdminSupabase().from("audit_logs").insert({
    actor_id: input.actorId ?? null,
    actor_role: input.actorRole ?? null,
    action: input.action,
    entity_type: input.entityType ?? "jobs_notification",
    entity_id: input.entityId ?? "jobs",
    reason: input.reason ?? null,
    new_values: input.payload ?? {},
  } as never);
}

export async function createJobsInAppNotification(input: {
  userId: string;
  title: string;
  body: string;
  actionUrl?: string | null;
  actionLabel?: string | null;
  priority?: string | null;
  referenceType?: string | null;
  referenceId?: string | null;
}) {
  const { data } = await createAdminSupabase()
    .from("customer_notifications")
    .insert({
      user_id: input.userId,
      title: input.title,
      body: input.body,
      category: "jobs",
      priority: input.priority ?? "normal",
      action_url: input.actionUrl ?? null,
      action_label: input.actionLabel ?? null,
      division: "jobs",
      reference_type: input.referenceType ?? null,
      reference_id: input.referenceId ?? null,
    } as never)
    .select("id")
    .maybeSingle();

  return data?.id ? String(data.id) : null;
}

export async function sendJobsEmail(
  to: string | null | undefined,
  template: EmailTemplateInput,
  options?: {
    actorId?: string | null;
    actorRole?: string | null;
    entityType?: string | null;
    entityId?: string | null;
  }
): Promise<DispatchResult> {
  const recipient = extractEmail(to);
  if (!recipient) {
    return {
      ok: false,
      status: "skipped",
      reason: "Recipient email is missing.",
      messageId: null,
    };
  }

  const resendKey = cleanText(process.env.RESEND_API_KEY);
  const from = cleanText(process.env.RESEND_FROM_EMAIL || process.env.RESEND_FROM) || `HenryCo Jobs <${jobs.supportEmail}>`;
  const rendered = renderEmailTemplate({
    ...template,
    ctaHref: toAbsoluteJobsUrl(template.ctaHref),
  });

  if (!resendKey) {
    await logNotificationAudit({
      actorId: options?.actorId,
      actorRole: options?.actorRole,
      action: "jobs_email_queued",
      entityType: options?.entityType,
      entityId: options?.entityId,
      reason: "RESEND_API_KEY is not configured.",
      payload: { to: recipient, template: template.key, subject: rendered.subject },
    });
    return {
      ok: false,
      status: "queued",
      reason: "RESEND_API_KEY is not configured.",
      messageId: null,
    };
  }

  const response = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${resendKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to: [recipient],
      subject: rendered.subject,
      html: rendered.html,
      text: rendered.text,
    }),
  });

  const payload = (await response.json().catch(() => null)) as { id?: string; message?: string } | null;
  const ok = response.ok && Boolean(payload?.id);

  await logNotificationAudit({
    actorId: options?.actorId,
    actorRole: options?.actorRole,
    action: ok ? "jobs_email_sent" : "jobs_email_failed",
    entityType: options?.entityType,
    entityId: options?.entityId,
    reason: ok ? null : payload?.message || `Resend rejected the email with status ${response.status}.`,
    payload: { to: recipient, template: template.key, subject: rendered.subject, resendId: payload?.id ?? null },
  });

  return {
    ok,
    status: ok ? "sent" : "failed",
    reason: ok ? null : payload?.message || `Resend rejected the email with status ${response.status}.`,
    messageId: payload?.id ?? null,
  };
}

export async function sendJobsWhatsApp(input: {
  phone?: string | null;
  body: string;
  actorId?: string | null;
  actorRole?: string | null;
  entityType?: string | null;
  entityId?: string | null;
}) {
  const normalizedPhone = normalizePhone(input.phone);
  if (!normalizedPhone) {
    return {
      ok: false,
      status: "skipped" as const,
      reason: "A valid phone number is not available for WhatsApp delivery.",
      messageId: null,
    };
  }

  const accessToken = cleanText(process.env.WHATSAPP_ACCESS_TOKEN);
  const phoneNumberId = cleanText(process.env.WHATSAPP_PHONE_NUMBER_ID);
  const businessAccountId = cleanText(process.env.WHATSAPP_BUSINESS_ACCOUNT_ID);

  if (!accessToken || !phoneNumberId || !businessAccountId) {
    await logNotificationAudit({
      actorId: input.actorId,
      actorRole: input.actorRole,
      action: "jobs_whatsapp_skipped",
      entityType: input.entityType,
      entityId: input.entityId,
      reason:
        "WhatsApp is not configured. Add WHATSAPP_ACCESS_TOKEN, WHATSAPP_PHONE_NUMBER_ID, and WHATSAPP_BUSINESS_ACCOUNT_ID.",
      payload: { phone: normalizedPhone },
    });
    return {
      ok: false,
      status: "skipped" as const,
      reason:
        "WhatsApp is not configured. Add WHATSAPP_ACCESS_TOKEN, WHATSAPP_PHONE_NUMBER_ID, and WHATSAPP_BUSINESS_ACCOUNT_ID.",
      messageId: null,
    };
  }

  const response = await fetch(`https://graph.facebook.com/v22.0/${phoneNumberId}/messages`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      messaging_product: "whatsapp",
      recipient_type: "individual",
      to: normalizedPhone.replace(/^\+/, ""),
      type: "text",
      text: {
        preview_url: false,
        body: input.body,
      },
    }),
  });

  const payload = (await response.json().catch(() => null)) as
    | { messages?: Array<{ id?: string }>; error?: { message?: string; code?: number } }
    | null;

  const messageId = payload?.messages?.[0]?.id ?? null;
  const ok = response.ok && Boolean(messageId);
  const reason =
    ok
      ? null
      : payload?.error?.message ||
        (response.status === 400
          ? "Meta rejected the WhatsApp request. If this was proactive outreach, the phone likely needs an approved template or an active 24-hour support window."
          : `Meta rejected the WhatsApp request with status ${response.status}.`);

  await logNotificationAudit({
    actorId: input.actorId,
    actorRole: input.actorRole,
    action: ok ? "jobs_whatsapp_sent" : "jobs_whatsapp_failed",
    entityType: input.entityType,
    entityId: input.entityId,
    reason,
    payload: {
      phone: normalizedPhone,
      messageId,
      statusCode: response.status,
      errorCode: payload?.error?.code ?? null,
    },
  });

  return {
    ok,
    status: ok ? ("sent" as const) : ("failed" as const),
    reason,
    messageId,
  };
}
