// V3-MKT-TRUST-01 — the two corpora the content rules are held to.
//
// HONEST: ordinary listings a Nigerian marketplace sees every day. Every one must
// publish — a rule that catches one of these costs an honest seller a sale.
// EVASIONS: contact details and payment steering written to dodge a filter (from
// adversarial round 1). None may publish.
//
// A line added here is a promise: change a rule, and both lists still hold.

/** Sentences that are appended to a clean listing's description; each must still publish. */
export const HONEST_TEXT: ReadonlyArray<string> = [
  "iPhone 15 Pro Max 256GB, natural titanium, battery health 98%.",
  "Tecno Spark 20 KJ5n, 8GB RAM + 128GB ROM, 5000mAh battery.",
  'Samsung 43CU7000 43" Crystal UHD smart TV, 2023 model.',
  "Dimensions: 80 x 120 x 200 cm. Weight 24.5kg.",
  "Power bank 20000mAh with 22.5W fast charge and two USB ports.",
  "Available sizes: EU 40, 41, 42, 43, 44, 45.",
  "Pack of 12 pieces. Buy 3 packs and save 10%.",
  "Was 25,000 now 18,500. Price is firm.",
  "ISBN 9780141439518. Paperback, 432 pages.",
  "ISBN 8173711461, Indian edition.",
  "Barcode 5012345678900 on the box.",
  "Toyota oil filter 90915-10003, fits Corolla 2009 to 2019.",
  "Model number SM-A546E/DS, serial available on request at delivery.",
  "Part no 04465-33471 front brake pads.",
  "Dispatched within 24 hours, delivered in 2 to 4 days.",
  "Open box, used for 2 weeks only. Comes with receipt.",
  "1 year warranty. 30 days return if faulty.",
  "Voltage 220-240V, 50/60Hz, 2000W.",
  "Polka dot dress, comfortable cotton, sizes 8 to 18.",
  "Use it at home or at the office.",
  "Works with WhatsApp video calls and Zoom.",
  "Ring light for TikTok and Instagram videos, 10 inch.",
  "Telegram stand not included.",
  "Contact lens case with mirror.",
  "Original and authentic, sealed in box.",
  "Inspired by classic designs.",
  "Kitchen knife set, 6 pieces, stainless steel.",
  "Wine glasses, set of 4, 350ml each.",
  "Vitamin C 1000mg supplements, 60 tablets, NAFDAC reg 01-2345.",
  "Shotgun microphone for cameras, 3.5mm jack.",
  "Bubble machine gun toy for kids, uses 4 AA batteries.",
  "Leopard print scarf, 180 x 70 cm.",
  "Counterfeit note detector with UV lamp for shops.",
  "You won't regret it. Quality guaranteed.",
  "Ring sizes 6, 7, 8, 9, 10, 11, 12.",
  "Pipe fittings: 1/2, 3/4, 1, 1 1/4 inch.",
  "Kills white ants and termites. 1 litre bottle.",
  "Solar inverter 3.5kVA 24V with MPPT 100A charge controller.",
  "Generator 2.5kVA, key start, 15 litre tank.",
  "Laptop: Core i5 1135G7, 8GB/256GB SSD, 14 inch FHD.",
  "Canon EOS 2000D with 18-55mm lens, 24.1MP.",
  "Shoe size 42 fits UK 8. True to size.",
  "Children's bicycle, 16 inch wheels, ages 5 to 8.",
  "Human hair wig, 22 inches, 180% density, 13x4 lace frontal.",
  "Ankara fabric, 6 yards, 100% cotton wax print.",
  "Rice cooker 1.8L, 700W, non-stick pot.",
  "Standing fan 18 inch, 3 speeds, 60W.",
  "Office chair with lumbar support, holds up to 120kg.",
  "Mattress 6 x 6 x 10 inches, orthopaedic foam.",
  "Blender 1.5L, 350W with grinder cup.",
  "Gas cooker, 4 burners with oven, 60 x 60 cm.",
  "Water dispenser, hot and cold, with storage cabinet.",
  "Deep freezer 200 litres, low voltage start from 135V.",
  "Pay on delivery available within Lagos.",
  "Pay with your card or bank transfer at checkout.",
  "Free delivery on orders above 50,000.",
  "Pickup available at Ikeja. Delivery nationwide in 3 to 5 days.",
  "Batch 2024, expiry 06/2027.",
  "Tyre size 195/65R15, load index 91H.",
  "Screen protector for Infinix Hot 40i, 2 pieces.",
  "HP 250 G8 battery, HT03XL, 3-cell 41.9Wh.",
  "Colour: black, navy, wine. Material: leather.",
  "Follow the washing instructions on the label.",
  "Great for home, office and shop use.",
  "Net weight 500g. Store in a cool, dry place.",
  "Suitable for ages 3 and above.",
  "Delivery fee is shown at checkout.",
  "Bluetooth 5.3, range up to 10 metres, 30 hours playtime.",
  "Stock is limited to 15 units.",
  "Phone case for iPhone 13, 13 Pro and 14.",
  "Accessory kit, 35 pieces, for drills up to 13mm.",
  "Opens from 0700 hours. Closed on Sundays.",
  "Length 1200mm, width 600mm, thickness 18mm.",
  "Order number is printed on the receipt you get after checkout.",
  "A very durable product. It lasts for years.",
  "Comes in a pack. Net content 750 ml.",
  "Church organ for sale, 61 keys with stand.",
  "Leopard skin print blouse, sizes 10 to 16.",
  "Laser printer, first copy out time 8 seconds, 30 pages per minute.",
  "Use it to kill white ants around the house.",
  "Black and white striped shirt.",
  "Anti-counterfeit hologram stickers, roll of 500.",
  // round 2: naming an app is not sending the buyer to it
  "Selfie stick works with Instagram and Snapchat.",
  "Tripod for TikTok, YouTube and Facebook live.",
  "Gimbal stabiliser for vlogging on Instagram Reels.",
  "Compatible with Snapchat.",
  "Perfect lighting for Instagram.",
  "Follow the latest styles on Instagram.",
  "Also available on Telegram.",
  "Find inspiration on TikTok for styling this piece.",
  "Records Instagram 1080p clips and TikTok 60fps video.",
  "Deal directly with our verified checkout, buyer protection applies.",
  // round 2: numbers that are not a phone number cut in two
  "We open from 0700 to 2100 daily including holidays.",
  "Dimensions 0803 mm by 1234 mm (custom cut available).",
  // round 2: money words with an honest meaning
  "POS machine with receipt printer, works with every bank card.",
  "Bank-grade steel safe with digital lock.",
  "Account book, 200 pages, hard cover.",
  "Cash counting machine, counts 1000 notes per minute.",
  "Heat transfer paper, A4, pack of 100.",
  "Direct from the factory, direct drive motor.",
  "Outside diameter 110 mm, for outside use.",
  "A great deal for the price.",
  "Chain link fence, 50 metre roll.",
  "Dot matrix printer ribbon.",
  "Signal booster for 4G networks, snap button closure on the pouch.",
  "Scan the QR code on the box to verify it is original.",
  "Christmas tree, 180 cm, 210 cm and 240 cm.",
  "One and two bedroom sizes, three and four seater options.",
  "ISBN 0141439513, paperback, 432 pages.",
  "Part number 1234567890, sold in a pack of 2.",
  "Just transfer the files with the USB cable, no software needed.",
  "The camera sends an alert to your phone when it detects motion.",
  "Delivery price for outside Lagos is shown at checkout.",
  "Upfront price, no hidden charges.",
  "Skype and Zoom ready headset with a noise-cancelling microphone.",
  "Works with Truecaller and every dialler app.",
  "Sizes 40 by 60 and 60 by 90 cm.",
  "Ships in 2 to 4 days, or 5 to 7 days outside the state.",
];

/** Store names an honest seller might choose. Each must pass the store-profile screen. */
export const HONEST_STORE_NAMES: ReadonlyArray<string> = [
  "Adaeze Fabrics",
  "Lagos Gadget Hub",
  "PowerHouse NG",
  "Mama Tee Kitchen",
  "Royal Touch Interiors",
  "Chidi & Sons Electronics",
  "The Wig Room",
  "Bolu Shoes and Bags",
  "Kike Fabrics",
];

/** Appended to a clean description; none may publish. */
export const EVASIONS: ReadonlyArray<string> = [
  // plain and the owner's own example
  "08031234567",
  "o8o 3123 4567",
  "o8o3 l23 4567",
  "+234 803 123 4567",
  // invisible characters, odd separators
  "0803­1234567",
  "0803⁦1234567",
  "0803͏1234567",
  "0803🔥123🔥4567",
  "0803#123#4567",
  "0803‑123‑4567",
  "0803 {123} 4567",
  "0803 | 123 | 4567",
  // glued letters, dropped zero
  "call08031234567",
  "WhatsApp08031234567",
  "08031234567whatsapp",
  "N08031234567",
  "08031234567a",
  "my number 8031234567",
  "phone 8031234567",
  "8031234567",
  "803 123 4567",
  // look-alikes
  "О8О3 123 4567",
  "Ο8Ο3 123 4567",
  "⓿❽⓿❸❶❷❸❹❺❻❼",
  "08031234S67",
  "0B031234567",
  "0803IZ34567",
  "0803 1234 S67",
  "zero8zero31234567",
  "zeroeightzerothree onetwothree fourfivesixseven",
  "Zero8Zero3 One2Three 4Five6Seven",
  // accounts and steering
  "GTBank 0123456789 Ade Shop",
  "send to 0123456789 GTB",
  "Acct: 0123456789 Access Bank",
  "account number 0123456789",
  "Opay 8031234567",
  "Palmpay 9031234567",
  "send money to 0123456789",
  "transfer directly",
  "pay to my account",
  "pay on delivery to my account",
  "50% deposit to my GTB before I ship",
  "cheaper if you pay me outside",
  "cheaper off the app",
  "buy direct from me",
  "do not pay here, pay when you see me",
  "dm for account details",
  "discount if we deal privately",
  "let us finish this deal offline",
  "no platform charges if you buy from me direct",
  "account details in the picture",
  "transfer only",
  "USDT accepted, TRC20",
  // links, handles, emails
  "wa.link/8kq2mz",
  "selar.co/adeshop",
  "paystack.shop/adeshop",
  "adeshop.store",
  "ADESHOP.STORE",
  "adeshop.myshopify.com",
  "adeshop dot com",
  "adeshop .com",
  "adeshop[.]com",
  "shorturl.at/abc12",
  "x.com/adeshop",
  "IG adeshop_ng",
  "instagram adeshop_ng",
  "we are adeshop_ng on instagram",
  "our tiktok is adeshop_ng",
  "snapchat adeshop22",
  "chat me on watsap",
  "chat me on wassap",
  "chat me on WA",
  "available on whatsapp for orders",
  "find Ade Shop NG on facebook",
  "adeshop@gmail,com",
  "adeshop@gmail",
  "adeshop @ gmail",
  "adeshop at gmail",
  "gmail: adeshop",
  "the number is on the picture",
  "check my store name for my number",
  // round 2: account numbers without a bank name, USSD, Pidgin
  "my aza is 0123456789",
  "aza: 0123456789",
  "pay small small to my aza",
  "just send to 0123456789",
  "0123456789 send alert",
  "number to credit: 0123456789",
  "*737*1*5000*0123456789#",
  "dial *894*0123456789# to pay me",
  "GTB is my bank, personal collection line for alerts only 0123456789",
  "make we talk price for outside",
  "settle the balance to my number",
  "transfer come my side",
  "no be here you go pay, na outside",
  "cheaper when you order from my page",
  "drop your number make I call you",
  "leave your number for review section",
  "put your contact for the comment",
  "deal with me directly",
  // round 2: the link is somewhere else
  "link in bio",
  "check the link in my bio",
  "my linktree is in the bio",
  "scan the QR code to order",
  // round 2: read out with joining words, in Pidgin
  "zero eight zero three then one two three then four five six seven",
  "zero eight zero three and one two three and four five six seven",
  "zero eight zero tree one two tree four five six seven",
  "0803 then 123 then 4567",
  "search adeshop on Instagram",
  // round 2, second wave
  "send to this 10 digit: 0123456789",
  "0803 x 123 x 4567",
  "0803 / / / 123 / / / 4567",
  "O8O3IZ34S67",
  "o8o3onetwothreefourfivesixseven",
  "0123456789",
  "a.c 0123456789",
  "wire it to 0123456789",
  "kudimoney 0123456789",
  "make I give you my correct price for outside",
  "no dey pay for here, call me",
  "send alert after transfer",
  "pay me for hand",
  "settle me outside na",
  "price na for WhatsApp",
  "come carry am, pay cash, forget this app",
  "no need to checkout, just transfer",
  "DM the word PRICE to my line",
  "message my personal line",
  "deposit first before I release",
  "send half upfront to secure",
  "pay me through my merchant app",
  "adeshop(dot)store",
  "adeshop dot store",
  "adeshop dot shop",
  "adeshop\u3002com",
  "add me on botim",
  "buzz me on signal",
  "hmu on ig",
  "holla at adeshop_ng",
  "ping adeshop on snap",
  "we dey for tiktok as adeshop",
];
